package it.eng.spagobi.functions.metadata;

// Generated 10-mag-2016 14.47.57 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiCatalogFunction generated by hbm2java
 */
public class SbiCatalogFunction extends SbiHibernateModel {

	private int functionId;
	private String name;
	private String description;
	private String language;
	private String script;
	private String owner;
	private String keywords;
	private String label;
	private String type;
	private boolean remote;
	private String url;
	private Set sbiFunctionInputVariables = new HashSet(0);
	private Set sbiFunctionOutputs = new HashSet(0);
	private Set sbiFunctionInputDatasets = new HashSet(0);
	private Set sbiFunctionInputFiles = new HashSet(0);

	public SbiCatalogFunction() {
	}

	public SbiCatalogFunction(int functionId, String name, String description, String language, String script, String owner, String keywords, String label,
			boolean remote, String url, String type) {
		this.functionId = functionId;
		this.name = name;
		this.description = description;
		this.language = language;
		this.script = script;
		this.owner = owner;
		this.keywords = keywords;
		this.label = label;
		this.type = type;
		this.url = url;
		this.remote = remote;
	}

	public int getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(int functionId) {
		this.functionId = functionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public void setRemote(boolean remote) {
		this.remote = remote;
	}

	public boolean isRemote() {
		return remote;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return url;
	}

	public Set getSbiFunctionInputVariables() {
		return this.sbiFunctionInputVariables;
	}

	public void setSbiFunctionInputVariables(Set sbiFunctionInputVariables) {
		this.sbiFunctionInputVariables = sbiFunctionInputVariables;
	}

	public Set getSbiFunctionOutputs() {
		return this.sbiFunctionOutputs;
	}

	public void setSbiFunctionOutputs(Set sbiFunctionOutputs) {
		this.sbiFunctionOutputs = sbiFunctionOutputs;
	}

	public Set getSbiFunctionInputDatasets() {
		return sbiFunctionInputDatasets;
	}

	public void setSbiFunctionInputDatasets(Set sbiFunctionInputDatasets) {
		this.sbiFunctionInputDatasets = sbiFunctionInputDatasets;
	}

	public Set getSbiFunctionInputFiles() {
		return sbiFunctionInputFiles;
	}

	public void setSbiFunctionInputFiles(Set sbiFunctionInputFiles) {
		this.sbiFunctionInputFiles = sbiFunctionInputFiles;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
