/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.behaviouralmodel.analyticaldriver.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;




/**
 * SbiParuseDetId generated by hbm2java
 */
public class SbiParuseDetId  implements java.io.Serializable {

    // Fields    

     private SbiParuse sbiParuse;
     private SbiExtRoles sbiExtRoles;


    // Constructors

    /**
     * default constructor.
     */
    public SbiParuseDetId() {
    }
    
   
    
    

    // Property accessors

    /**
     * Gets the sbi paruse.
     * 
     * @return the sbi paruse
     */
    public SbiParuse getSbiParuse() {
        return this.sbiParuse;
    }
    
    /**
     * Sets the sbi paruse.
     * 
     * @param sbiParuse the new sbi paruse
     */
    public void setSbiParuse(SbiParuse sbiParuse) {
        this.sbiParuse = sbiParuse;
    }

    /**
     * Gets the sbi ext roles.
     * 
     * @return the sbi ext roles
     */
    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    /**
     * Sets the sbi ext roles.
     * 
     * @param sbiExtRoles the new sbi ext roles
     */
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }

   /* (non-Javadoc)
    * @see java.lang.Object#equals(java.lang.Object)
    */
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiParuseDetId) ) return false;
		 SbiParuseDetId castOther = ( SbiParuseDetId ) other; 
         
		 return (this.getSbiParuse()==castOther.getSbiParuse()) || ( this.getSbiParuse()!=null && castOther.getSbiParuse()!=null && this.getSbiParuse().equals(castOther.getSbiParuse()) )
 && (this.getSbiExtRoles()==castOther.getSbiExtRoles()) || ( this.getSbiExtRoles()!=null && castOther.getSbiExtRoles()!=null && this.getSbiExtRoles().equals(castOther.getSbiExtRoles()) );
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSbiParuse().hashCode();
         result = 37 * result + this.getSbiExtRoles().hashCode();
         return result;
   }   


}