/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.behaviouralmodel.analyticaldriver.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;





/**
 * SbiParuseDet generated by hbm2java
 */
public class SbiParuseDet  extends SbiHibernateModel {

    // Fields    

     private SbiParuseDetId id;
     private Integer prog;
     
     private Short hiddenFl;
     private String defaultVal;


    // Constructors

    /**
     * default constructor.
     */
    public SbiParuseDet() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiParuseDet(SbiParuseDetId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiParuseDetId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiParuseDetId id) {
        this.id = id;
    }

    /**
     * Gets the prog.
     * 
     * @return the prog
     */
    public Integer getProg() {
        return this.prog;
    }
    
    /**
     * Sets the prog.
     * 
     * @param prog the new prog
     */
    public void setProg(Integer prog) {
        this.prog = prog;
    }



	/**
	 * Gets the default val.
	 * 
	 * @return the default val
	 */
	public String getDefaultVal() {
		return defaultVal;
	}
	
	/**
	 * Sets the default val.
	 * 
	 * @param defaultVal the new default val
	 */
	public void setDefaultVal(String defaultVal) {
		this.defaultVal = defaultVal;
	}
	
	/**
	 * Gets the hidden fl.
	 * 
	 * @return the hidden fl
	 */
	public Short getHiddenFl() {
		return hiddenFl;
	}
	
	/**
	 * Sets the hidden fl.
	 * 
	 * @param hiddenFl the new hidden fl
	 */
	public void setHiddenFl(Short hiddenFl) {
		this.hiddenFl = hiddenFl;
	}
}