/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.metadata;

// Generated 19-feb-2016 16.57.14 by Hibernate Tools 3.6.0

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiKpiRule generated by hbm2java
 */
public class SbiKpiRule extends SbiHibernateModel implements java.io.Serializable {

	private SbiKpiRuleId sbiKpiRuleId = new SbiKpiRuleId();
	private String name;
	private String definition;
	private Integer dataSourceId;
	private Character active;

	private Set<SbiKpiRuleOutput> sbiKpiRuleOutputs = new HashSet<>(0);
	private Set<SbiKpiPlaceholder> sbiKpiPlaceholders = new HashSet<>(0);

	/**
	 * @return the sbiKpiRuleId
	 */
	public SbiKpiRuleId getSbiKpiRuleId() {
		return sbiKpiRuleId;
	}

	/**
	 * @param sbiKpiRuleId
	 *            the sbiKpiRuleId to set
	 */
	public void setSbiKpiRuleId(SbiKpiRuleId sbiKpiRuleId) {
		this.sbiKpiRuleId = sbiKpiRuleId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the definition
	 */
	public String getDefinition() {
		return definition;
	}

	/**
	 * @param definition
	 *            the definition to set
	 */
	public void setDefinition(String definition) {
		this.definition = definition;
	}

	/**
	 * @return the dataSourceId
	 */
	public Integer getDataSourceId() {
		return dataSourceId;
	}

	/**
	 * @param dataSourceId
	 *            the dataSourceId to set
	 */
	public void setDataSourceId(Integer dataSourceId) {
		this.dataSourceId = dataSourceId;
	}

	/**
	 * @return the sbiKpiRuleOutputs
	 */
	public Set<SbiKpiRuleOutput> getSbiKpiRuleOutputs() {
		return sbiKpiRuleOutputs;
	}

	/**
	 * @param sbiKpiRuleOutputs
	 *            the sbiKpiRuleOutputs to set
	 */
	public void setSbiKpiRuleOutputs(Set<SbiKpiRuleOutput> sbiKpiRuleOutputs) {
		this.sbiKpiRuleOutputs = sbiKpiRuleOutputs;
	}

	/**
	 * @return the sbiKpiPlaceholders
	 */
	public Set<SbiKpiPlaceholder> getSbiKpiPlaceholders() {
		return sbiKpiPlaceholders;
	}

	/**
	 * @param sbiKpiPlaceholders
	 *            the sbiKpiPlaceholders to set
	 */
	public void setSbiKpiPlaceholders(Set<SbiKpiPlaceholder> sbiKpiPlaceholders) {
		this.sbiKpiPlaceholders = sbiKpiPlaceholders;
	}

	/**
	 * @return the active
	 */
	public Character getActive() {
		return active;
	}

	/**
	 * @param active
	 *            the active to set
	 */
	public void setActive(Character active) {
		this.active = active;
	}

}
