package it.eng.spagobi.kpi.metadata;

// Generated 19-feb-2016 16.57.14 by Hibernate Tools 3.6.0

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiKpiRule generated by hbm2java
 */
public class SbiKpiRule extends SbiHibernateModel implements java.io.Serializable {

	private Integer id;
	private String name;
	private String definition;
	private Set<SbiKpiRuleOutput> sbiKpiRuleOutputs = new HashSet(0);
	private Set<SbiKpiPlaceholder> sbiKpiPlaceholders = new HashSet(0);

	public SbiKpiRule() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public Set getSbiKpiRuleOutputs() {
		return this.sbiKpiRuleOutputs;
	}

	public void setSbiKpiRuleOutputs(Set sbiKpiRuleOutputs) {
		this.sbiKpiRuleOutputs = sbiKpiRuleOutputs;
	}

	public Set getSbiKpiPlaceholders() {
		return this.sbiKpiPlaceholders;
	}

	public void setSbiKpiPlaceholders(Set sbiKpiPlaceholders) {
		this.sbiKpiPlaceholders = sbiKpiPlaceholders;
	}

}
