package it.eng.spagobi.kpi.metadata;

// Generated 19-feb-2016 16.57.14 by Hibernate Tools 3.6.0

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

/**
 * SbiKpiPlaceholder generated by hbm2java
 */
public class SbiKpiPlaceholder extends SbiHibernateModel implements java.io.Serializable {

	private Integer id;
	private String name;

	public SbiKpiPlaceholder() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
