--- START ---
RENAME TABLE SBI_I18N_MESSAGES TO SBI_I18N_MESSAGES_OLD;

CREATE TABLE SBI_I18N_MESSAGES (ID INT) AS 
SELECT (@ROW := @ROW + 1) AS ID, T.*
FROM SBI_I18N_MESSAGES_OLD T, (SELECT @ROW := 0) R;

DROP TABLE SBI_I18N_MESSAGES_OLD;

ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT PK_SBI_I18N_MESSAGES PRIMARY KEY (ID);
ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT FK_SBI_I18N_MESSAGES FOREIGN KEY (LANGUAGE_CD) REFERENCES SBI_DOMAINS (VALUE_ID);
ALTER TABLE SBI_I18N_MESSAGES ADD UNIQUE SBI_I18N_MESSAGES_UNIQUE(LANGUAGE_CD, LABEL, ORGANIZATION);

INSERT INTO hibernate_sequences VALUES ('SBI_I18N_MESSAGES',
                                                            (SELECT COALESCE(MAX(m.ID) + 1, 1) FROM SBI_I18N_MESSAGES m));
COMMIT;                                                            
--- END ---

ALTER TABLE SBI_DATA_SET ADD UNIQUE XAK2SBI_DATA_SET (NAME, VERSION_NUM, ORGANIZATION);

ALTER TABLE SBI_ATTRIBUTE ADD COLUMN AFTER ATTRIBUTE_ID (LOV_ID INTEGER NULL,ALLOW_USER SMALLINT(6) NULL,MULTIALUE SMALLINT(6) NULL,SYNTAX SMALLINT(6) NULL,
									  VALUE_TYPE_ID INTEGER NULL, VALUE_TYPE_CD VARCHAR(20) , VALUE_TYPE ENUM('STRING','DATE','NUM'));
ALTER TABLE SBI_ATTRIBUTE ADD CONSTRAINT FK_LOV FOREIGN KEY (LOV_ID) REFERENCES SBI_LOV(LOV_ID) ON DELETE RESTRICT;

ALTER TABLE `SBI_ATTRIBUTE` CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(500) NULL;