--- START ---
RENAME TABLE SBI_I18N_MESSAGES TO SBI_I18N_MESSAGES_OLD;

CREATE TABLE SBI_I18N_MESSAGES (ID INT) AS 
SELECT (@ROW := @ROW + 1) AS ID, T.*
FROM SBI_I18N_MESSAGES_OLD T, (SELECT @ROW := 0) R;

DROP TABLE SBI_I18N_MESSAGES_OLD;

ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT PK_SBI_I18N_MESSAGES PRIMARY KEY (ID);
ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT FK_SBI_I18N_MESSAGES FOREIGN KEY (LANGUAGE_CD) REFERENCES SBI_DOMAINS (VALUE_ID);
ALTER TABLE SBI_I18N_MESSAGES ADD UNIQUE SBI_I18N_MESSAGES_UNIQUE(LANGUAGE_CD, LABEL, ORGANIZATION);

INSERT INTO hibernate_sequences VALUES ('SBI_I18N_MESSAGES',
                                                            (SELECT COALESCE(MAX(m.ID) + 1, 1) FROM SBI_I18N_MESSAGES m));
COMMIT;                                                            

ALTER TABLE SBI_DATA_SET ADD UNIQUE XAK2SBI_DATA_SET (NAME, VERSION_NUM, ORGANIZATION);

ALTER TABLE SBI_ATTRIBUTE ADD COLUMN  LOV_ID INTEGER NULL AFTER ATTRIBUTE_ID, 
						  ADD COLUMN  ALLOW_USER SMALLINT(6) DEFAULT '1' AFTER LOV_ID, 
						  ADD COLUMN  MULTIVALUE SMALLINT(6) DEFAULT '0' AFTER ALLOW_USER, 
						  ADD COLUMN  SYNTAX SMALLINT(6) NULL AFTER MULTIVALUE,
						  ADD COLUMN  VALUE_TYPE_ID INTEGER NULL AFTER SYNTAX, 
						  ADD COLUMN  VALUE_TYPE_CD VARCHAR(20) AFTER VALUE_TYPE_ID, 
						  ADD COLUMN  VALUE_TYPE ENUM ('STRING','DATE','NUM') AFTER VALUE_TYPE_CD;

ALTER TABLE `SBI_ATTRIBUTE` CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(500) NULL;

ALTER TABLE SBI_EVENTS_LOG ADD COLUMN EVENT_TYPE VARCHAR(50) DEFAULT 'SCHEDULER' NOT NULL;

UPDATE SBI_EVENTS_LOG SET EVENT_TYPE = (
CASE HANDLER 
	WHEN 'it.eng.spagobi.events.handlers.DefaultEventPresentationHandler' THEN 'SCHEDULER'
	WHEN 'it.eng.spagobi.events.handlers.CommonjEventPresentationHandler' THEN 'COMMONJ'
	WHEN 'it.eng.spagobi.events.handlers.TalendEventPresentationHandler' THEN 'ETL'
	WHEN 'it.eng.spagobi.events.handlers.WekaEventPresentationHandler' THEN 'DATA_MINING'
END
);
commit;

ALTER TABLE SBI_EVENTS_LOG DROP COLUMN HANDLER;

--- END ---

ALTER TABLE SBI_OUTPUT_PARAMETER MODIFY COLUMN FORMAT_VALUE varchar(30);



---BEGIN---
CREATE TABLE SBI_METAMODEL_PAR (
       METAMODEL_PAR_ID           INTEGER NOT NULL ,
       PAR_ID               INTEGER NOT NULL,
       METAMODEL_ID             INTEGER NOT NULL,
       LABEL                VARCHAR(40) NOT NULL,
       REQ_FL               SMALLINT NULL,
       MOD_FL               SMALLINT NULL,
       VIEW_FL              SMALLINT NULL,
       MULT_FL              SMALLINT NULL,
       PROG                 INTEGER NOT NULL,
       PARURL_NM            VARCHAR(20) NULL,
       PRIORITY             INTEGER NULL,
       COL_SPAN             INTEGER NULL DEFAULT 1,
       THICK_PERC           INTEGER NULL DEFAULT 0,
       USER_IN              VARCHAR(100) NOT NULL,
       USER_UP              VARCHAR(100),
       USER_DE              VARCHAR(100),
       TIME_IN              TIMESTAMP NOT NULL,
       TIME_UP              TIMESTAMP NULL DEFAULT NULL,
       TIME_DE              TIMESTAMP NULL DEFAULT NULL,
       SBI_VERSION_IN       VARCHAR(10),
       SBI_VERSION_UP       VARCHAR(10),
       SBI_VERSION_DE       VARCHAR(10),
       META_VERSION         VARCHAR(100),
       ORGANIZATION         VARCHAR(20),     
       PRIMARY KEY (METAMODEL_PAR_ID)
) ENGINE=InnoDB;
ALTER TABLE SBI_METAMODEL_PAR 					ADD CONSTRAINT FK_METAMODEL_PAR_1 					FOREIGN KEY (METAMODEL_ID) 				REFERENCES SBI_META_MODELS (ID) 	ON DELETE RESTRICT;
ALTER TABLE SBI_METAMODEL_PAR 					ADD CONSTRAINT FK_METAMODEL_PAR_2 					FOREIGN KEY (PAR_ID) 				REFERENCES SBI_PARAMETERS (PAR_ID) 		ON DELETE RESTRICT;

COMMIT;
---END---