--- START ---
RENAME TABLE SBI_I18N_MESSAGES TO SBI_I18N_MESSAGES_OLD;

CREATE TABLE SBI_I18N_MESSAGES (ID INT) AS 
SELECT (@ROW := @ROW + 1) AS ID, T.*
FROM SBI_I18N_MESSAGES_OLD T, (SELECT @ROW := 0) R;

DROP TABLE SBI_I18N_MESSAGES_OLD;

ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT PK_SBI_I18N_MESSAGES PRIMARY KEY (ID);
ALTER TABLE SBI_I18N_MESSAGES ADD CONSTRAINT FK_SBI_I18N_MESSAGES FOREIGN KEY (LANGUAGE_CD) REFERENCES SBI_DOMAINS (VALUE_ID);
ALTER TABLE SBI_I18N_MESSAGES ADD UNIQUE SBI_I18N_MESSAGES_UNIQUE(LANGUAGE_CD, LABEL, ORGANIZATION);

INSERT INTO hibernate_sequences VALUES ('SBI_I18N_MESSAGES',
                                                            (SELECT COALESCE(MAX(m.ID) + 1, 1) FROM SBI_I18N_MESSAGES m));
COMMIT;                                                            
--- END ---