-- 06/04/2021
UPDATE SBI_CONFIG SC SET VALUE_CHECK = 'it-IT,en-US,fr-FR,es-ES,pt-BR,en-GB,zh-Hans-CN,de-DE' WHERE LABEL = 'SPAGOBI.LANGUAGE_SUPPORTED.LANGUAGES';
UPDATE SBI_CONFIG SC SET VALUE_CHECK = 'en-US' WHERE LABEL = 'SPAGOBI.LANGUAGE_SUPPORTED.LANGUAGE.default';

UPDATE SBI_DOMAINS SET VALUE_CD = 'it-IT', DOMAIN_NM='Language tag code', VALUE_NM = 'Italian (IT)', VALUE_DS=VALUE_NM WHERE DOMAIN_CD = 'LANG' AND VALUE_NM = 'Italian' AND DOMAIN_NM = 'Language ISO code';
UPDATE SBI_DOMAINS SET VALUE_CD = 'en-US', DOMAIN_NM='Language tag code', VALUE_NM = 'English (US)', VALUE_DS=VALUE_NM WHERE DOMAIN_CD = 'LANG' AND VALUE_NM = 'English' AND DOMAIN_NM = 'Language ISO code';
UPDATE SBI_DOMAINS SET VALUE_CD = 'es-ES', DOMAIN_NM='Language tag code', VALUE_NM = 'Spanish (ES)', VALUE_DS=VALUE_NM WHERE DOMAIN_CD = 'LANG' AND VALUE_NM = 'Spanish' AND DOMAIN_NM = 'Language ISO code';
UPDATE SBI_DOMAINS SET VALUE_CD = 'fr-FR', DOMAIN_NM='Language tag code', VALUE_NM = 'French (FR)', VALUE_DS=VALUE_NM WHERE DOMAIN_CD = 'LANG' AND VALUE_NM = 'French' AND DOMAIN_NM = 'Language ISO code';
UPDATE SBI_DOMAINS SET VALUE_CD = 'pt-BR', DOMAIN_NM='Language tag code', VALUE_NM = 'Portoguese (BR)', VALUE_DS=VALUE_NM WHERE DOMAIN_CD = 'LANG' AND VALUE_NM = 'Portoguese' AND DOMAIN_NM = 'Language ISO code';

ALTER TABLE SBI_MENU ADD (CUST_ICON_CLOB CLOB);
UPDATE SBI_MENU SET CUST_ICON_CLOB = CUST_ICON;
ALTER TABLE SBI_MENU DROP COLUMN CUST_ICON;
ALTER TABLE SBI_MENU RENAME COLUMN CUST_ICON_CLOB TO CUST_ICON;

CREATE TABLE SBI_WIDGET_GALLERY (
  UUID CHAR(36) NOT NULL, -- primary key
  NAME VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(500) NULL,
  TYPE VARCHAR(45) NULL, -- HTML/CUSTOM CHART/PYTHON/R
  PREVIEW_IMAGE BLOB NULL, -- binary of preview file
  TEMPLATE CLOB NULL, -- text with template as a JSON
  AUTHOR VARCHAR(100) NULL,
  USAGE_COUNTER INT NULL, -- counter to see how many times the widgets was used
	USER_IN              VARCHAR2(100) NOT NULL,
		USER_UP              VARCHAR2(100),
		USER_DE              VARCHAR2(100),
		TIME_IN              TIMESTAMP NOT NULL,
		TIME_UP              TIMESTAMP DEFAULT NULL,
		TIME_DE              TIMESTAMP DEFAULT NULL,
		SBI_VERSION_IN       VARCHAR2(10),
		SBI_VERSION_UP       VARCHAR2(10),
		SBI_VERSION_DE       VARCHAR2(10),
		META_VERSION         VARCHAR2(100),
		ORGANIZATION         VARCHAR2(20),
		OUTPUT_TYPE         VARCHAR2(100),
 CONSTRAINT  XAK1SBI_WIDGET_GALLERY UNIQUE (NAME, ORGANIZATION),
  PRIMARY KEY (UUID)
);

CREATE TABLE SBI_WIDGET_GALLERY_TAGS (
  WIDGET_ID CHAR(36) NOT NULL, -- widget id reference
  TAG VARCHAR(50) NOT NULL, -- tag name
 USER_IN              VARCHAR2(100) NOT NULL,
		USER_UP              VARCHAR2(100),
		USER_DE              VARCHAR2(100),
		TIME_IN              TIMESTAMP NOT NULL,
		TIME_UP              TIMESTAMP DEFAULT NULL,
		TIME_DE              TIMESTAMP DEFAULT NULL,
		SBI_VERSION_IN       VARCHAR2(10),
		SBI_VERSION_UP       VARCHAR2(10),
		SBI_VERSION_DE       VARCHAR2(10),
		META_VERSION         VARCHAR2(100),
		ORGANIZATION         VARCHAR2(20),
  PRIMARY KEY  (WIDGET_ID, TAG),
  CONSTRAINT FK_SBI_WIDGET_GALLERY_TAGS_1 FOREIGN KEY (WIDGET_ID) REFERENCES SBI_WIDGET_GALLERY (UUID) ON DELETE CASCADE
);