angular.module('cockpitModule').factory('cockpitModule_generalOptions',function(sbiModule_translate){
	return{
		fontSizeDimension:	[
								{
									label:"",
									value:''
								 },
								 {
									 label:"0.5",
									 value:'0.5em'
								 },
								 {
									 label:"1.0",
									 value:'1.0em'
								 },
								 {
									 label:"1.5",
									 value:'1.5em'
								 },
								 {
									 label:"2.0",
									 value:'2.0em'
								 },
								 {
									 label:"2.5",
									 value:'2.3em'
								 }
		                  	
						 	],
		textDecoration:		[
								{
									label:"",
									value:''
								 },
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.overline"),
									value:'overline'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.underline"),
									value:'underline'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.lineThrough"),
									value:'line-through'
								}
							],
		fontWeight:			[
								{
									label:"",
									value:''
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.normal"),
									value:'normal'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.bold"),
									value:'bold'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.bolder"),
									value:'bolder'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.lighter"),
									value:'lighter'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.number"),
									value:'number'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.initial"),
									value:'initial'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.inherit"),
									value:'inherit'
								}
							],
	fontType:			[
	           			 {
	           				 label:"",
	           				 value:''
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.arial"),
	           				 value:'arial'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.curierNew"),
	           				 value:'curier-new'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.tahoma"),
	           				 value:'tahoma'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.timesNewRoman"),
	           				 value:'times-new-roman'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.verdana"),
	           				 value:'verdana'
	           			 }
	           			 ],
	           	aggregationFunctions:[
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.none"),
	    		    	                            	   value:"NONE"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.sum"),
	    		    	                            	   value:"SUM"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.avg"),
	    		    	                            	   value:"AVG"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.max"),
	    		    	                            	   value:"MAX"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.min"),
	    		    	                            	   value:"MIN"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.count"),
	    		    	                            	   value:"COUNT"
	    		    	                               },
	    		    	                               {
	    		    	                            	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.countdistinct"),
	    		    	                            	   value:"COUNT_DISTINCT"
	    		    	                               },
   		    	                               ]
		
	}
});