/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package it.eng.spagobi.cache.metadata;

// Generated 21-mag-2015 12.23.29 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;

/**
 * SbiCacheItem generated by hbm2java
 */
public class SbiCacheItem extends SbiHibernateModel {

	private String tableName;
	private String signature;
	private String name;
	private Long dimension;
	private Date creationDate;
	private Date lastUsedDate;
	private String properties;

	public SbiCacheItem() {
	}

	public SbiCacheItem(String tableName, String signature, String name) {
		this.tableName = tableName;
		this.signature = signature;
		this.name = name;
	}

	public SbiCacheItem(String tableName, String signature, String name, Long dimension, Date creationDate, Date lastUsedDate, String properties) {
		this.tableName = tableName;
		this.signature = signature;
		this.name = name;
		this.dimension = dimension;
		this.creationDate = creationDate;
		this.lastUsedDate = lastUsedDate;
		this.properties = properties;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getDimension() {
		return this.dimension;
	}

	public void setDimension(Long dimension) {
		this.dimension = dimension;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUsedDate() {
		return this.lastUsedDate;
	}

	public void setLastUsedDate(Date lastUsedDate) {
		this.lastUsedDate = lastUsedDate;
	}

	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}
}
