package it.eng.spagobi.commons.constants;

public final class ConfigurationConstants {

	public static final String SPAGOBI_DATASET_ASSOCIATIONS_AUTODETECT_SAMPLES = "SPAGOBI.DATASET.ASSOCIATIONS.AUTODETECT.SAMPLES";
	public static final String SPAGOBI_DATASET_ASSOCIATIVE_LOGIC_STRATEGY = "SPAGOBI.DATASET.ASSOCIATIVE_LOGIC.STRATEGY";
	public static final String DOCUMENT_EXPORTING_PDF_FRONT_PAGE = "DOCUMENT.EXPORTING.PDF.FRONT_PAGE";
	public static final String DOCUMENT_EXPORTING_PDF_BACK_PAGE = "DOCUMENT.EXPORTING.PDF.BACK_PAGE";
}
