/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.profiling.bean;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

/**
 * SbiExtUserRoles generated by hbm2java
 */
public class SbiExtUserRoles extends SbiHibernateModel {

	private SbiExtUserRolesId id;
	private SbiUser sbiUser;

	public SbiExtUserRoles() {
	}

	public SbiExtUserRoles(SbiExtUserRolesId id, SbiUser sbiUser) {
		this.id = id;
		this.sbiUser = sbiUser;
	}

	public SbiExtUserRolesId getId() {
		return this.id;
	}

	public void setId(SbiExtUserRolesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((sbiUser == null) ? 0 : sbiUser.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SbiExtUserRoles other = (SbiExtUserRoles) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (sbiUser == null) {
			if (other.sbiUser != null)
				return false;
		} else if (!sbiUser.equals(other.sbiUser))
			return false;
		return true;
	}

}
