/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import it.eng.spagobi.commons.metadata.SbiExtRoles;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbiUser generated by hbm2java
 */
public class SbiUser extends SbiHibernateModel {

	private int id;
	private String userId;
	private String password;
	private String fullName;
	private Date dtPwdBegin;
	private Date dtPwdEnd;
	private Boolean flgPwdBlocked;
	private Date dtLastAccess;
	private Boolean isSuperadmin;

	private Set<SbiExtRoles> sbiExtUserRoleses = new HashSet<SbiExtRoles>(0);
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(0);

	public SbiUser() {
	}

	public SbiUser(int id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public SbiUser(int id, String userId, String password, String fullName, Date dtPwdBegin, Date dtPwdEnd, Boolean flgPwdBlocked, Date dtLastAccess,
			Set<SbiExtRoles> sbiExtUserRoleses, Set<SbiUserAttributes> sbiUserAttributeses, Boolean isSuperadmin) {
		this.id = id;
		this.userId = userId;
		this.password = password;
		this.fullName = fullName;
		this.dtPwdBegin = dtPwdBegin;
		this.dtPwdEnd = dtPwdEnd;
		this.flgPwdBlocked = flgPwdBlocked;
		this.dtLastAccess = dtLastAccess;
		this.sbiExtUserRoleses = sbiExtUserRoleses;
		this.sbiUserAttributeses = sbiUserAttributeses;
		this.isSuperadmin = isSuperadmin;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDtPwdBegin() {
		return this.dtPwdBegin;
	}

	public void setDtPwdBegin(Date dtPwdBegin) {
		this.dtPwdBegin = dtPwdBegin;
	}

	public Date getDtPwdEnd() {
		return this.dtPwdEnd;
	}

	public void setDtPwdEnd(Date dtPwdEnd) {
		this.dtPwdEnd = dtPwdEnd;
	}

	public Boolean getFlgPwdBlocked() {
		return this.flgPwdBlocked;
	}

	public void setFlgPwdBlocked(Boolean flgPwdBlocked) {
		this.flgPwdBlocked = flgPwdBlocked;
	}

	public Date getDtLastAccess() {
		return this.dtLastAccess;
	}

	public void setDtLastAccess(Date dtLastAccess) {
		this.dtLastAccess = dtLastAccess;
	}

	public Set<SbiExtRoles> getSbiExtUserRoleses() {
		return this.sbiExtUserRoleses;
	}

	public void setSbiExtUserRoleses(Set<SbiExtRoles> sbiExtUserRoleses) {
		this.sbiExtUserRoleses = sbiExtUserRoleses;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public Boolean getIsSuperadmin() {
		return this.isSuperadmin;
	}

	public void setIsSuperadmin(Boolean isSuperadmin) {
		this.isSuperadmin = isSuperadmin;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SbiUser other = (SbiUser) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
