--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD COLUMN RESOURCE_CODE VARCHAR(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
ALTER TABLE SBI_RESOURCES ADD UNIQUE INDEX UNIQUE_RES_CODE (RESOURCE_CODE);
ALTER TABLE SBI_RESOURCES MODIFY COLUMN RESOURCE_CODE VARCHAR(45) NOT NULL;