ALTER TABLE SBI_CATALOG_FUNCTION ADD COLUMN DESCRIPTION TEXT NOT NULL AFTER NAME;

ALTER TABLE SBI_PARUSE ADD COLUMN OPTIONS VARCHAR(4000) NULL DEFAULT NULL

ALTER TABLE  SBI_GEO_MAPS ADD COLUMN HIERARCHY_NAME VARCHAR(100) AFTER FORMAT;
ALTER TABLE  SBI_GEO_MAPS ADD COLUMN LEVEL INTEGER AFTER HIERARCHY_NAME;
ALTER TABLE  SBI_GEO_MAPS ADD COLUMN MEMBER_NAME VARCHAR(100) AFTER LEVEL;
