/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.metadata;

// Generated 19-feb-2016 16.57.14 by Hibernate Tools 3.6.0

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiKpiThreshold generated by hbm2java
 */
public class SbiKpiThreshold extends SbiHibernateModel implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private SbiDomains type;
	private Set<SbiKpiThresholdValue> sbiKpiThresholdValues = new HashSet<>();

	public SbiKpiThreshold() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public SbiDomains getType() {
		return this.type;
	}

	public void setType(SbiDomains type) {
		this.type = type;
	}

	public Set<SbiKpiThresholdValue> getSbiKpiThresholdValues() {
		return this.sbiKpiThresholdValues;
	}

	public void setSbiKpiThresholdValues(Set<SbiKpiThresholdValue> sbiKpiThresholdValues) {
		this.sbiKpiThresholdValues = sbiKpiThresholdValues;
	}

}
