/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.profiling.bean;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

/**
 * SbiExtUserRoles generated by hbm2java
 */
public class SbiExtUserRoles extends SbiHibernateModel {

	private SbiExtUserRolesId id;
	private SbiUser sbiUser;

	public SbiExtUserRoles() {
	}

	public SbiExtUserRoles(SbiExtUserRolesId id, SbiUser sbiUser) {
		this.id = id;
		this.sbiUser = sbiUser;
	}

	public SbiExtUserRolesId getId() {
		return this.id;
	}

	public void setId(SbiExtUserRolesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((sbiUser == null) ? 0 : sbiUser.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SbiExtUserRoles other = (SbiExtUserRoles) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (sbiUser == null) {
			if (other.sbiUser != null)
				return false;
		} else if (!sbiUser.equals(other.sbiUser))
			return false;
		return true;
	}

}
