/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 *
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.profiling.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import it.eng.spagobi.commons.metadata.SbiExtRoles;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

/**
 * SbiUser generated by hbm2java
 */
public class SbiUser extends SbiHibernateModel {

	private int id;
	private String userId;
	private String password;
	private String fullName;
	private Date dtPwdBegin;
	private Date dtPwdEnd;
	private Boolean flgPwdBlocked;
	private Date dtLastAccess;
	private int failedLoginAttempts;

	private Boolean isSuperadmin;

	private Integer defaultRoleId;

	private Set<SbiExtRoles> sbiExtUserRoleses = new HashSet<SbiExtRoles>(0);
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(0);

	public SbiUser() {
	}

	public SbiUser(int id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public SbiUser(int id, String userId, String password, String fullName, Date dtPwdBegin, Date dtPwdEnd,
			Boolean flgPwdBlocked, Date dtLastAccess, Set<SbiExtRoles> sbiExtUserRoleses,
			Set<SbiUserAttributes> sbiUserAttributeses, Boolean isSuperadmin) {
		this.id = id;
		this.userId = userId;
		this.password = password;
		this.fullName = fullName;
		this.dtPwdBegin = dtPwdBegin;
		this.dtPwdEnd = dtPwdEnd;
		this.flgPwdBlocked = flgPwdBlocked;
		this.dtLastAccess = dtLastAccess;
		this.sbiExtUserRoleses = sbiExtUserRoleses;
		this.sbiUserAttributeses = sbiUserAttributeses;
		this.isSuperadmin = isSuperadmin;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFailedLoginAttempts(int failedLoginAttempts) {
		this.failedLoginAttempts = failedLoginAttempts;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDtPwdBegin() {
		return this.dtPwdBegin;
	}

	public void setDtPwdBegin(Date dtPwdBegin) {
		this.dtPwdBegin = dtPwdBegin;
	}

	public Date getDtPwdEnd() {
		return this.dtPwdEnd;
	}

	public void setDtPwdEnd(Date dtPwdEnd) {
		this.dtPwdEnd = dtPwdEnd;
	}

	public int getFailedLoginAttempts() {
		return failedLoginAttempts;
	}

	public Boolean getFlgPwdBlocked() {
		return this.flgPwdBlocked;
	}

	public void setFlgPwdBlocked(Boolean flgPwdBlocked) {
		this.flgPwdBlocked = flgPwdBlocked;
	}

	public Date getDtLastAccess() {
		return this.dtLastAccess;
	}

	public void setDtLastAccess(Date dtLastAccess) {
		this.dtLastAccess = dtLastAccess;
	}

	public Set<SbiExtRoles> getSbiExtUserRoleses() {
		return this.sbiExtUserRoleses;
	}

	public void setSbiExtUserRoleses(Set<SbiExtRoles> sbiExtUserRoleses) {
		this.sbiExtUserRoleses = sbiExtUserRoleses;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public Boolean getIsSuperadmin() {
		return this.isSuperadmin;
	}

	public void setIsSuperadmin(Boolean isSuperadmin) {
		this.isSuperadmin = isSuperadmin;
	}

	public Integer getDefaultRoleId() {
		return defaultRoleId;
	}

	public void setDefaultRoleId(Integer defaultRoleId) {
		this.defaultRoleId = defaultRoleId;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dtLastAccess == null) ? 0 : dtLastAccess.hashCode());
		result = prime * result + ((dtPwdBegin == null) ? 0 : dtPwdBegin.hashCode());
		result = prime * result + ((dtPwdEnd == null) ? 0 : dtPwdEnd.hashCode());
		result = prime * result + ((flgPwdBlocked == null) ? 0 : flgPwdBlocked.hashCode());
		result = prime * result + ((fullName == null) ? 0 : fullName.hashCode());
		result = prime * result + id;
		result = prime * result + ((isSuperadmin == null) ? 0 : isSuperadmin.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((sbiExtUserRoleses == null) ? 0 : sbiExtUserRoleses.hashCode());
		result = prime * result + ((sbiUserAttributeses == null) ? 0 : sbiUserAttributeses.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		result = prime * result + ((defaultRoleId == null) ? 0 : defaultRoleId.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SbiUser other = (SbiUser) obj;
		if (dtLastAccess == null) {
			if (other.dtLastAccess != null)
				return false;
		} else if (!dtLastAccess.equals(other.dtLastAccess))
			return false;
		if (dtPwdBegin == null) {
			if (other.dtPwdBegin != null)
				return false;
		} else if (!dtPwdBegin.equals(other.dtPwdBegin))
			return false;
		if (dtPwdEnd == null) {
			if (other.dtPwdEnd != null)
				return false;
		} else if (!dtPwdEnd.equals(other.dtPwdEnd))
			return false;
		if (flgPwdBlocked == null) {
			if (other.flgPwdBlocked != null)
				return false;
		} else if (!flgPwdBlocked.equals(other.flgPwdBlocked))
			return false;
		if (fullName == null) {
			if (other.fullName != null)
				return false;
		} else if (!fullName.equals(other.fullName))
			return false;
		if (id != other.id)
			return false;
		if (isSuperadmin == null) {
			if (other.isSuperadmin != null)
				return false;
		} else if (!isSuperadmin.equals(other.isSuperadmin))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (sbiExtUserRoleses == null) {
			if (other.sbiExtUserRoleses != null)
				return false;
		} else if (!sbiExtUserRoleses.equals(other.sbiExtUserRoleses))
			return false;
		if (sbiUserAttributeses == null) {
			if (other.sbiUserAttributeses != null)
				return false;
		} else if (!sbiUserAttributeses.equals(other.sbiUserAttributeses))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		if (defaultRoleId == null) {
			if (other.defaultRoleId != null)
				return false;
		} else if (!defaultRoleId.equals(other.defaultRoleId))
			return false;
		return true;
	}

}
