--- START ---
-- 2020-09-11 Adding Portuguese language in case it is missing
update SBI_CONFIG set VALUE_CHECK = CONCAT(VALUE_CHECK, ',[pt,BR]') WHERE LABEL = 'SPAGOBI.LANGUAGE_SUPPORTED.LANGUAGES' and VALUE_CHECK not like '%[pt,BR]%';
commit;

-- 2020-01-12 Matteo Massarotto
ALTER TABLE SBI_DOSSIER_ACTIVITY ADD DOC BLOB NULL; 
ALTER TABLE SBI_DOSSIER_ACTIVITY ADD CONFIG VARCHAR(4000) NULL;
