/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package it.eng.spagobi.federateddataset.metadata;

// Generated 4-giu-2009 12.50.24 by Hibernate Tools 3.1.0 beta3

/**
 * SbiExportersId generated by hbm2java
 */

public class SbiDataSetFederationId implements java.io.Serializable {

	// Fields
	private int federationId;
	private int dsId;
	private int versionNum;
	private String organization;

	public SbiDataSetFederationId() {
		super();
	}

	public int getFederationId() {
		return federationId;
	}

	public void setFederationId(int federationId) {
		this.federationId = federationId;
	}

	public int getDsId() {
		return dsId;
	}

	public void setDsId(int dsId) {
		this.dsId = dsId;
	}

	public int getVersionNum() {
		return versionNum;
	}

	public void setVersionNum(int versionNum) {
		this.versionNum = versionNum;
	}

	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public SbiDataSetFederationId(int federationId, int dsId, int versionNum, String organization) {
		super();
		this.federationId = federationId;
		this.dsId = dsId;
		this.versionNum = versionNum;
		this.organization = organization;
	}

}
