CREATE TABLE SBI_HOMEPAGE (
  ID int(11) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  DOCUMENT_ID int(11) DEFAULT NULL,
  IMAGE_URL VARCHAR(4000) DEFAULT NULL,
  STATIC_PAGE VARCHAR(255) DEFAULT NULL,
  HTML LONGTEXT,
  CSS LONGTEXT,
  MENU_PLACEHOLDERS LONGTEXT,
  IS_DEFAULT tinyint(1) NOT NULL DEFAULT 0,
  USER_IN VARCHAR(100) NOT NULL,
  USER_UP VARCHAR(100) DEFAULT NULL,
  USER_DE VARCHAR(100) DEFAULT NULL,
  TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TIME_UP timestamp NULL DEFAULT NULL,
  TIME_DE timestamp NULL DEFAULT NULL,
  SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
  SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
  SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
  META_VERSION VARCHAR(100) DEFAULT NULL,
  ORGANIZATION VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_SBI_HOMEPAGE_1 FOREIGN KEY (DOCUMENT_ID) REFERENCES SBI_OBJECTS (BIOBJ_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;

CREATE TABLE SBI_HOMEPAGE_ROLE (
  HOMEPAGE_ID int(11) NOT NULL,
  EXT_ROLE_ID int(11) NOT NULL,
  PRIMARY KEY (HOMEPAGE_ID,EXT_ROLE_ID),
  CONSTRAINT FK_SBI_HOMEPAGE_ROLE_1 FOREIGN KEY (HOMEPAGE_ID) REFERENCES SBI_HOMEPAGE (ID) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT FK_SBI_HOMEPAGE_ROLE_2 FOREIGN KEY (EXT_ROLE_ID) REFERENCES SBI_EXT_ROLES (EXT_ROLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB;

insert into hibernate_sequences(next_val,sequence_name) values (ifnull((select max(ID)+1 from SBI_HOMEPAGE),1),'SBI_HOMEPAGE');

COMMIT;
