  CREATE TABLE "HIER_MASTER_TECHNICAL" 
   (	
	"MT_ID" NUMBER(19,0) NOT NULL, 
	"HIER_CD_T" CHAR(20 BYTE) DEFAULT NULL, 
	"HIER_NM_T" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"DIMENSION" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"NODE_CD_T" CHAR(50 BYTE) DEFAULT NULL, 
	"NODE_NM_T" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"NODE_LEV_T" NUMBER(6,0) DEFAULT NULL, 
	"GENERAL_INFO_T" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"PATH_CD_T" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"PATH_NM_T" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"HIER_CD_M" CHAR(20 BYTE) DEFAULT NULL, 
	"HIER_NM_M" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"NODE_CD_M" CHAR(50 BYTE) DEFAULT NULL, 
	"NODE_NM_M" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"NODE_LEV_M" NUMBER(6,0) DEFAULT NULL, 
	"BACKUP" NUMBER(1,0) DEFAULT 0, 
	"BACKUP_TIMESTAMP" TIMESTAMP (6) DEFAULT NULL, 
	 CONSTRAINT "MT_ID_PK" PRIMARY KEY ("MT_ID") DISABLE
   );
   
   CREATE TABLE "HIER_MASTERS_CONFIG" 
   (	
	"HIER_MASTER_ID" NUMBER(*,0) NOT NULL, 
	"HIER_CD" CHAR(20 BYTE) NOT NULL, 
	"HIER_NM" VARCHAR2(100 BYTE), 
	"CONFIGURATION" CLOB, 
	"TIME_IN" TIMESTAMP (6), 
	PRIMARY KEY ("HIER_MASTER_ID")
   );