/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.profiling.bean;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

/**
 * SbiExtUserRoles generated by hbm2java
 */
public class SbiExtUserRoles extends SbiHibernateModel {

	private SbiExtUserRolesId id;
	private SbiUser sbiUser;

	public SbiExtUserRoles() {
	}

	public SbiExtUserRoles(SbiExtUserRolesId id, SbiUser sbiUser) {
		this.id = id;
		this.sbiUser = sbiUser;
	}

	public SbiExtUserRolesId getId() {
		return this.id;
	}

	public void setId(SbiExtUserRolesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

}
