ALTER TABLE SBI_KPI_KPI ALTER COLUMN DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_RULE ALTER COLUMN DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_VALUE ALTER COLUMN LOGICAL_KEY VARCHAR(4000) NOT NULL;