ALTER TABLE SBI_KPI_KPI ALTER COLUMN DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_RULE ALTER COLUMN DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_VALUE ALTER COLUMN LOGICAL_KEY VARCHAR(4000) NOT NULL;

ALTER TABLE SBI_META_MODEL ADD CONSTRAINT FK_META_MODELS_DS_ID FOREIGN KEY (DATA_SOURCE_ID) REFERENCES SBI_DATA_SOURCE(DS_ID) ON DELETE CASCADE ON UPDATE NO ACTION;