/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.ou.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.model.metadata.SbiKpiModelInst;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3



/**
 * SbiOrgUnitGrantNodes generated by hbm2java
 */

public class SbiOrgUnitGrantNodes  extends SbiHibernateModel {


    // Fields    

     private SbiOrgUnitGrantNodesId id;
     private SbiOrgUnitNodes sbiOrgUnitNodes;
     private SbiKpiModelInst sbiKpiModelInst;
     private SbiOrgUnitGrant sbiOrgUnitGrant;


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrantNodes() {
    }

    
    /** full constructor */
    public SbiOrgUnitGrantNodes(SbiOrgUnitGrantNodesId id, SbiOrgUnitNodes sbiOrgUnitNodes, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.id = id;
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
    

   
    // Property accessors

    public SbiOrgUnitGrantNodesId getId() {
        return this.id;
    }
    
    public void setId(SbiOrgUnitGrantNodesId id) {
        this.id = id;
    }

    public SbiOrgUnitNodes getSbiOrgUnitNodes() {
        return this.sbiOrgUnitNodes;
    }
    
    public void setSbiOrgUnitNodes(SbiOrgUnitNodes sbiOrgUnitNodes) {
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
    }

    public SbiKpiModelInst getSbiKpiModelInst() {
        return this.sbiKpiModelInst;
    }
    
    public void setSbiKpiModelInst(SbiKpiModelInst sbiKpiModelInst) {
        this.sbiKpiModelInst = sbiKpiModelInst;
    }

    public SbiOrgUnitGrant getSbiOrgUnitGrant() {
        return this.sbiOrgUnitGrant;
    }
    
    public void setSbiOrgUnitGrant(SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
   








}
