/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.ou.metadata;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.model.metadata.SbiKpiModelInst;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * SbiOrgUnitGrant generated by hbm2java
 */

public class SbiOrgUnitGrant  extends SbiHibernateModel {


    // Fields    

     private Integer id;
     private SbiKpiModelInst sbiKpiModelInst;
     private SbiOrgUnitHierarchies sbiOrgUnitHierarchies;
     private Date startDate;
     private Date endDate;
     private String label;
     private String name;
     private String description;
     private Boolean isAvailable;


	private Set sbiOrgUnitGrantNodeses = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrant() {
    }

	/** minimal constructor */
    public SbiOrgUnitGrant(Integer id, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
        this.id = id;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
    }
    
    /** full constructor */
    public SbiOrgUnitGrant(Integer id, Boolean isAvailable, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitHierarchies sbiOrgUnitHierarchies, Date startDate, Date endDate, String label, String name, String description, Set sbiOrgUnitGrantNodeses) {
        this.id = id;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
        this.startDate = startDate;
        this.endDate = endDate;
        this.label = label;
        this.name = name;
        this.description = description;
        this.isAvailable = isAvailable;
        this.sbiOrgUnitGrantNodeses = sbiOrgUnitGrantNodeses;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public SbiKpiModelInst getSbiKpiModelInst() {
        return this.sbiKpiModelInst;
    }
    
    public void setSbiKpiModelInst(SbiKpiModelInst sbiKpiModelInst) {
        this.sbiKpiModelInst = sbiKpiModelInst;
    }

    public SbiOrgUnitHierarchies getSbiOrgUnitHierarchies() {
        return this.sbiOrgUnitHierarchies;
    }
    
    public void setSbiOrgUnitHierarchies(SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
    }

    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSbiOrgUnitGrantNodeses() {
        return this.sbiOrgUnitGrantNodeses;
    }
    
    public void setSbiOrgUnitGrantNodeses(Set sbiOrgUnitGrantNodeses) {
        this.sbiOrgUnitGrantNodeses = sbiOrgUnitGrantNodeses;
    }
    public Boolean getIsAvailable() {
		return isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}








}
