/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.ou.metadata;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3



/**
 * SbiOrgUnitGrantNodesId generated by hbm2java
 */

public class SbiOrgUnitGrantNodesId  implements java.io.Serializable {


    // Fields    

     private Integer nodeId;
     private Integer kpiModelInstNodeId;
     private Integer grantId;


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrantNodesId() {
    }

    
    /** full constructor */
    public SbiOrgUnitGrantNodesId(Integer nodeId, Integer kpiModelInstNodeId, Integer grantId) {
        this.nodeId = nodeId;
        this.kpiModelInstNodeId = kpiModelInstNodeId;
        this.grantId = grantId;
    }
    

   
    // Property accessors

    public Integer getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    public Integer getKpiModelInstNodeId() {
        return this.kpiModelInstNodeId;
    }
    
    public void setKpiModelInstNodeId(Integer kpiModelInstNodeId) {
        this.kpiModelInstNodeId = kpiModelInstNodeId;
    }

    public Integer getGrantId() {
        return this.grantId;
    }
    
    public void setGrantId(Integer grantId) {
        this.grantId = grantId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiOrgUnitGrantNodesId) ) return false;
		 SbiOrgUnitGrantNodesId castOther = ( SbiOrgUnitGrantNodesId ) other; 
         
		 return ( (this.getNodeId()==castOther.getNodeId()) || ( this.getNodeId()!=null && castOther.getNodeId()!=null && this.getNodeId().equals(castOther.getNodeId()) ) )
 && ( (this.getKpiModelInstNodeId()==castOther.getKpiModelInstNodeId()) || ( this.getKpiModelInstNodeId()!=null && castOther.getKpiModelInstNodeId()!=null && this.getKpiModelInstNodeId().equals(castOther.getKpiModelInstNodeId()) ) )
 && ( (this.getGrantId()==castOther.getGrantId()) || ( this.getGrantId()!=null && castOther.getGrantId()!=null && this.getGrantId().equals(castOther.getGrantId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNodeId() == null ? 0 : this.getNodeId().hashCode() );
         result = 37 * result + ( getKpiModelInstNodeId() == null ? 0 : this.getKpiModelInstNodeId().hashCode() );
         result = 37 * result + ( getGrantId() == null ? 0 : this.getGrantId().hashCode() );
         return result;
   }   





}
