/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.ou.metadata;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiOrgUnitHierarchies generated by hbm2java
 */

public class SbiOrgUnitHierarchies  extends SbiHibernateModel {


    // Fields    

     private Integer id;
     private String label;
     private String name;
     private String description;
     private String target;
     private String company;
     private Set sbiOrgUnitNodeses = new HashSet(0);
     private Set sbiOrgUnitGrants = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiOrgUnitHierarchies() {
    }

	/** minimal constructor */
    public SbiOrgUnitHierarchies(Integer id, String label) {
        this.id = id;
        this.label = label;
    }
    
    /** full constructor */
    public SbiOrgUnitHierarchies(Integer id, String label, String name, String description, String target, Set sbiOrgUnitNodeses, Set sbiOrgUnitGrants) {
        this.id = id;
        this.label = label;
        this.name = name;
        this.description = description;
        this.target = target;
        this.sbiOrgUnitNodeses = sbiOrgUnitNodeses;
        this.sbiOrgUnitGrants = sbiOrgUnitGrants;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getCompany() {
        return this.company;
    }
    
    public Set getSbiOrgUnitNodeses() {
        return this.sbiOrgUnitNodeses;
    }
    
    public void setSbiOrgUnitNodeses(Set sbiOrgUnitNodeses) {
        this.sbiOrgUnitNodeses = sbiOrgUnitNodeses;
    }

    public Set getSbiOrgUnitGrants() {
        return this.sbiOrgUnitGrants;
    }
    
    public void setSbiOrgUnitGrants(Set sbiOrgUnitGrants) {
        this.sbiOrgUnitGrants = sbiOrgUnitGrants;
    }
   








}
