/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.analiticalmodel.functionalitytree.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;


/**
 * SbiFuncRole generated by hbm2java
 */
public class SbiFuncRole  extends SbiHibernateModel {

    // Fields    

     private SbiFuncRoleId id;
     private String stateCd;


    // Constructors

    /**
     * default constructor.
     */
    public SbiFuncRole() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiFuncRole(SbiFuncRoleId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiFuncRoleId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiFuncRoleId id) {
        this.id = id;
    }

    /**
     * Gets the state cd.
     * 
     * @return the state cd
     */
    public String getStateCd() {
        return this.stateCd;
    }
    
    /**
     * Sets the state cd.
     * 
     * @param stateCd the new state cd
     */
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }



}