ALTER TABLE SBI_CATALOG_FUNCTION ADD DESCRIPTION TEXT NOT NULL;

ALTER TABLE  SBI_GEO_MAPS ADD HIERARCHY_NAME VARCHAR(100);
ALTER TABLE  SBI_GEO_MAPS ADD LEVEL INTEGER;
ALTER TABLE  SBI_GEO_MAPS ADD MEMBER_NAME VARCHAR(100);
