DELETE FROM SBI_EVENTS_ROLES ;
DROP TABLE SBI_EVENTS_ROLES ;

ALTER TABLE SBI_CACHE_ITEM
ADD COLUMN PARAMETERS TEXT NULL DEFAULT NULL;

DELETE
FROM
	SBI_PRODUCT_TYPE_ENGINE
where
	ENGINE_ID in (
	select
		ENGINE_ID
	from
		SBI_ENGINES
	WHERE
		label in('knowagegisengine', 'knowageprocessengine', 'knowagesvgviewerengine')

);
DELETE FROM SBI_ENGINES WHERE label in('knowagegisengine', 'knowageprocessengine', 'knowagesvgviewerengine');

DELETE FROM SBI_GEO_MAP_FEATURES ;
DROP TABLE SBI_GEO_MAP_FEATURES ;

DELETE FROM SBI_GEO_MAPS ;
DROP TABLE SBI_GEO_MAPS ;

DELETE FROM SBI_GEO_FEATURES ;
DROP TABLE SBI_GEO_FEATURES ;

DELETE FROM SBI_COMMUNITY_USERS ;
DROP TABLE SBI_COMMUNITY_USERS ;

DELETE FROM SBI_COMMUNITY ;
DROP TABLE SBI_COMMUNITY ;

delete from SBI_DOMAINS where VALUE_CD = 'Ckan' and VALUE_NM = 'SbiCkanDataSet';

delete from SBI_ROLE_TYPE_USER_FUNC where USER_FUNCT_ID in (select USER_FUNCT_ID from SBI_USER_FUNC where name = 'CkanIntegrationFunctionality');
delete from SBI_USER_FUNC where name = 'CkanIntegrationFunctionality';