/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.mapcatalogue.metadata;

import it.eng.spagobi.commons.metadata.SbiBinContents;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.mapcatalogue.bo.GeoMap;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8


/**
 * SbiGeoMaps generated by hbm2java
 */
public class SbiGeoMaps extends SbiHibernateModel {

	// Fields    

	private int mapId;

	private String name;

	private String descr;

	private String url;
	
	private String format;
	
	private SbiBinContents binContents = null;


	// Constructors

	/**
	 * default constructor.
	 */
	public SbiGeoMaps() {
	}

	/**
	 * minimal constructor.
	 * 
	 * @param mapId the map id
	 */
	public SbiGeoMaps(int mapId) {
		this.mapId = mapId;
	}

	/**
	 * full constructor.
	 * 
	 * @param mapId the map id
	 * @param name the name
	 * @param descr the descr
	 * @param url the url
	 * @param format the format
	 * @param binContents the binary contents of svg file
	 */
	public SbiGeoMaps(int mapId, String name, String descr, String url, String format, SbiBinContents binContents ) {
		this.mapId = mapId;
		this.name = name;
		this.descr = descr;
		this.url = url;
		this.format = format;
		this.binContents = binContents;
	}

	// Property accessors
	/**
	 * Gets the map id.
	 * 
	 * @return the map id
	 */
	public int getMapId() {
		return this.mapId;
	}

	/**
	 * Sets the map id.
	 * 
	 * @param mapId the new map id
	 */
	public void setMapId(int mapId) {
		this.mapId = mapId;
	}

	/**
	 * Gets the name.
	 * 
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 * 
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the descr.
	 * 
	 * @return the descr
	 */
	public String getDescr() {
		return this.descr;
	}

	/**
	 * Sets the descr.
	 * 
	 * @param descr the new descr
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * Gets the url.
	 * 
	 * @return the url
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * Sets the url.
	 * 
	 * @param url the new url
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Gets the format.
	 * 
	 * @return the format
	 */
	public String getFormat() {
		return format;
	}

	/**
	 * Sets the format.
	 * 
	 * @param format the new format
	 */
	public void setFormat(String format) {
		this.format = format;
	}


	/**
	 * @return the binContents
	 */
	public SbiBinContents getBinContents() {
		return binContents;
	}

	/**
	 * @param binContents the binContents to set
	 */
	public void setBinContents(SbiBinContents binContents) {
		this.binContents = binContents;
	}


	/**
	 * From the Hibernate Map object at input, gives the corrispondent
	 * <code>GeoMap</code> object.
	 * 
	 * @param hibMap The Hibernate Map object
	 * 
	 * @return the corrispondent output <code>GeoMap</code>
	 */
	public GeoMap toGeoMap(){

		GeoMap map = new GeoMap();
		map.setMapId(getMapId());
		map.setName(getName());
		map.setDescr(getDescr());
		map.setFormat(getFormat());
		map.setUrl(getUrl());
		SbiBinContents tmpBin = getBinContents();
		if (tmpBin != null) { 
			map.setBinId(tmpBin.getId().intValue());
		}


		return map;
	}


}

