/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.analiticalmodel.document.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;




/**
 * SbiObjState generated by hbm2java
 */
public class SbiObjState  extends SbiHibernateModel {

    // Fields    

     private SbiObjStateId id;
     private Date endDt;
     private String note;


    // Constructors

    /**
     * default constructor.
     */
    public SbiObjState() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiObjState(SbiObjStateId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiObjStateId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiObjStateId id) {
        this.id = id;
    }

    /**
     * Gets the end dt.
     * 
     * @return the end dt
     */
    public Date getEndDt() {
        return this.endDt;
    }
    
    /**
     * Sets the end dt.
     * 
     * @param endDt the new end dt
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * Gets the note.
     * 
     * @return the note
     */
    public String getNote() {
        return this.note;
    }
    
    /**
     * Sets the note.
     * 
     * @param note the new note
     */
    public void setNote(String note) {
        this.note = note;
    }



}