/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.analiticalmodel.document.metadata;
// Generated 23-apr-2008 15.08.55 by Hibernate Tools 3.1.0 beta3



/**
 * SbiObjectsRatingId generated by hbm2java
 */

public class SbiObjectsRatingId  implements java.io.Serializable {


    // Fields    

     private Integer objId;
     private String userId;


    // Constructors

    /**
     * default constructor.
     */
    public SbiObjectsRatingId() {
    }

    
    /**
     * full constructor.
     * 
     * @param objId the obj id
     * @param userId the user id
     */
    public SbiObjectsRatingId(Integer objId, String userId) {
        this.objId = objId;
        this.userId = userId;
    }
    

   
    // Property accessors

    /**
     * Gets the obj id.
     * 
     * @return the obj id
     */
    public Integer getObjId() {
        return this.objId;
    }
    
    /**
     * Sets the obj id.
     * 
     * @param objId the new obj id
     */
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    /**
     * Gets the user id.
     * 
     * @return the user id
     */
    public String getUserId() {
        return this.userId;
    }
    
    /**
     * Sets the user id.
     * 
     * @param userId the new user id
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
   



   /* (non-Javadoc)
    * @see java.lang.Object#equals(java.lang.Object)
    */
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiObjectsRatingId) ) return false;
		 SbiObjectsRatingId castOther = ( SbiObjectsRatingId ) other; 
         
		 return ( (this.getObjId()==castOther.getObjId()) || ( this.getObjId()!=null && castOther.getObjId()!=null && this.getObjId().equals(castOther.getObjId()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getObjId() == null ? 0 : this.getObjId().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   





}
