/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.commons.metadata;

import it.eng.spagobi.events.metadata.SbiEventsLog;

/**
 * SbiEventRoleId generated by hbm2java
 */
public class SbiEventRoleId  implements java.io.Serializable {

    // Fields    

     private SbiExtRoles role;
     private SbiEventsLog event;


    // Constructors

    /**
     * default constructor.
     */
    public SbiEventRoleId() {
    }

    // Property accessors

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiEventRoleId) ) return false;
		 SbiEventRoleId castOther = ( SbiEventRoleId ) other; 
         
		 return 
		 	(this.getRole()==castOther.getRole()) || (this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()))
		 	&& 
		 	(this.getEvent()==castOther.getEvent()) || (this.getEvent()!=null && castOther.getEvent()!=null && this.getEvent().equals(castOther.getEvent()));
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   public int hashCode() {
         int result = 17;
         result = 37 * result + this.getRole().hashCode();
         result = 37 * result + this.getEvent().hashCode();
         return result;
   }   


	/**
	 * Gets the event.
	 * 
	 * @return the event
	 */
	public SbiEventsLog getEvent() {
		return event;
	}
	
	/**
	 * Sets the event.
	 * 
	 * @param event the new event
	 */
	public void setEvent(SbiEventsLog event) {
		this.event = event;
	}
	
	/**
	 * Gets the role.
	 * 
	 * @return the role
	 */
	public SbiExtRoles getRole() {
		return role;
	}
	
	/**
	 * Sets the role.
	 * 
	 * @param role the new role
	 */
	public void setRole(SbiExtRoles role) {
		this.role = role;
	}
}