-- 2021/07/26
ALTER TABLE SBI_ALERT_ACTION DROP COLUMN TEMPLATE CASCADE;
ALTER TABLE SBI_ALERT_LISTENER DROP COLUMN TEMPLATE CASCADE;
ALTER TABLE SBI_DATA_SOURCE ADD USE_FOR_DATAPREP NUMBER(38,0) DEFAULT 0;
