--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD RESOURCE_CODE VARCHAR(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
CREATE UNIQUE INDEX UNIQUE_RES_CODE ON SBI_RESOURCES (RESOURCE_CODE);
