-- 22/12/2020 Marco Balestri
-- CATALOG FUNCTION TABLES UPDATE

-- START

-- CLEAN old tables
DELETE FROM SBI_CATALOG_FUNCTION;
DELETE FROM SBI_FUNCTION_INPUT_VARIABLE;

-- DROP old tables
DROP TABLE IF EXISTS SBI_FUNCTION_OUTPUT, SBI_FUNCTION_INPUT_DATASET, SBI_FUNCTION_INPUT_FILE;

-- ------------------------- TABLE sbi_catalog_function -------------------------
ALTER TABLE SBI_CATALOG_FUNCTION
ADD (BENCHMARKS text(4000), FAMILY text(30), ONLINE_SCRIPT text(4000), OFFLINE_SCRIPT_TRAIN text(4000), OFFLINE_SCRIPT_USE text(4000)),
DROP SCRIPT, DROP URL, DROP REMOTE;

-- ----------------------- TABLE sbi_function_input_column -----------------------
CREATE TABLE IF NOT EXISTS SBI_FUNCTION_INPUT_COLUMN LIKE SBI_FUNCTION_INPUT_VARIABLE;
  
ALTER TABLE SBI_FUNCTION_INPUT_COLUMN
CHANGE VAR_NAME COL_NAME varchar(100),
CHANGE VAR_VALUE COL_TYPE varchar(100);

-- ---------------------- TABLE sbi_function_input_variable ---------------------
ALTER TABLE SBI_FUNCTION_INPUT_VARIABLE
ADD (VAR_TYPE varchar(100));

-- ---------------------- TABLE sbi_function_output_column -----------------------
CREATE TABLE IF NOT EXISTS SBI_FUNCTION_OUTPUT_COLUMN LIKE SBI_FUNCTION_INPUT_COLUMN;

ALTER TABLE SBI_FUNCTION_OUTPUT_COLUMN
ADD (COL_FIELD_TYPE varchar(100));

-- --------------------------- TABLE sbi_obj_function ---------------------------
CREATE TABLE IF NOT EXISTS SBI_OBJ_FUNCTION LIKE SBI_OBJ_DATA_SET;

ALTER TABLE SBI_OBJ_FUNCTION
DROP IS_DETAIL,
CHANGE BIOBJ_DS_ID BIOBJ_FUNCTION_ID int,
CHANGE DS_ID FUNCTION_ID int,
ADD FOREIGN KEY (BIOBJ_ID) REFERENCES SBI_OBJECTS(BIOBJ_ID),
ADD FOREIGN KEY (FUNCTION_ID) REFERENCES SBI_CATALOG_FUNCTION(FUNCTION_ID);

-- END