-- 2021/07/26
ALTER TABLE SBI_ALERT_ACTION DROP COLUMN TEMPLATE CASCADE;
ALTER TABLE SBI_ALERT_LISTENER DROP COLUMN TEMPLATE CASCADE;

-- 2022/02/08
CREATE TABLE SBI_ORGANIZATION_THEME (
	ID INT4 NOT NULL,
	ORGANIZATION_ID INT4 NOT NULL,
	THEME_NAME VARCHAR NOT NULL,
	CONFIG TEXT NULL,
	ACTIVE BOOL NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL::CHARACTER VARYING,
	USER_DE VARCHAR(100) NULL DEFAULT NULL::CHARACTER VARYING,
	TIME_IN TIMESTAMP NULL,
	TIME_UP TIMESTAMP NULL,
	TIME_DE TIMESTAMP NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL::CHARACTER VARYING,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL::CHARACTER VARYING,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL::CHARACTER VARYING,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL::CHARACTER VARYING,
	ORGANIZATION VARCHAR(20) NOT NULL DEFAULT NULL::CHARACTER VARYING,
	CONSTRAINT "PK_SBI_ORGANIZATION_THEME" PRIMARY KEY (ID),
	CONSTRAINT "U_SBI_ORGANIZATION_THEME" UNIQUE (THEME_NAME, ORGANIZATION_ID),
	CONSTRAINT FK_ORGANIZATION_1 FOREIGN KEY (ORGANIZATION_ID) REFERENCES SBI_ORGANIZATIONS(ID)
);
INSERT INTO HIBERNATE_SEQUENCES (SEQUENCE_NAME, NEXT_VAL) VALUES('SBI_ORGANIZATION_THEME', 1);