/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.36 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.model.metadata.SbiResources;
import it.eng.spagobi.kpi.ou.metadata.SbiOrgUnit;
import it.eng.spagobi.kpi.ou.metadata.SbiOrgUnitHierarchies;

import java.util.Date;


/**
 * SbiKpiValue generated by hbm2java
 */

public class _SbiKpiValue  extends SbiHibernateModel {


    // Fields    
	
     private Integer idKpiInstanceValue;
     private SbiKpiInstance sbiKpiInstance;
     private SbiResources sbiResources;
     private String value;
     private Date beginDt;
     private Date endDt;
     private String description;
     private String xmlData; 
     private SbiOrgUnit sbiOrgUnit;
     private SbiOrgUnitHierarchies sbiOrgUnitHierarchies;
     private String company;

    // Constructors

   

	/** default constructor */
    public _SbiKpiValue() {
    }

	/** minimal constructor */
    public _SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
    }
	/** minimal constructor with ou*/
    public _SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources,SbiOrgUnit sbiOrgUnit, SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
        this.sbiOrgUnit = sbiOrgUnit;
        this.sbiOrgUnit = sbiOrgUnit;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
    } 
    /** full constructor */
    public _SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources, String value, Date beginDt, Date endDt, String description, String xmlData) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
        this.value = value;
        this.beginDt = beginDt;
        this.endDt = endDt;
        this.description = description;
        this.xmlData = xmlData;
    }
    
    /** full constructor */
    public _SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources, String value, Date beginDt, Date endDt, String description, String xmlData, 
    					SbiOrgUnit sbiOrgUnit,
    					SbiOrgUnitHierarchies sbiOrgUnitHierarchies,
    					String company) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
        this.value = value;
        this.beginDt = beginDt;
        this.endDt = endDt;
        this.description = description;
        this.xmlData = xmlData;
        this.sbiOrgUnit = sbiOrgUnit;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
        this.company = company;
    }
   
    // Property accessors

    public Integer getIdKpiInstanceValue() {
        return this.idKpiInstanceValue;
    }
    
    public void setIdKpiInstanceValue(Integer idKpiInstanceValue) {
        this.idKpiInstanceValue = idKpiInstanceValue;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public SbiResources getSbiResources() {
        return this.sbiResources;
    }
    
    public void setSbiResources(SbiResources sbiResources) {
        this.sbiResources = sbiResources;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Date getBeginDt() {
        return this.beginDt;
    }
    
    public void setBeginDt(Date beginDt) {
        this.beginDt = beginDt;
    }

    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }
   
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getXmlData() {
		return xmlData;
	}

	public void setXmlData(String xmlData) {
		this.xmlData = xmlData;
	}

	public SbiOrgUnit getSbiOrgUnit() {
		return sbiOrgUnit;
	}

	public void setSbiOrgUnit(SbiOrgUnit sbiOrgUnit) {
		this.sbiOrgUnit = sbiOrgUnit;
	}

	public SbiOrgUnitHierarchies getSbiOrgUnitHierarchies() {
		return sbiOrgUnitHierarchies;
	}

	public void setSbiOrgUnitHierarchies(SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
		this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}
