/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiKpiRole generated by hbm2java
 */

public class SbiKpiDocument  extends SbiHibernateModel{

	// Fields    
	
    private Integer idKpiDoc;
    private SbiKpi sbiKpi;
    private SbiObjects sbiObjects;


   // Constructors

   /** default constructor */
   public SbiKpiDocument() {
	   this.idKpiDoc = -1;
   }

   
   /** full constructor */
   public SbiKpiDocument(Integer idKpiDoc, SbiKpi sbiKpi, SbiObjects sbiObjects) {
       this.idKpiDoc = idKpiDoc;
       this.sbiKpi = sbiKpi;
       this.sbiObjects = sbiObjects;
   }

  
   // Property accessors

   // Property accessors

   public Integer getIdKpiDoc() {
       return this.idKpiDoc;
   }
   
   public void setIdKpiDoc(Integer idKpiDoc) {
       this.idKpiDoc = idKpiDoc;
   }

   public SbiObjects getSbiObjects() {
       return this.sbiObjects;
   }
   
   public void setSbiObjects(SbiObjects sbiObjects) {
       this.sbiObjects = sbiObjects;
   }

   public SbiKpi getSbiKpi() {
       return this.sbiKpi;
   }
   
   public void setSbiKpi(SbiKpi sbiKpi) {
       this.sbiKpi = sbiKpi;
   }

}
