/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.35 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiMeasureUnit generated by hbm2java
 */

public class SbiMeasureUnit  extends SbiHibernateModel {


    // Fields    

     private Integer idMeasureUnit;
     private SbiDomains scaleType;
     private String name;
     private String scaleCd;
     private String scaleNm;
     private Set sbiKpis = new HashSet(0);
     private Set sbiKpiInstanceHistories = new HashSet(0);
     private Set sbiKpiInstances = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiMeasureUnit() {
    }

	/** minimal constructor */
    public SbiMeasureUnit(Integer idMeasureUnit, SbiDomains sbiDomains) {
        this.idMeasureUnit = idMeasureUnit;
        this.scaleType = sbiDomains;
    }
    
    /** full constructor */
    public SbiMeasureUnit(Integer idMeasureUnit, SbiDomains sbiDomains, String name, String scaleCd, String scaleNm, Set sbiKpis, Set sbiKpiInstanceHistories, Set sbiKpiInstances) {
        this.idMeasureUnit = idMeasureUnit;
        this.scaleType = sbiDomains;
        this.name = name;
        this.scaleCd = scaleCd;
        this.scaleNm = scaleNm;
        this.sbiKpis = sbiKpis;
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
        this.sbiKpiInstances = sbiKpiInstances;
    }
    

   
    // Property accessors

    public Integer getIdMeasureUnit() {
        return this.idMeasureUnit;
    }
    
    public void setIdMeasureUnit(Integer idMeasureUnit) {
        this.idMeasureUnit = idMeasureUnit;
    }

    public SbiDomains getScaleType() {
        return this.scaleType;
    }
    
    public void setScaleType(SbiDomains sbiDomains) {
        this.scaleType = sbiDomains;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getScaleCd() {
        return this.scaleCd;
    }
    
    public void setScaleCd(String scaleCd) {
        this.scaleCd = scaleCd;
    }

    public String getScaleNm() {
        return this.scaleNm;
    }
    
    public void setScaleNm(String scaleNm) {
        this.scaleNm = scaleNm;
    }

    public Set getSbiKpis() {
        return this.sbiKpis;
    }
    
    public void setSbiKpis(Set sbiKpis) {
        this.sbiKpis = sbiKpis;
    }

    public Set getSbiKpiInstanceHistories() {
        return this.sbiKpiInstanceHistories;
    }
    
    public void setSbiKpiInstanceHistories(Set sbiKpiInstanceHistories) {
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }
   








}
