CREATE TABLE SBI_HOMEPAGE (
	ID INTEGER NOT NULL,
	TYPE VARCHAR2(20) NOT NULL,
	DOCUMENT_ID INTEGER DEFAULT NULL,
	IMAGE_URL VARCHAR2(4000) DEFAULT NULL,
	STATIC_PAGE VARCHAR2(255) DEFAULT NULL,
	HTML CLOB,
	CSS CLOB,
	MENU_PLACEHOLDERS CLOB,
	IS_DEFAULT SMALLINT DEFAULT 0 NOT NULL,
	USER_IN VARCHAR2(100) NOT NULL,
	USER_UP VARCHAR2(100) DEFAULT NULL,
	USER_DE VARCHAR2(100) DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL,
	TIME_UP TIMESTAMP DEFAULT NULL,
	TIME_DE TIMESTAMP DEFAULT NULL,
	SBI_VERSION_IN VARCHAR2(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR2(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR2(10) DEFAULT NULL,
	META_VERSION VARCHAR2(100) DEFAULT NULL,
	ORGANIZATION VARCHAR2(20) DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_SBI_HOMEPAGE_1 FOREIGN KEY (DOCUMENT_ID) REFERENCES SBI_OBJECTS (BIOBJ_ID)
);

CREATE TABLE SBI_HOMEPAGE_ROLE (
	HOMEPAGE_ID INTEGER NOT NULL,
	EXT_ROLE_ID INTEGER NOT NULL,
	PRIMARY KEY (HOMEPAGE_ID,EXT_ROLE_ID),
	CONSTRAINT FK_SBI_HOMEPAGE_ROLE_1 FOREIGN KEY (HOMEPAGE_ID) REFERENCES SBI_HOMEPAGE (ID) ON DELETE CASCADE,
	CONSTRAINT FK_SBI_HOMEPAGE_ROLE_2 FOREIGN KEY (EXT_ROLE_ID) REFERENCES SBI_EXT_ROLES (EXT_ROLE_ID) ON DELETE CASCADE
);

INSERT INTO hibernate_sequences(next_val, sequence_name)
VALUES (NVL((SELECT MAX(ID)+1 FROM SBI_HOMEPAGE), 1), 'SBI_HOMEPAGE');

COMMIT;
