INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('groovy','Groovy','SCRIPT_TYPE','Script Type','Script Type');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('rhino-nonjdk','Javascript','SCRIPT_TYPE','Script Type','Script Type');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('ejs','Embedded Javascript','SCRIPT_TYPE','Script Type','Script Type');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('File','SbiFileDataSet','DATA_SET_TYPE','Data Set Type','SbiFileDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('Query','SbiQueryDataSet','DATA_SET_TYPE','Data Set Type','SbiQueryDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('Java Class','SbiJClassDataSet','DATA_SET_TYPE','Data Set Type','SbiJClassDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('Web Service','SbiWSDataSet','DATA_SET_TYPE','Data Set Type','SbiWSDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('Script','SbiScriptDataSet','DATA_SET_TYPE','Data Set Type','SbiScriptDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('Qbe','SbiQbeDataSet','DATA_SET_TYPE','Data Set Type','SbiQbeDataSet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('WORKSHEET','sbidomains.nm.worksheet','BIOBJ_TYPE','BI Object types','sbidomains.ds.worksheet');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('DEVELOPMENT', 'sbidomains.permissiononfolder.nm.dev','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.dev');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('TEST', 'sbidomains.permissiononfolder.nm.test','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.test');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('EXECUTION', 'sbidomains.permissiononfolder.nm.execute','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.execute');
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('CREATION', 'sbidomains.permissiononfolder.nm.create','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.create');
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'DEVELOPMENT' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'DEVELOPMENT' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'DEV' AND DOMAIN_CD = 'STATE');
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'TEST' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'TEST' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'TEST' AND DOMAIN_CD = 'STATE');
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'EXECUTION' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'EXECUTION' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'REL' AND DOMAIN_CD = 'STATE');

INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('DomainManagement', 'DomainManagement');
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='DomainManagement'));
INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('ConfigManagement', 'ConfigManagement');
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='ConfigManagement'));
INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('UserSaveDocumentFunctionality', 'UserSaveDocumentFunctionality');
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'USER'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'DEV_ROLE'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'TEST_ROLE'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'));
INSERT INTO SBI_ENGINES (NAME, ENCRYPT, LABEL,MAIN_URL, DRIVER_NM, ENGINE_TYPE,BIOBJ_TYPE,USE_DATASOURCE,USE_DATASET) VALUES 
 ('Worksheet Engine', 0, 'WorksheetEngine','/SpagoBIQbeEngine/servlet/AdapterHTTP','it.eng.spagobi.engines.drivers.worksheet.WorksheetDriver',(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ENGINE_TYPE' AND VALUE_CD = 'EXT'),(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'BIOBJ_TYPE' AND VALUE_CD = 'WORKSHEET'),true, false);

CREATE TABLE SBI_DATA_SET_HISTORY (
	DS_H_ID 	   INTEGER NOT NULL,
	DS_ID 		   INTEGER NOT NULL,
	ACTIVE		   BOOLEAN NOT NULL,
	VERSION_NUM	   INTEGER NOT NULL,
	OBJECT_TYPE    VARCHAR(50),
	DS_METADATA    VARCHAR(2000),
	PARAMS         VARCHAR(1000),
	CATEGORY_ID    INTEGER,
    FILE_NAME	   VARCHAR(300),
    QUERY   	   TEXT,
    DATA_SOURCE_ID INTEGER,
    ADRESS   	   VARCHAR(250),
    OPERATION      VARCHAR(50),
    JCLASS_NAME    VARCHAR(100),
    LANGUAGE_SCRIPT VARCHAR(50),
	SCRIPT   	   TEXT,
	JSON_QUERY     TEXT,
	DATAMARTS	   VARCHAR(400),
    TRANSFORMER_ID INTEGER,
    PIVOT_COLUMN   VARCHAR(50),
	PIVOT_ROW      VARCHAR(50),
	PIVOT_VALUE    VARCHAR(50),
	NUM_ROWS	   BOOLEAN DEFAULT FALSE,	
	USER_IN              VARCHAR(100) NOT NULL,
	TIME_IN              TIMESTAMP NOT NULL,
	META_VERSION         VARCHAR(100),
	SBI_VERSION_IN       VARCHAR(10),
    PRIMARY KEY (DS_H_ID)
)TYPE=INNODB;

ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_T  FOREIGN KEY ( TRANSFORMER_ID ) REFERENCES SBI_DOMAINS ( VALUE_ID ) ON DELETE CASCADE;
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_CAT  FOREIGN KEY (CATEGORY_ID) REFERENCES SBI_DOMAINS (VALUE_ID) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_DS  FOREIGN KEY ( DATA_SOURCE_ID ) REFERENCES SBI_DATA_SOURCE ( DS_ID ) ON DELETE CASCADE;
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_DS2  FOREIGN KEY (DS_ID) REFERENCES SBI_DATA_SET (DS_ID) ON DELETE CASCADE ON UPDATE RESTRICT;

INSERT INTO SBI_DATA_SET_HISTORY
(DS_H_ID, DS_ID,ACTIVE,VERSION_NUM,FILE_NAME,QUERY,JCLASS_NAME,SCRIPT,PARAMS,DS_METADATA
	,DATA_SOURCE_ID,OBJECT_TYPE,OPERATION,TRANSFORMER_ID,PIVOT_COLUMN,PIVOT_ROW
	,PIVOT_VALUE,NUM_ROWS,LANGUAGE_SCRIPT,USER_IN, TIME_IN)
SELECT DS_ID, DS_ID,true ACTIVE,1 VERSION_NUM,FILE_NAME,QUERY,JCLASS_NAME,SCRIPT,PARAMS,DS_METADATA,DATA_SOURCE_ID
,OBJECT_TYPE,OPERATION,TRANSFORMER_ID,PIVOT_COLUMN,PIVOT_ROW,PIVOT_VALUE,NUM_ROWS,LANGUAGE_SCRIPT
,'biadmin' USER_IN, NOW() TIME_IN
FROM SBI_DATA_SET;

commit;


ALTER TABLE SBI_DATA_SET DROP FOREIGN KEY FK_SBI_DATA_SET_1;

ALTER TABLE SBI_DATA_SET DROP COLUMN EXECUTOR_CLASS;
ALTER TABLE SBI_DATA_SET DROP COLUMN FILE_NAME;
ALTER TABLE SBI_DATA_SET DROP COLUMN QUERY;
ALTER TABLE SBI_DATA_SET DROP COLUMN JCLASS_NAME;
ALTER TABLE SBI_DATA_SET DROP COLUMN SCRIPT;
ALTER TABLE SBI_DATA_SET DROP COLUMN PARAMS;
ALTER TABLE SBI_DATA_SET DROP COLUMN DS_METADATA;
ALTER TABLE SBI_DATA_SET DROP COLUMN DATA_SOURCE_ID;
ALTER TABLE SBI_DATA_SET DROP COLUMN OBJECT_TYPE;
ALTER TABLE SBI_DATA_SET DROP COLUMN OPERATION;
ALTER TABLE SBI_DATA_SET DROP COLUMN TRANSFORMER_ID;
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_COLUMN;
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_ROW;
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_VALUE;
ALTER TABLE SBI_DATA_SET DROP COLUMN NUM_ROWS;
ALTER TABLE SBI_DATA_SET DROP COLUMN LANGUAGE_SCRIPT;
ALTER TABLE SBI_DATA_SET DROP COLUMN ADRESS;


ALTER TABLE SBI_DATA_SET ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DATA_SET ADD COLUMN USER_UP VARCHAR(100); 
ALTER TABLE SBI_DATA_SET ADD COLUMN USER_DE VARCHAR(100);
ALTER TABLE SBI_DATA_SET ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DATA_SET ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DATA_SET ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DATA_SET ADD COLUMN SBI_VERSION_IN VARCHAR(10); 
ALTER TABLE SBI_DATA_SET ADD COLUMN SBI_VERSION_UP VARCHAR(10); 
ALTER TABLE SBI_DATA_SET ADD COLUMN SBI_VERSION_DE VARCHAR(10); 
ALTER TABLE SBI_DATA_SET ADD COLUMN META_VERSION VARCHAR(100); 
ALTER TABLE SBI_DATA_SET ADD COLUMN ORGANIZATION VARCHAR(20); 

ALTER TABLE SBI_FUNCTIONS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN USER_UP VARCHAR(100);
ALTER TABLE SBI_FUNCTIONS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_FUNCTIONS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_STATE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_PAR ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJECTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECTS ADD COLUMN TIME_UP TIMESTAMP  NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_VIEWPOINTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DATA_SOURCE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SUBOBJECTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SNAPSHOTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_FUNC_ROLE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE_DET ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE_CK ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_PARUSE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARUSE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SUBREPORTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARAMETERS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_PARAMETERS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARAMETERS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARAMETERS ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_PARAMETERS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN TIME_DE  TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_FUNC ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_CHECKS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_CHECKS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_CHECKS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_CHECKS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_CHECKS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_LOV ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_LOV ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_LOV ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_LOV ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_LOV ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOMAINS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DOMAINS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOMAINS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOMAINS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOMAINS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EXT_ROLES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER_FUNC ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_USER_FUNC ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER_FUNC ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER_FUNC ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER_FUNC ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ENGINES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ENGINES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ENGINES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ENGINES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ENGINES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EVENTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_EVENTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_EVENTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EVENTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EVENTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EVENTS_LOG ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_REMEMBER_ME ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM_EVENT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ALARM ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_ROLE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_REL ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_REL ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_REL ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_REL ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_REL ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_ERROR ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_VALUE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL_KPI ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GOAL ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GOAL ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_RESOURCES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_RESOURCES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_RESOURCES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_RESOURCES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_RESOURCES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_THRESHOLD ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_THRESHOLD ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_THRESHOLD ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_FEATURES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_MAPS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_AUDIT ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_AUDIT ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_AUDIT ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_AUDIT ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_AUDIT ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ATTRIBUTE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_USER ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DIST_LIST ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_METADATA ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_UDP_VALUE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_UDP ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_UDP ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_UDP ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_UDP ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_UDP ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MENU_ROLE ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MENU ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_MENU ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_MENU ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MENU ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_MENU ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD COLUMN ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN USER_IN VARCHAR(100) NOT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN TIME_IN TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN TIME_UP TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN TIME_DE TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD COLUMN ORGANIZATION VARCHAR(20) ;

UPDATE SBI_FUNCTIONS SET TIME_IN =NULL;
UPDATE SBI_OBJ_STATE SET TIME_IN =NULL;
UPDATE SBI_OBJ_PAR SET TIME_IN =NULL;
UPDATE SBI_OBJECTS SET TIME_IN =NULL;
UPDATE SBI_VIEWPOINTS SET TIME_IN =NULL;
UPDATE SBI_DATA_SOURCE SET TIME_IN =NULL;
UPDATE SBI_DATA_SET SET TIME_IN =NULL;
UPDATE SBI_OBJECT_TEMPLATES SET TIME_IN =NULL;
UPDATE SBI_OBJECT_NOTES SET TIME_IN =NULL;
UPDATE SBI_SUBOBJECTS SET TIME_IN =NULL;
UPDATE SBI_SNAPSHOTS SET TIME_IN =NULL;
UPDATE SBI_FUNC_ROLE SET TIME_IN =NULL;
UPDATE SBI_PARUSE_DET SET TIME_IN =NULL;
UPDATE SBI_PARUSE_CK SET TIME_IN =NULL;
UPDATE SBI_PARUSE SET TIME_IN =NULL;
UPDATE SBI_SUBREPORTS SET TIME_IN =NULL;
UPDATE SBI_OBJECTS_RATING SET TIME_IN =NULL;
UPDATE SBI_PARAMETERS SET TIME_IN =NULL;
UPDATE SBI_OBJ_PARUSE SET TIME_IN =NULL;
UPDATE SBI_OBJ_FUNC SET TIME_IN =NULL;
UPDATE SBI_CHECKS SET TIME_IN =NULL;
UPDATE SBI_LOV SET TIME_IN =NULL;
UPDATE SBI_BINARY_CONTENTS SET TIME_IN =NULL;
UPDATE SBI_DOMAINS SET TIME_IN =NULL;
UPDATE SBI_EXT_ROLES SET TIME_IN =NULL;
UPDATE SBI_USER_FUNC SET TIME_IN =NULL;
UPDATE SBI_ENGINES SET TIME_IN =NULL;
UPDATE SBI_EVENTS SET TIME_IN =NULL;
UPDATE SBI_EVENTS_LOG SET TIME_IN =NULL;
UPDATE SBI_REMEMBER_ME SET TIME_IN =NULL;
UPDATE SBI_ALARM_EVENT SET TIME_IN =NULL;
UPDATE SBI_ALARM SET TIME_IN =NULL;
UPDATE SBI_ALARM_CONTACT SET TIME_IN =NULL;
UPDATE SBI_KPI_ROLE SET TIME_IN =NULL;
UPDATE SBI_KPI_REL SET TIME_IN =NULL;
UPDATE SBI_KPI_PERIODICITY SET TIME_IN =NULL;
UPDATE SBI_KPI_INST_PERIOD SET TIME_IN =NULL;
UPDATE SBI_KPI_INSTANCE_HISTORY SET TIME_IN =NULL;
UPDATE SBI_KPI_INSTANCE SET TIME_IN =NULL;
UPDATE SBI_KPI_ERROR SET TIME_IN =NULL;
UPDATE SBI_KPI_DOCUMENTS SET TIME_IN =NULL;
UPDATE SBI_KPI SET TIME_IN =NULL;
UPDATE SBI_KPI_VALUE SET TIME_IN =NULL;
UPDATE SBI_MEASURE_UNIT SET TIME_IN =NULL;
UPDATE SBI_GOAL_KPI SET TIME_IN =NULL;
UPDATE SBI_GOAL_HIERARCHY SET TIME_IN =NULL;
UPDATE SBI_GOAL SET TIME_IN =NULL;
UPDATE SBI_RESOURCES SET TIME_IN =NULL;
UPDATE SBI_KPI_MODEL_RESOURCES SET TIME_IN =NULL;
UPDATE SBI_KPI_MODEL_INST SET TIME_IN =NULL;
UPDATE SBI_KPI_MODEL SET TIME_IN =NULL;
UPDATE SBI_ORG_UNIT SET TIME_IN =NULL;
UPDATE SBI_ORG_UNIT_GRANT SET TIME_IN =NULL;
UPDATE SBI_ORG_UNIT_GRANT_NODES SET TIME_IN =NULL;
UPDATE SBI_ORG_UNIT_HIERARCHIES SET TIME_IN =NULL;
UPDATE SBI_ORG_UNIT_NODES SET TIME_IN =NULL;
UPDATE SBI_THRESHOLD SET TIME_IN =NULL;
UPDATE SBI_THRESHOLD_VALUE SET TIME_IN =NULL;
UPDATE SBI_GEO_FEATURES SET TIME_IN =NULL;
UPDATE SBI_GEO_MAP_FEATURES SET TIME_IN =NULL;
UPDATE SBI_GEO_MAPS SET TIME_IN =NULL;
UPDATE SBI_AUDIT SET TIME_IN =NULL;
UPDATE SBI_ATTRIBUTE SET TIME_IN =NULL;
UPDATE SBI_EXT_USER_ROLES SET TIME_IN =NULL;
UPDATE SBI_USER SET TIME_IN =NULL;
UPDATE SBI_USER_ATTRIBUTES SET TIME_IN =NULL;
UPDATE SBI_DIST_LIST_USER SET TIME_IN =NULL;
UPDATE SBI_DIST_LIST_OBJECTS SET TIME_IN =NULL;
UPDATE SBI_DIST_LIST SET TIME_IN =NULL;
UPDATE SBI_OBJ_METACONTENTS SET TIME_IN =NULL;
UPDATE SBI_OBJ_METADATA SET TIME_IN =NULL;
UPDATE SBI_UDP_VALUE SET TIME_IN =NULL;
UPDATE SBI_UDP SET TIME_IN =NULL;
UPDATE SBI_MENU_ROLE SET TIME_IN =NULL;
UPDATE SBI_MENU SET TIME_IN =NULL;
UPDATE SBI_DOSSIER_PRES SET TIME_IN =NULL;
UPDATE SBI_DOSSIER_TEMP SET TIME_IN =NULL;
UPDATE SBI_DOSSIER_BIN_TEMP SET TIME_IN =NULL;

DROP TABLE SBI_CONFIG;

CREATE TABLE SBI_CONFIG (
	   ID 					INTEGER  NOT NULL ,
	   LABEL				VARCHAR(100) NOT NULL,
	   NAME					VARCHAR(100) NULL,
	   DESCRIPTION 			VARCHAR(500) NULL,
	   IS_ACTIVE 			BOOLEAN DEFAULT TRUE,
	   VALUE_CHECK 			VARCHAR(1000) NULL,
	   VALUE_TYPE_ID 		INTEGER NULL, 
       USER_IN              VARCHAR(100) NOT NULL,
       USER_UP              VARCHAR(100),
       USER_DE              VARCHAR(100),
       TIME_IN              TIMESTAMP NOT NULL,
       TIME_UP              TIMESTAMP NULL DEFAULT NULL,
       TIME_DE              TIMESTAMP NULL DEFAULT NULL,
       SBI_VERSION_IN       VARCHAR(10),
       SBI_VERSION_UP       VARCHAR(10),
       SBI_VERSION_DE       VARCHAR(10),
       META_VERSION         VARCHAR(100),
       ORGANIZATION         VARCHAR(20), 
       CATEGORY             VARCHAR(50),
       UNIQUE XAK1SBI_CONFIG (LABEL),
 	PRIMARY KEY (ID)
) ENGINE=InnoDB;


CREATE TABLE hibernate_sequences (
  SEQUENCE_NAME VARCHAR(200) NOT NULL,
  NEXT_VAL INT(11) NOT NULL,
  PRIMARY KEY (SEQUENCE_NAME)
);

INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(BIOBJ_ID)+1 FROM SBI_OBJECTS),1),'SBI_OBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(OBJ_NOTE_ID)+1 FROM SBI_OBJECT_NOTES),1) ,'SBI_OBJECT_NOTES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(OBJ_PAR_ID)+1 FROM SBI_OBJ_PAR),1) ,'SBI_OBJ_PAR');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(OBJ_TEMP_ID)+1 FROM SBI_OBJECT_TEMPLATES),1) ,'SBI_OBJECT_TEMPLATES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(SNAP_ID)+1 FROM SBI_SNAPSHOTS),1) ,'SBI_SNAPSHOTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(SUBOBJ_ID)+1 FROM SBI_SUBOBJECTS),1) ,'SBI_SUBOBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(VP_ID)+1 FROM SBI_VIEWPOINTS),1) ,'SBI_VIEWPOINTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(FUNCT_ID)+1 FROM SBI_FUNCTIONS),1) ,'SBI_FUNCTIONS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(PAR_ID)+1 FROM SBI_PARAMETERS),1) ,'SBI_PARAMETERS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(USE_ID)+1 FROM SBI_PARUSE),1) ,'SBI_PARUSE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(CHECK_ID)+1 FROM SBI_CHECKS),1) ,'SBI_CHECKS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(LOV_ID)+1 FROM SBI_LOV),1) ,'SBI_LOV');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_CONFIG),1) ,'SBI_CONFIG');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(BIN_ID)+1 FROM SBI_BINARY_CONTENTS),1) ,'SBI_BINARY_CONTENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(VALUE_ID)+1 FROM SBI_DOMAINS),1) ,'SBI_DOMAINS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(EXT_ROLE_ID)+1 FROM SBI_EXT_ROLES),1) ,'SBI_EXT_ROLES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(USER_FUNCT_ID)+1 FROM SBI_USER_FUNC),1) ,'SBI_USER_FUNC');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ENGINE_ID)+1 FROM SBI_ENGINES),1) ,'SBI_ENGINES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(BIN_ID)+1 FROM SBI_DOSSIER_BIN_TEMP),1) ,'SBI_DOSSIER_BIN_TEMP');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(PART_ID)+1 FROM SBI_DOSSIER_TEMP),1) ,'SBI_DOSSIER_TEMP');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(PRESENTATION_ID)+1 FROM SBI_DOSSIER_PRES),1) ,'SBI_DOSSIER_PRES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_EVENTS),1) ,'SBI_EVENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_EVENTS_LOG),1) ,'SBI_EVENTS_LOG');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_REMEMBER_ME),1) ,'SBI_REMEMBER_ME');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ALARM_ID)+1 FROM SBI_ALARM),1) ,'SBI_ALARM');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ALARM_CONTACT_ID)+1 FROM SBI_ALARM_CONTACT),1) ,'SBI_ALARM_CONTACT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ALARM_EVENT_ID)+1 FROM SBI_ALARM_EVENT),1) ,'SBI_ALARM_EVENT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_ID)+1 FROM SBI_KPI),1) ,'SBI_KPI');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_DOC)+1 FROM SBI_KPI_DOCUMENTS),1),'SBI_KPI_DOCUMENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_ERROR_ID)+1 FROM SBI_KPI_ERROR),1) ,'SBI_KPI_ERROR');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_INSTANCE)+1 FROM SBI_KPI_INSTANCE),1) ,'SBI_KPI_INSTANCE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_INSTANCE_HISTORY)+1 FROM SBI_KPI_INSTANCE_HISTORY) ,1),'SBI_KPI_INSTANCE_HISTORY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_INST_PERIOD_ID)+1 FROM SBI_KPI_INST_PERIOD),1) ,'SBI_KPI_INST_PERIOD');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_PERIODICITY)+1 FROM SBI_KPI_PERIODICITY),1) ,'SBI_KPI_PERIODICITY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_ROLE)+1 FROM SBI_KPI_ROLE) ,1),'SBI_KPI_ROLE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_KPI_INSTANCE_VALUE)+1 FROM SBI_KPI_VALUE),1) ,'SBI_KPI_VALUE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_MEASURE_UNIT)+1 FROM SBI_MEASURE_UNIT),1) ,'SBI_MEASURE_UNIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(GOAL_ID)+1 FROM SBI_GOAL),1) ,'SBI_GOAL');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(GOAL_HIERARCHY_ID)+1 FROM SBI_GOAL_HIERARCHY),1) ,'SBI_GOAL_HIERARCHY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(GOAL_KPI_ID)+1 FROM SBI_GOAL_KPI),1) ,'SBI_GOAL_KPI');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_MODEL_ID)+1 FROM SBI_KPI_MODEL) ,1),'SBI_KPI_MODEL');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_MODEL_INST)+1 FROM SBI_KPI_MODEL_INST),1) ,'SBI_KPI_MODEL_INST');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(KPI_MODEL_RESOURCES_ID)+1 FROM SBI_KPI_MODEL_RESOURCES),1) ,'SBI_KPI_MODEL_RESOURCES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(RESOURCE_ID)+1 FROM SBI_RESOURCES),1) ,'SBI_RESOURCES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT),1) ,'SBI_ORG_UNIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT_GRANT),1) ,'SBI_ORG_UNIT_GRANT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT_HIERARCHIES),1) ,'SBI_ORG_UNIT_HIERARCHIES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(NODE_ID)+1 FROM SBI_ORG_UNIT_NODES),1) ,'SBI_ORG_UNIT_NODES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(THRESHOLD_ID)+1 FROM SBI_THRESHOLD),1) ,'SBI_THRESHOLD');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID_THRESHOLD_VALUE)+1 FROM SBI_THRESHOLD_VALUE),1) ,'SBI_THRESHOLD_VALUE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(FEATURE_ID)+1 FROM SBI_GEO_FEATURES),1) ,'SBI_GEO_FEATURES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(MAP_ID)+1 FROM SBI_GEO_MAPS),1) ,'SBI_GEO_MAPS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_AUDIT),1) ,'SBI_AUDIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ATTRIBUTE_ID)+1 FROM SBI_ATTRIBUTE),1) ,'SBI_ATTRIBUTE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(ID)+1 FROM SBI_USER) ,1),'SBI_USER');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(DS_ID)+1 FROM SBI_DATA_SET),1) ,'SBI_DATA_SET');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(DS_H_ID)+1 FROM SBI_DATA_SET_HISTORY),1) ,'SBI_DATA_SET_HISTORY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(DS_ID)+1 FROM SBI_DATA_SOURCE),1) ,'SBI_DATA_SOURCE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(DL_ID)+1 FROM SBI_DIST_LIST),1) ,'SBI_DIST_LIST');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(REL_ID)+1 FROM SBI_DIST_LIST_OBJECTS),1) ,'SBI_DIST_LIST_OBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(DLU_ID)+1 FROM SBI_DIST_LIST_USER) ,1),'SBI_DIST_LIST_USER');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(OBJ_METACONTENT_ID)+1 FROM SBI_OBJ_METACONTENTS),1) ,'SBI_OBJ_METACONTENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(OBJ_META_ID)+1 FROM SBI_OBJ_METADATA),1) ,'SBI_OBJ_METADATA');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (IFNULL((SELECT MAX(MENU_ID)+1 FROM SBI_MENU) ,1),'SBI_MENU');

INSERT INTO  SBI_EXPORTERS (ENGINE_ID,DOMAIN_ID,DEFAULT_VALUE)values((SELECT ENGINE_ID FROM SBI_ENGINES WHERE LABEL='WorksheetEngine'),(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'EXPORT_TYPE' AND VALUE_CD = 'XLS'), false);

ALTER TABLE SBI_ALARM_EVENT DROP FOREIGN KEY SBI_ALARM_EVENT_IBFK_1;
ALTER TABLE SBI_ALARM_EVENT ADD CONSTRAINT SBI_ALARM_EVENT_IBFK_1 FOREIGN KEY (ALARM_ID) REFERENCES SBI_ALARM (ALARM_ID) ON DELETE CASCADE ON UPDATE CASCADE;
--If this is not the correct name of your foreign key delete manually the foreign key related to the table SBI_OBJECTS
ALTER TABLE SBI_KPI_DOCUMENTS DROP FOREIGN KEY sbi_kpi_documents_ibfk_1;
ALTER TABLE SBI_KPI_DOCUMENTS  ADD CONSTRAINT FK_SBI_KPI_DOCUMENTS_1 FOREIGN KEY ( BIOBJ_ID ) REFERENCES  SBI_OBJECTS  ( BIOBJ_ID ) ON DELETE CASCADE ON UPDATE CASCADE;