/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.mapcatalogue.metadata;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8

/**
 * SbiGeoMapFeaturesId generated by hbm2java
 */
public class SbiGeoMapFeaturesId implements java.io.Serializable {

	// Fields    

	private int mapId;

	private int featureId;

	// Constructors

	/**
	 * default constructor.
	 */
	public SbiGeoMapFeaturesId() {
	}

	/**
	 * full constructor.
	 * 
	 * @param mapId the map id
	 * @param featureId the feature id
	 */
	public SbiGeoMapFeaturesId(int mapId, int featureId) {
		this.mapId = mapId;
		this.featureId = featureId;
	}

	// Property accessors
	/**
	 * Gets the map id.
	 * 
	 * @return the map id
	 */
	public int getMapId() {
		return this.mapId;
	}

	/**
	 * Sets the map id.
	 * 
	 * @param mapId the new map id
	 */
	public void setMapId(int mapId) {
		this.mapId = mapId;
	}

	/**
	 * Gets the feature id.
	 * 
	 * @return the feature id
	 */
	public int getFeatureId() {
		return this.featureId;
	}

	/**
	 * Sets the feature id.
	 * 
	 * @param featureId the new feature id
	 */
	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiGeoMapFeaturesId))
			return false;
		SbiGeoMapFeaturesId castOther = (SbiGeoMapFeaturesId) other;

		return (this.getMapId() == castOther.getMapId())
				&& (this.getFeatureId() == castOther.getFeatureId());
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMapId();
		result = 37 * result + this.getFeatureId();
		return result;
	}

}
