/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.commons.metadata;

// Generated 20-nov-2013 15.29.05 by Hibernate Tools 3.4.0.CR1

/**
 * SbiProductTypeEngineId generated by hbm2java
 */
public class SbiProductTypeEngineId implements java.io.Serializable {

	private int engineId;
	private int productTypeId;

	public SbiProductTypeEngineId() {
	}

	public SbiProductTypeEngineId(int engineId, int productTypeId) {
		this.engineId = engineId;
		this.productTypeId = productTypeId;
	}

	public int getEngineId() {
		return this.engineId;
	}

	public void setEngineId(int engineId) {
		this.engineId = engineId;
	}

	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiProductTypeEngineId))
			return false;
		SbiProductTypeEngineId castOther = (SbiProductTypeEngineId) other;

		return (this.getEngineId() == castOther.getEngineId()) && (this.getProductTypeId() == castOther.getProductTypeId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEngineId();
		result = 37 * result + this.getProductTypeId();
		return result;
	}

}
