<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:spagobiexportrecords" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:spagobiexportrecords" xmlns:intf="urn:spagobiexportrecords" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="processRecordsRequest">

      <wsdl:part name="in0" type="soapenc:string"/>

      <wsdl:part name="in1" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="processRecordsResponse">

      <wsdl:part name="processRecordsReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="ExportRecordsService">

      <wsdl:operation name="processRecords" parameterOrder="in0 in1">

         <wsdl:input message="impl:processRecordsRequest" name="processRecordsRequest"/>

         <wsdl:output message="impl:processRecordsResponse" name="processRecordsResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ExportRecordsServiceSoapBinding" type="impl:ExportRecordsService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="processRecords">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="processRecordsRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobiexportrecords" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="processRecordsResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobiexportrecords" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ExportRecordsServiceService">

      <wsdl:port binding="impl:ExportRecordsServiceSoapBinding" name="ExportRecordsService">

         <wsdlsoap:address location="http://localhost:8080/SpagoBI/services/ExportRecordsService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
