import { mount } from "@vue/test-utils";
import axios from "axios";
import Button from "primevue/button";
import flushPromises from "flush-promises";
import MenuConfiguration from "./MenuConfiguration.vue";
import InputText from "primevue/inputtext";
import ProgressBar from "primevue/progressbar";
import Card from "primevue/card";
import Toolbar from "primevue/toolbar";

const mockedMenuNodes = [
    {
        "menuId": 14,
        "objId": null,
        "objParameters": null,
        "subObjName": null,
        "snapshotName": null,
        "snapshotHistory": null,
        "functionality": null,
        "initialPath": null,
        "name": "test menu node",
        "descr": "description",
        "parentId": null,
        "level": 1,
        "depth": null,
        "prog": 1,
        "hasChildren": false,
        "lstChildren": [],
        "roles": [
        {
        "id": 1,
        "name": "dev",
        "description": "dev",
        "roleTypeCD": "DEV_ROLE",
        "code": null,
        "roleTypeID": 29,
        "organization": "DEFAULT_TENANT",
        "isPublic": null,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        },
        {
        "id": 25,
        "name": "demo admin",
        "description": "demo admin",
        "roleTypeCD": "ADMIN",
        "code": "demo_admin",
        "roleTypeID": 28,
        "organization": "DEFAULT_TENANT",
        "isPublic": false,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        },
        {
        "id": 13,
        "name": "/kte/admin",
        "description": "/kte/admin",
        "roleTypeCD": "ADMIN",
        "code": null,
        "roleTypeID": 28,
        "organization": "DEFAULT_TENANT",
        "isPublic": false,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        },
        {
        "id": 6,
        "name": "demo",
        "description": "demo",
        "roleTypeCD": "USER",
        "code": null,
        "roleTypeID": 27,
        "organization": "DEFAULT_TENANT",
        "isPublic": null,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        }
        ],
        "viewIcons": false,
        "hideToolbar": false,
        "hideSliders": false,
        "staticPage": "How_to.html",
        "code": null,
        "url": null,
        "iconPath": null,
        "icon": {
        "label": "",
        "className": "fas fa-bomb",
        "unicode": null,
        "visible": true,
        "id": 65,
        "category": "solid",
        "src": null
        },
        "custIcon": null,
        "iconCls": null,
        "groupingMenu": null,
        "linkType": null,
        "adminsMenu": false,
        "externalApplicationUrl": null,
        "clickable": true
        },
        {
        "menuId": 19,
        "objId": null,
        "objParameters": null,
        "subObjName": null,
        "snapshotName": null,
        "snapshotHistory": null,
        "functionality": "WorkspaceManagement",
        "initialPath": "datasets",
        "name": "kjkjl",
        "descr": "hklhkj",
        "parentId": null,
        "level": 1,
        "depth": null,
        "prog": 2,
        "hasChildren": false,
        "lstChildren": [],
        "roles": [
        {
        "id": 25,
        "name": "demo admin",
        "description": "demo admin",
        "roleTypeCD": "ADMIN",
        "code": "demo_admin",
        "roleTypeID": 28,
        "organization": "DEFAULT_TENANT",
        "isPublic": false,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        },
        {
        "id": 6,
        "name": "demo",
        "description": "demo",
        "roleTypeCD": "USER",
        "code": null,
        "roleTypeID": 27,
        "organization": "DEFAULT_TENANT",
        "isPublic": null,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        },
        {
        "id": 13,
        "name": "/kte/admin",
        "description": "/kte/admin",
        "roleTypeCD": "ADMIN",
        "code": null,
        "roleTypeID": 28,
        "organization": "DEFAULT_TENANT",
        "isPublic": false,
        "ableToCreateSelfServiceCockpit": false,
        "ableToCreateSelfServiceGeoreport": false,
        "ableToCreateSelfServiceKpi": false,
        "defaultRole": false,
        "roleMetaModelCategories": null,
        "ableToManageInternationalization": false,
        "ableToSeeNotes": false,
        "ableToSendMail": false,
        "ableToSaveIntoPersonalFolder": false,
        "ableToEnableDatasetPersistence": false,
        "ableToEnableFederatedDataset": false,
        "ableToEnableRate": false,
        "ableToEnablePrint": false,
        "ableToEnableCopyAndEmbed": false,
        "ableToManageCalendar": false,
        "ableToUseFunctionsCatalog": false,
        "ableToManageKpiValue": false,
        "ableToManageGlossaryTechnical": false,
        "ableToManageGlossaryBusiness": false,
        "ableToCreateCustomChart": false,
        "ableToSaveSubobjects": false,
        "ableToSeeSubobjects": false,
        "ableToEditPythonScripts": false,
        "ableToEditMyKpiComm": false,
        "ableToSaveMetadata": false,
        "ableToBuildQbeQuery": false,
        "ableToSaveRememberMe": false,
        "ableToHierarchiesManagement": false,
        "ableToSeeSubscriptions": false,
        "ableToSeeDocumentBrowser": false,
        "ableToEditAllKpiComm": false,
        "ableToSeeToDoList": false,
        "ableToCreateDocuments": false,
        "ableToDeleteKpiComm": false,
        "ableToSeeMyWorkspace": false,
        "ableToViewSocialAnalysis": false,
        "ableToManageUsers": false,
        "ableToSeeSnapshots": false,
        "ableToSeeMyData": false,
        "ableToSeeFavourites": false,
        "ableToSeeViewpoints": false,
        "ableToSeeMetadata": false,
        "ableToCreateSocialAnalysis": false,
        "ableToDoMassiveExport": false,
        "ableToRunSnapshots": false
        }
        ],
        "viewIcons": false,
        "hideToolbar": false,
        "hideSliders": false,
        "staticPage": null,
        "code": null,
        "url": null,
        "iconPath": null,
        "icon": {
        "label": "",
        "className": "fas fa-gem",
        "unicode": null,
        "visible": true,
        "id": 161,
        "category": "solid",
        "src": null
        },
        "custIcon": null,
        "iconCls": null,
        "groupingMenu": null,
        "linkType": null,
        "adminsMenu": false,
        "externalApplicationUrl": null,
        "clickable": true
        },
];

jest.mock("axios", () => ({
  get: jest.fn(() =>
    Promise.resolve({
      data: mockedMenuNodes,
    })
  ),
  delete: jest.fn(() => Promise.resolve()),
  post: jest.fn(() => Promise.resolve()),
}));

const $confirm = {
  require: jest.fn(),
};
const $store = {
  commit: jest.fn(),
};

const factory = () => {
  return mount(MenuConfiguration, {
    attachToDocument: true,
    global: {
      plugins: [],
      stubs: { Button, InputText, ProgressBar, Toolbar, Card },
      mocks: {
        $t: (msg) => msg,
        $store,
        $confirm,
      },
    },
  });
};

afterEach(() => {
  jest.clearAllMocks();
});

describe("menu configuration management loading", () => {
  it("show progress bar when loading", async () => {
    const wrapper = factory();

    expect(wrapper.vm.loading).toBe(true);
    expect(wrapper.find('[data-test="progress-bar"]').exists()).toBe(true);
  });

  it('shows "no data" label when loaded empty', async () => {
    axios.get.mockReturnValueOnce(
      Promise.resolve({
        data: [],
      })
    );
    const wrapper = factory();
    await flushPromises();
    expect(wrapper.vm.menuNodes.length).toBe(0);
    expect(wrapper.find('[data-test="menu-nodes-tree"]').html()).toContain(
      "common.info.noDataFound"
    );
  });
});

describe("menu configuration management", () => {

  it("deletes menu node clicking on delete icon", async () => {
    const wrapper = factory();
    await flushPromises();
    const deleteButton = wrapper.find('[data-test="deleteBtn"]');
    await deleteButton.trigger("click");
    expect($confirm.require).toHaveBeenCalledTimes(1);
    await wrapper.vm.onNodeDelete(1);
    await wrapper.vm.loadMenuNodes();
  });

  it("opens empty form when the '+' button is clicked", async () => {
    const wrapper = factory();
    const openButton = wrapper.find('[data-test="open-form-button"]');
    await openButton.trigger("click");
    expect(wrapper.vm.hiddenForm).toBe(false);
  });

 
});