-- -----------------------------------
-- knowage Database script
-- Important: Execute this script after creating the main tables
-- ------------------------------------


-- tables for different knowage product types
CREATE TABLE SBI_PRODUCT_TYPE (
	PRODUCT_TYPE_ID INTEGER NOT NULL,
	LABEL VARCHAR(40) NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(PRODUCT_TYPE_ID),
	CONSTRAINT XAK1SBI_PRODUCT_TYPE UNIQUE (LABEL, ORGANIZATION)
) WITHOUT OIDS;

-- mapping table between organizations (tenants) and product types
CREATE TABLE SBI_ORGANIZATION_PRODUCT_TYPE (
	PRODUCT_TYPE_ID INTEGER NOT NULL,
	ORGANIZATION_ID INTEGER NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(PRODUCT_TYPE_ID, ORGANIZATION_ID),
	CONSTRAINT FK_PRODUCT_TYPE_1 FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES SBI_PRODUCT_TYPE (PRODUCT_TYPE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FK_ORGANIZATION_3 FOREIGN KEY (ORGANIZATION_ID) REFERENCES SBI_ORGANIZATIONS (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_PRODUCT_TYPE_1_IDX ON SBI_ORGANIZATION_PRODUCT_TYPE (PRODUCT_TYPE_ID);
CREATE INDEX FK_ORGANIZATION_3_IDX ON SBI_ORGANIZATION_PRODUCT_TYPE (ORGANIZATION_ID);

-- modify sbi_user_func with product_id fk 
ALTER TABLE SBI_ROLE_TYPE_USER_FUNC DROP CONSTRAINT FK_SBI_ROLE_TYPE_USER_FUNC_2;
DROP TABLE SBI_USER_FUNC;
CREATE TABLE SBI_USER_FUNC (
	USER_FUNCT_ID 		INTEGER NOT NULL ,
	NAME 	            VARCHAR(50),  
	DESCRIPTION 	        VARCHAR(100),
	PRODUCT_TYPE_ID INTEGER NOT NULL,
	USER_IN              VARCHAR(100) NOT NULL,
	USER_UP              VARCHAR(100),
	USER_DE              VARCHAR(100),
	TIME_IN              TIMESTAMP NOT NULL,
	TIME_UP              TIMESTAMP NULL DEFAULT NULL,
	TIME_DE              TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN       VARCHAR(10),
	SBI_VERSION_UP       VARCHAR(10),
	SBI_VERSION_DE       VARCHAR(10),
	META_VERSION         VARCHAR(100),
	ORGANIZATION         VARCHAR(20),
	PRIMARY KEY (USER_FUNCT_ID)
) WITHOUT OIDS;
ALTER TABLE SBI_USER_FUNC ADD CONSTRAINT FK_PRODUCT_TYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES SBI_PRODUCT_TYPE (PRODUCT_TYPE_ID);
ALTER TABLE SBI_ROLE_TYPE_USER_FUNC ADD CONSTRAINT FK_SBI_ROLE_TYPE_USER_FUNC_2 FOREIGN KEY  ( USER_FUNCT_ID ) REFERENCES SBI_USER_FUNC(USER_FUNCT_ID);
	
-- modify sbi_authorization with product_id fk
ALTER TABLE SBI_AUTHORIZATIONS_ROLES DROP CONSTRAINT FK_AUTHORIZATION_1;
DROP TABLE SBI_AUTHORIZATIONS;
CREATE TABLE SBI_AUTHORIZATIONS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(200) DEFAULT NULL,
  PRODUCT_TYPE_ID INTEGER NOT NULL,
  USER_IN VARCHAR(100) NOT NULL,
  USER_UP VARCHAR(100) DEFAULT NULL,
  USER_DE VARCHAR(100) DEFAULT NULL,
  TIME_IN timestamp NOT NULL,
  TIME_UP timestamp DEFAULT NULL,
  TIME_DE timestamp DEFAULT NULL,
  SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
  SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
  SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
  META_VERSION VARCHAR(100) DEFAULT NULL,
  ORGANIZATION VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID)
) WITHOUT OIDS;
ALTER TABLE SBI_AUTHORIZATIONS ADD CONSTRAINT FK2_PRODUCT_TYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES SBI_PRODUCT_TYPE (PRODUCT_TYPE_ID);
ALTER TABLE SBI_AUTHORIZATIONS_ROLES ADD  CONSTRAINT FK_AUTHORIZATION_1 FOREIGN KEY (AUTHORIZATION_ID) REFERENCES SBI_AUTHORIZATIONS (ID);

-- create: GLOSSARY tables
CREATE TABLE SBI_GL_WORD (
	WORD_ID Integer NOT NULL ,
	WORD VARCHAR (100),
	DESCR VARCHAR (500),
	FORMULA VARCHAR (500),
	STATE INTEGER DEFAULT NULL,
	CATEGORY INTEGER DEFAULT NULL,
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(WORD_ID),
  	CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES SBI_DOMAINS (VALUE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  	CONSTRAINT FK_STATE FOREIGN KEY (STATE) REFERENCES SBI_DOMAINS (VALUE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_CATEGORY_IDX ON SBI_GL_WORD (CATEGORY);
CREATE INDEX FK_STATE_IDX ON SBI_GL_WORD (STATE);

CREATE TABLE SBI_GL_ATTRIBUTES (
	ATTRIBUTE_ID Integer NOT NULL ,
	ATTRIBUTE_CD VARCHAR (30),
	ATTRIBUTE_NM VARCHAR (100),
	ATTRIBUTE_DS VARCHAR (500),
	MANDATORY_FL Integer,
	ATTRIBUTES_TYPE VARCHAR (50),
	DOMAIN VARCHAR (500),
	FORMAT VARCHAR (30),
	DISPLAY_TP VARCHAR (30),
	ATTRIBUTES_ORDER VARCHAR (30),
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(ATTRIBUTE_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_GL_WORD_ATTR (
	WORD_ID Integer NOT NULL ,
	ATTRIBUTE_ID Integer NOT NULL ,
	ATTR_VALUE VARCHAR (500),
	ATTR_ORDER Integer,
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(WORD_ID,ATTRIBUTE_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_GL_REFERENCES (
	WORD_ID Integer NOT NULL ,
	REF_WORD_ID Integer NOT NULL ,
	REFERENCES_ORDER Integer,
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(WORD_ID,REF_WORD_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_GL_GLOSSARY (
	GLOSSARY_ID Integer NOT NULL ,
	GLOSSARY_CD VARCHAR (30),
	GLOSSARY_NM VARCHAR (100),
	GLOSSARY_DS VARCHAR (500),
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(GLOSSARY_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_GL_CONTENTS (
	CONTENT_ID Integer NOT NULL ,
	GLOSSARY_ID Integer NOT NULL ,
	PARENT_ID Integer,
	CONTENT_CD VARCHAR (30),
	CONTENT_NM VARCHAR (100),
	CONTENT_DS VARCHAR (500),
	DEPTH Integer,
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(CONTENT_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_GL_WLIST (
	CONTENT_ID Integer NOT NULL ,
	WORD_ID Integer NOT NULL ,
	WORD_ORDER Integer,
	
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY(CONTENT_ID,WORD_ID) 
) WITHOUT OIDS;

CREATE TABLE SBI_PRODUCT_TYPE_ENGINE (
	PRODUCT_TYPE_ID INTEGER NOT NULL,
	ENGINE_ID INTEGER NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) DEFAULT NULL,
	USER_DE VARCHAR(100) DEFAULT NULL,
	TIME_IN TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
	META_VERSION VARCHAR(100) DEFAULT NULL,
	ORGANIZATION VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (PRODUCT_TYPE_ID, ENGINE_ID)
) WITHOUT OIDS;

CREATE TABLE SBI_IMAGES (
	IMAGE_ID INTEGER NOT NULL,
	NAME varchar(100) NOT NULL,
	CONTENT BYTEA NOT NULL,
	CONTENT_ICO BYTEA,
	USER_IN varchar(100) DEFAULT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (IMAGE_ID),
	CONSTRAINT NAME_UNIQUE_1 UNIQUE (NAME)
) WITHOUT OIDS;


CREATE TABLE SBI_GL_DOCWLIST (
	WORD_ID INTEGER NOT NULL,
	BIOBJ_ID INTEGER NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) NULL DEFAULT NULL,
	USER_DE VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION VARCHAR(100) NULL DEFAULT NULL,
	ORGANIZATION VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (BIOBJ_ID, WORD_ID),
	CONSTRAINT FK_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_DOCUMENT_ID FOREIGN KEY (BIOBJ_ID) REFERENCES SBI_OBJECTS (BIOBJ_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_WORD_ID_IDX ON SBI_GL_DOCWLIST (WORD_ID);
CREATE INDEX FK_DOCUMENT_ID_IDX ON SBI_GL_DOCWLIST (BIOBJ_ID);

CREATE TABLE SBI_GL_DATASETWLIST (
	WORD_ID INTEGER NOT NULL REFERENCES SBI_GL_WORD (WORD_ID) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION,
	DS_ID INTEGER NOT NULL,
	COLUMN_NAME VARCHAR(100) NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) DEFAULT NULL,
	USER_DE VARCHAR(100) DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
	META_VERSION VARCHAR(100) DEFAULT NULL,
	ORGANIZATION VARCHAR(20) DEFAULT NULL,
	VERSION_NUM INTEGER DEFAULT NULL,
	PRIMARY KEY (WORD_ID,DS_ID,COLUMN_NAME)
) WITHOUT OIDS;
CREATE INDEX ORGANIZATION_IDX ON SBI_GL_DATASETWLIST (ORGANIZATION);
CREATE INDEX FK_DS_ID ON SBI_GL_DATASETWLIST (DS_ID);
CREATE INDEX FK_WORD_ID_IDX_1 ON SBI_GL_DATASETWLIST (WORD_ID);

CREATE TABLE SBI_GL_TABLE (
	TABLE_ID INTEGER NOT NULL,
	LABEL varchar(100) NOT NULL, USER_IN varchar(100) DEFAULT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (TABLE_ID)
) WITHOUT OIDS;

CREATE TABLE SBI_GL_BNESS_CLS (
	BC_ID SERIAL,
	DATAMART_NAME varchar(100) NOT NULL,
	UNIQUE_IDENTIFIER varchar(100) NOT NULL,
	USER_IN varchar(100) DEFAULT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (BC_ID)
) WITHOUT OIDS;

CREATE TABLE SBI_GL_BNESS_CLS_WLIST (
	WORD_ID INTEGER NOT NULL,
	BC_ID INTEGER NOT NULL,
	COLUMN_NAME varchar(100) DEFAULT NULL,
	USER_IN varchar(100) NOT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (BC_ID,WORD_ID),
	CONSTRAINT FK_BC_ID FOREIGN KEY (BC_ID) REFERENCES SBI_GL_BNESS_CLS (BC_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_BC_ID_IDX ON SBI_GL_BNESS_CLS_WLIST (BC_ID);
CREATE INDEX FK_WORD_ID_IDX_2 ON SBI_GL_BNESS_CLS_WLIST (WORD_ID);

CREATE TABLE SBI_GL_TABLE_WLIST (
	WORD_ID INTEGER NOT NULL,
	TABLE_ID INTEGER NOT NULL,
	USER_IN varchar(100) NOT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (TABLE_ID,WORD_ID),
	CONSTRAINT FK_TABLE_ID FOREIGN KEY (TABLE_ID) REFERENCES SBI_GL_TABLE (TABLE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_TABLE_ID_IDX ON SBI_GL_TABLE_WLIST (TABLE_ID);
CREATE INDEX FK_WORD_ID_IDX_3 ON SBI_GL_TABLE_WLIST (WORD_ID);

CREATE TABLE SBI_WS_EVENT (
	ID INTEGER NOT NULL,
	EVENT_NAME VARCHAR(80) NOT NULL,
	IP_COME_FROM VARCHAR(15) NULL,
	INCOMING_DATE TIMESTAMP NULL,
	TAKE_CHARGE_DATE TIMESTAMP NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) DEFAULT NULL,
	USER_DE VARCHAR(100) DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
	META_VERSION VARCHAR(100) DEFAULT NULL,
	ORGANIZATION VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (id)
) WITHOUT OIDS;

-- Create Foreign keys section

ALTER TABLE SBI_GL_WORD_ATTR ADD FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID);

ALTER TABLE SBI_GL_REFERENCES ADD FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID);

ALTER TABLE SBI_GL_REFERENCES ADD FOREIGN KEY (REF_WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID);

ALTER TABLE SBI_GL_WLIST ADD FOREIGN KEY (WORD_ID) REFERENCES SBI_GL_WORD (WORD_ID);

ALTER TABLE SBI_GL_WORD_ATTR ADD FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SBI_GL_ATTRIBUTES (ATTRIBUTE_ID);

ALTER TABLE SBI_GL_CONTENTS ADD FOREIGN KEY (GLOSSARY_ID) REFERENCES SBI_GL_GLOSSARY (GLOSSARY_ID);

ALTER TABLE SBI_GL_CONTENTS ADD FOREIGN KEY (PARENT_ID) REFERENCES SBI_GL_CONTENTS (CONTENT_ID);

ALTER TABLE SBI_GL_WLIST ADD FOREIGN KEY (CONTENT_ID) REFERENCES SBI_GL_CONTENTS (CONTENT_ID);
	
ALTER TABLE SBI_PRODUCT_TYPE_ENGINE ADD CONSTRAINT FK_PRODUCT_TYPE_2 FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES SBI_PRODUCT_TYPE (PRODUCT_TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SBI_PRODUCT_TYPE_ENGINE ADD CONSTRAINT FK_ENGINE_2 FOREIGN KEY (ENGINE_ID) REFERENCES SBI_ENGINES (ENGINE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;



---- TIMESPAN

  
CREATE TABLE SBI_TIMESPAN (
	ID INTEGER NOT NULL,
	NAME varchar(45) NOT NULL,
	TYPE varchar(45) NOT NULL,
	CATEGORY varchar(45) DEFAULT NULL,
	STATIC_FILTER SMALLINT DEFAULT 0,
	DEFINITION varchar(4000) DEFAULT NULL,
	USER_IN varchar(100) NOT NULL,
	USER_UP varchar(100) DEFAULT NULL,
	USER_DE varchar(100) DEFAULT NULL,
	TIME_IN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP timestamp NULL DEFAULT NULL,
	TIME_DE timestamp NULL DEFAULT NULL,
	SBI_VERSION_IN varchar(10) DEFAULT NULL,
	SBI_VERSION_UP varchar(10) DEFAULT NULL,
	SBI_VERSION_DE varchar(10) DEFAULT NULL,
	META_VERSION varchar(100) DEFAULT NULL,
	ORGANIZATION varchar(20) DEFAULT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

-- LAYER CATALOGUE --
DROP TABLE SBI_GEO_LAYERS;
CREATE TABLE SBI_GEO_LAYERS (
  LAYER_ID INTEGER NOT NULL,
  LABEL varchar(100) NOT NULL,
  NAME varchar(100),
  DESCR varchar(100),
  LAYER_DEFINITION BYTEA NOT NULL,
  TYPE varchar(40),
  IS_BASE_LAYER BOOLEAN DEFAULT FALSE,
  GEO_CATEGORY INTEGER NULL,
  USER_IN varchar(100) NOT NULL,
  USER_UP varchar(100) DEFAULT NULL,
  USER_DE varchar(100) DEFAULT NULL,
  TIME_IN timestamp NOT NULL,
  TIME_UP timestamp NULL DEFAULT NULL,
  TIME_DE timestamp NULL DEFAULT NULL,
  SBI_VERSION_IN varchar(10) DEFAULT NULL,
  SBI_VERSION_UP varchar(10) DEFAULT NULL,
  SBI_VERSION_DE varchar(10) DEFAULT NULL,
  META_VERSION varchar(100) DEFAULT NULL,
  ORGANIZATION varchar(20) DEFAULT NULL,
  CONSTRAINT XAK1SBI_GEO_LAYERS UNIQUE (NAME, TYPE, ORGANIZATION),
  PRIMARY KEY (LAYER_ID)
) WITHOUT OIDS;

CREATE TABLE SBI_ROLES_LAYERS (
	ID_LAYER INTEGER NOT NULL,
	ID_ROLE INTEGER NOT NULL,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) DEFAULT NULL,
	USER_DE VARCHAR(100) DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
	META_VERSION VARCHAR(100) DEFAULT NULL,
	ORGANIZATION VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (ID_LAYER,ID_ROLE),
	CONSTRAINT FK_ID_LAYER FOREIGN KEY (ID_LAYER) REFERENCES SBI_GEO_LAYERS (LAYER_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_ID_ROLE FOREIGN KEY (ID_ROLE) REFERENCES SBI_EXT_ROLES (EXT_ROLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
) WITHOUT OIDS;
CREATE INDEX FK_ID_LAYER_IDX ON SBI_ROLES_LAYERS (ID_LAYER);
CREATE INDEX FK_ID_ROLE_IDX ON SBI_ROLES_LAYERS (ID_ROLE);

ALTER TABLE SBI_PARUSE_CK DROP CONSTRAINT FK_SBI_PARUSE_CK_1;
ALTER TABLE SBI_PARUSE_DET DROP CONSTRAINT FK_SBI_PARUSE_DET_1;
ALTER TABLE SBI_OBJ_PARUSE DROP CONSTRAINT FK_SBI_OBJ_PARUSE_2;
DROP TABLE SBI_PARUSE;
CREATE TABLE SBI_PARUSE (
	USE_ID              INTEGER NOT NULL ,
	LOV_ID              INTEGER NULL,
	DEFAULT_LOV_ID      INTEGER NULL,
	DEFAULT_FORMULA     VARCHAR(4000) NULL,
	LABEL               VARCHAR(20) NOT NULL,
	DESCR               VARCHAR(160) NULL,
	PAR_ID              INTEGER NOT NULL,
	NAME                VARCHAR(40) NOT NULL,
	MAN_IN              INTEGER NOT NULL,
	MAXIMIZER_ENABLED   BOOLEAN DEFAULT FALSE,
	SELECTION_TYPE      VARCHAR(20) DEFAULT 'LIST',
	MULTIVALUE_FLAG     INTEGER DEFAULT 0,
	VALUE_SELECTION     VARCHAR(20) NULL,
	SELECTED_LAYER      VARCHAR(100) NULL,
	SELECTED_LAYER_PROP VARCHAR(40) NULL,
	USER_IN             VARCHAR(100) NOT NULL,
	USER_UP             VARCHAR(100),
	USER_DE             VARCHAR(100),
	TIME_IN             TIMESTAMP NOT NULL,
	TIME_UP             TIMESTAMP NULL DEFAULT NULL,
	TIME_DE             TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN      VARCHAR(10),
	SBI_VERSION_UP      VARCHAR(10),
	SBI_VERSION_DE      VARCHAR(10),
	META_VERSION        VARCHAR(100),
	ORGANIZATION        VARCHAR(20),    
	CONSTRAINT XAK1SBI_PARUSE UNIQUE  (PAR_ID,LABEL),
	PRIMARY KEY (USE_ID)
) WITHOUT OIDS;
ALTER TABLE SBI_OBJ_PARUSE ADD CONSTRAINT FK_SBI_OBJ_PARUSE_2 FOREIGN KEY (USE_ID) REFERENCES SBI_PARUSE (USE_ID) ON DELETE RESTRICT;
ALTER TABLE SBI_PARUSE_DET ADD CONSTRAINT FK_SBI_PARUSE_DET_1 FOREIGN KEY (USE_ID) REFERENCES SBI_PARUSE (USE_ID) ON DELETE RESTRICT;
ALTER TABLE SBI_PARUSE_CK ADD CONSTRAINT FK_SBI_PARUSE_CK_1 FOREIGN KEY (USE_ID) REFERENCES SBI_PARUSE (USE_ID) ON DELETE RESTRICT;

ALTER TABLE SBI_OBJ_PAR DROP CONSTRAINT FK_SBI_OBJ_PAR_2;
DROP TABLE SBI_PARAMETERS;
CREATE TABLE SBI_PARAMETERS (
	PAR_ID              INTEGER NOT NULL ,
	DESCR               VARCHAR(160) NULL,
	LENGTH              SMALLINT NOT NULL,
	LABEL               VARCHAR(20) NOT NULL,
	PAR_TYPE_CD         VARCHAR(20) NOT NULL,
	MASK                VARCHAR(20) NULL,
	PAR_TYPE_ID         INTEGER NOT NULL,
	NAME                VARCHAR(40) NOT NULL,
	FUNCTIONAL_FLAG     SMALLINT NOT NULL DEFAULT 1,
	TEMPORAL_FLAG       SMALLINT NOT NULL DEFAULT 0,
	VALUE_SELECTION     VARCHAR(20) NULL,
	SELECTED_LAYER      VARCHAR(100) NULL,
	SELECTED_LAYER_PROP VARCHAR(40) NULL,
	USER_IN             VARCHAR(100) NOT NULL,
	USER_UP             VARCHAR(100),
	USER_DE             VARCHAR(100),
	TIME_IN             TIMESTAMP NOT NULL,
	TIME_UP             TIMESTAMP NULL DEFAULT NULL,
	TIME_DE             TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN      VARCHAR(10),
	SBI_VERSION_UP      VARCHAR(10),
	SBI_VERSION_DE      VARCHAR(10),
	META_VERSION        VARCHAR(100),
	ORGANIZATION        VARCHAR(20),   
	CONSTRAINT XAK1SBI_PARAMETERS UNIQUE  (LABEL, ORGANIZATION),
	PRIMARY KEY (PAR_ID)
) WITHOUT OIDS;
ALTER TABLE SBI_OBJ_PAR ADD CONSTRAINT FK_SBI_OBJ_PAR_2 FOREIGN KEY (PAR_ID) REFERENCES SBI_PARAMETERS (PAR_ID) ON DELETE RESTRICT;