DROP TABLE IF EXISTS SBI_USER_HISTORY;
CREATE TABLE SBI_USER_HISTORY (
	EVENT_ID			INT NOT NULL,
	USER_ID				CHAR(100) NOT NULL,
	PASSWORD			VARCHAR(150),
	FULL_NAME			VARCHAR(255),
	ID					INT NOT NULL,
	DT_PWD_BEGIN		DATETIME,
	DT_PWD_END			DATETIME,
	FLG_PWD_BLOCKED		BOOLEAN,
	DT_LAST_ACCESS		DATETIME,
	IS_SUPERADMIN		TINYINT(1) DEFAULT 0,
	USER_IN				VARCHAR(100) NULL DEFAULT NULL,
	USER_UP				VARCHAR(100) NULL DEFAULT NULL,
	USER_DE				VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN				TIMESTAMP NULL DEFAULT NULL,
	TIME_UP				TIMESTAMP NULL DEFAULT NULL,
	TIME_DE				TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN		VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP		VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE		VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION		VARCHAR(100),
	ORGANIZATION		VARCHAR(20),
	TIME_START          TIMESTAMP NULL DEFAULT NULL,
	TIME_END            TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY(EVENT_ID)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS SBI_EXT_USER_ROLES_HISTORY;
CREATE TABLE SBI_EXT_USER_ROLES_HISTORY (
	EVENT_ID			INT NOT NULL,
	ID 					INT NOT NULL,
	EXT_ROLE_ID			INT NOT NULL,
	USER_IN				VARCHAR(100) NULL DEFAULT NULL,
	USER_UP				VARCHAR(100) NULL DEFAULT NULL,
	USER_DE				VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN				TIMESTAMP NULL DEFAULT NULL,
	TIME_UP				TIMESTAMP NULL DEFAULT NULL,
	TIME_DE				TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN		VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP		VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE		VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION		VARCHAR(100),
	ORGANIZATION		VARCHAR(20),
	TIME_START			TIMESTAMP NULL DEFAULT NULL,
	TIME_END			TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (EVENT_ID)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS SBI_USER_ATTRIBUTES_HISTORY;
CREATE TABLE SBI_USER_ATTRIBUTES_HISTORY (
	EVENT_ID			INT NOT NULL,
	ID 					INT NOT NULL,
	ATTRIBUTE_ID 		INT NOT NULL,
	ATTRIBUTE_VALUE		VARCHAR(500),
	USER_IN              VARCHAR(100) NULL DEFAULT NULL,
	USER_UP              VARCHAR(100) NULL DEFAULT NULL,
	USER_DE              VARCHAR(100) NULL DEFAULT NULL,
	TIME_IN              TIMESTAMP NULL DEFAULT NULL,
	TIME_UP              TIMESTAMP NULL DEFAULT NULL,
	TIME_DE              TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN       VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_UP       VARCHAR(10) NULL DEFAULT NULL,
	SBI_VERSION_DE       VARCHAR(10) NULL DEFAULT NULL,
	META_VERSION         VARCHAR(100),
	ORGANIZATION         VARCHAR(20),     
	TIME_START          TIMESTAMP NULL DEFAULT NULL,
	TIME_END            TIMESTAMP NULL DEFAULT NULL,
 	PRIMARY KEY (EVENT_ID)
) ENGINE=InnoDB;

