DROP TABLE IF EXISTS A_T_ASS_CAL_CFG_ATTRIB CASCADE ;
DROP TABLE IF EXISTS A_T_CAL_ATTRIBUTES CASCADE ;
DROP TABLE IF EXISTS A_T_CAL_CFG CASCADE ;
DROP TABLE IF EXISTS A_T_CAL_ATT_DOMAIN CASCADE ;
DROP TABLE IF EXISTS A_T_CALENDAR CASCADE ;
DROP TABLE IF EXISTS A_D_TIME_BY_DAY CASCADE ;
DROP TABLE IF EXISTS hibernate_sequences CASCADE ;
