/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.wapp.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiMenuRole generated by hbm2java
 */

public class SbiMenuRole  extends SbiHibernateModel {


    // Fields    
     private SbiMenuRoleId id;
     private SbiMenu sbiMenu;
     private SbiExtRoles sbiExtRoles;


    // Constructors

    /**
     * default constructor.
     */
    public SbiMenuRole() {
    }

    
    /**
     * full constructor.
     * 
     * @param id the id
     * @param sbiMenu the sbi menu
     * @param sbiExtRoles the sbi ext roles
     */
    public SbiMenuRole(SbiMenuRoleId id, SbiMenu sbiMenu, SbiExtRoles sbiExtRoles) {
        this.id = id;
        this.sbiMenu = sbiMenu;
        this.sbiExtRoles = sbiExtRoles;
    }
    

   
    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiMenuRoleId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiMenuRoleId id) {
        this.id = id;
    }

    /**
     * Gets the sbi menu.
     * 
     * @return the sbi menu
     */
    public SbiMenu getSbiMenu() {
        return this.sbiMenu;
    }
    
    /**
     * Sets the sbi menu.
     * 
     * @param sbiMenu the new sbi menu
     */
    public void setSbiMenu(SbiMenu sbiMenu) {
        this.sbiMenu = sbiMenu;
    }

    /**
     * Gets the sbi ext roles.
     * 
     * @return the sbi ext roles
     */
    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    /**
     * Sets the sbi ext roles.
     * 
     * @param sbiExtRoles the new sbi ext roles
     */
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }
   








}
