/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.wapp.metadata;
// Generated 9-apr-2008 12.18.27 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiMenu generated by hbm2java
 */

public class SbiMenu  extends SbiHibernateModel {


    // Fields    

     private Integer menuId;
     private Integer objId;
     private String objParameters;
     private String subObjName;
     private String snapshotName;
     private Integer snapshotHistory;
     private String functionality;
     private String initialPath;
     private String name;
     private String descr;
     private String staticPage;    
     private String externalApplicationUrl;
	 private Integer parentId;
     private Set sbiMenuRoles = new HashSet(0);
     private Boolean viewIcons;
     private Boolean hideToolbar;
     private Boolean hideSliders;
     private Integer prog;
     

    // Constructors

    /**
     * default constructor.
     */
    public SbiMenu() {
    }

	/**
	 * minimal constructor.
	 * 
	 * @param menuId the menu id
	 */
    public SbiMenu(Integer menuId) {
        this.menuId = menuId;
    }
    
    public SbiMenu(Integer menuId, Integer objId, String objParameters,
			String subObjName, String snapshotName, Integer snapshotHistory,
			String functionality, String initialPath, String name,
			String descr, String staticPage, String externalApplicationUrl,
			Integer parentId, Set sbiMenuRoles, Boolean viewIcons,
			Boolean hideToolbar, Boolean hideSliders, Integer prog) {
		super();
		this.menuId = menuId;
		this.objId = objId;
		this.objParameters = objParameters;
		this.subObjName = subObjName;
		this.snapshotName = snapshotName;
		this.snapshotHistory = snapshotHistory;
		this.functionality = functionality;
		this.initialPath = initialPath;
		this.name = name;
		this.descr = descr;
		this.staticPage = staticPage;
		this.externalApplicationUrl = externalApplicationUrl;
		this.parentId = parentId;
		this.sbiMenuRoles = sbiMenuRoles;
		this.viewIcons = viewIcons;
		this.hideToolbar = hideToolbar;
		this.hideSliders = hideSliders;
		this.prog = prog;
	}

	// Property accessors

    /**
     * Gets the menu id.
     * 
     * @return the menu id
     */
    public Integer getMenuId() {
        return this.menuId;
    }
    
    /**
     * Sets the menu id.
     * 
     * @param menuId the new menu id
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }
    
    /**
     * Sets the name.
     * 
     * @param name the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the descr.
     * 
     * @return the descr
     */
    public String getDescr() {
        return this.descr;
    }
    
    /**
     * Sets the descr.
     * 
     * @param descr the new descr
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * Gets the parent id.
     * 
     * @return the parent id
     */
    public Integer getParentId() {
        return this.parentId;
    }
    
    /**
     * Sets the parent id.
     * 
     * @param parentId the new parent id
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * Gets the sbi menu roles.
     * 
     * @return the sbi menu roles
     */
    public Set getSbiMenuRoles() {
        return this.sbiMenuRoles;
    }
    
    /**
     * Sets the sbi menu roles.
     * 
     * @param sbiMenuRoles the new sbi menu roles
     */
    public void setSbiMenuRoles(Set sbiMenuRoles) {
        this.sbiMenuRoles = sbiMenuRoles;
    }

	public Boolean getViewIcons() {
		return viewIcons;
	}

	public void setViewIcons(Boolean viewIcons) {
		this.viewIcons = viewIcons;
	}

	public Boolean getHideToolbar() {
		return hideToolbar;
	}

	public void setHideToolbar(Boolean hideToolbar) {
		this.hideToolbar = hideToolbar;
	}

	public String getStaticPage() {
		return staticPage;
	}

	public void setStaticPage(String staticPage) {
		this.staticPage = staticPage;
	}

	public String getObjParameters() {
		return objParameters;
	}

	public void setObjParameters(String objParameters) {
		this.objParameters = objParameters;
	}

	public String getSubObjName() {
		return subObjName;
	}

	public void setSubObjName(String subObjName) {
		this.subObjName = subObjName;
	}

	public String getSnapshotName() {
		return snapshotName;
	}

	public void setSnapshotName(String snapshotName) {
		this.snapshotName = snapshotName;
	}

	public Integer getSnapshotHistory() {
		return snapshotHistory;
	}

	public void setSnapshotHistory(Integer snapshotHistory) {
		this.snapshotHistory = snapshotHistory;
	}

	public Integer getObjId() {
		return objId;
	}

	public void setObjId(Integer objId) {
		this.objId = objId;
	}

	public Boolean getHideSliders() {
		return hideSliders;
	}

	public void setHideSliders(Boolean hideSliders) {
		this.hideSliders = hideSliders;
	}

	public String getFunctionality() {
		return functionality;
	}

	public void setFunctionality(String functionality) {
		this.functionality = functionality;
	}

	public Integer getProg() {
		return prog;
	}

	public void setProg(Integer prog) {
		this.prog = prog;
	}

	public String getInitialPath() {
		return initialPath;
	}

	public void setInitialPath(String initialPath) {
		this.initialPath = initialPath;
	}

    public String getExternalApplicationUrl() {
		return externalApplicationUrl;
	}

	public void setExternalApplicationUrl(String externalApplicationUrl) {
		this.externalApplicationUrl = externalApplicationUrl;
	}

}
