/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiDistributionList generated by hbm2java
 */

public class SbiDistributionList  extends SbiHibernateModel {


    // Fields    

     private Integer dlId;
     private String name;
     private String descr;
     private Set sbiDistributionListUsers = new HashSet(0);
     private Set sbiDistributionListsObjectses = new HashSet(0);


    // Constructors

    /**
     * default constructor.
     */
    public SbiDistributionList() {
    }

	/**
	 * minimal constructor.
	 * 
	 * @param dlId the dl id
	 * @param name the name
	 */
    public SbiDistributionList(Integer dlId, String name) {
        this.dlId = dlId;
        this.name = name;
    }
    
    /**
     * full constructor.
     * 
     * @param dlId the dl id
     * @param name the name
     * @param descr the descr
     * @param sbiDistributionListUsers the sbi distribution list users
     * @param sbiDistributionListsObjectses the sbi distribution lists objectses
     */
    public SbiDistributionList(Integer dlId, String name, String descr, Set sbiDistributionListUsers, Set sbiDistributionListsObjectses) {
        this.dlId = dlId;
        this.name = name;
        this.descr = descr;
        this.sbiDistributionListUsers = sbiDistributionListUsers;
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
    

   
    // Property accessors

    /**
     * Gets the dl id.
     * 
     * @return the dl id
     */
    public Integer getDlId() {
        return this.dlId;
    }
    
    /**
     * Sets the dl id.
     * 
     * @param dlId the new dl id
     */
    public void setDlId(Integer dlId) {
        this.dlId = dlId;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }
    
    /**
     * Sets the name.
     * 
     * @param name the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the descr.
     * 
     * @return the descr
     */
    public String getDescr() {
        return this.descr;
    }
    
    /**
     * Sets the descr.
     * 
     * @param descr the new descr
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * Gets the sbi distribution list users.
     * 
     * @return the sbi distribution list users
     */
    public Set getSbiDistributionListUsers() {
        return this.sbiDistributionListUsers;
    }
    
    /**
     * Sets the sbi distribution list users.
     * 
     * @param sbiDistributionListUsers the new sbi distribution list users
     */
    public void setSbiDistributionListUsers(Set sbiDistributionListUsers) {
        this.sbiDistributionListUsers = sbiDistributionListUsers;
    }

    /**
     * Gets the sbi distribution lists objectses.
     * 
     * @return the sbi distribution lists objectses
     */
    public Set getSbiDistributionListsObjectses() {
        return this.sbiDistributionListsObjectses;
    }
    
    /**
     * Sets the sbi distribution lists objectses.
     * 
     * @param sbiDistributionListsObjectses the new sbi distribution lists objectses
     */
    public void setSbiDistributionListsObjectses(Set sbiDistributionListsObjectses) {
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
   




}
