ALTER TABLE SBI_DATA_SOURCE ADD COLUMN MULTI_SCHEMA SMALLINT  DEFAULT 0 NOT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD COLUMN ATTR_SCHEMA VARCHAR DEFAULT NULL;
ALTER TABLE SBI_EXT_ROLES ADD COLUMN BUILD_QBE_QUERY BOOLEAN DEFAULT TRUE;
ALTER TABLE SBI_KPI_VALUE ADD COLUMN XML_DATA VARCHAR;