angular.module('cockpitModule').factory('cockpitModule_generalOptions',function(sbiModule_translate){
	return{
		fontSizeDimension:	[
								{
									label:"",
									value:''
								 },
								 {
									 label:"8px",
									 value:'8px'
								 },
								 {
									 label:"10px",
									 value:'10px'
								 },
								 {
									 label:"12px",
									 value:'12px'
								 },
								 {
									 label:"14px",
									 value:'14px'
								 },
								 {
									 label:"16px",
									 value:'16px'
								 },
								 {
									 label:"20px",
									 value:'20px'
								 },
								 {
									 label:"24px",
									 value:'24px'
								 }

						 	],
		textDecoration:		[
								{
									label:"",
									value:''
								 },
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.overline"),
									value:'overline'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.underline"),
									value:'underline'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontDecoration.lineThrough"),
									value:'line-through'
								}
							],
		fontWeight:			[
								{
									label:"",
									value:''
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.normal"),
									value:'normal'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.bold"),
									value:'bold'
								},
								{
									label:sbiModule_translate.load("sbi.cockpit.style.fontWeight.light"),
									value:'light'
								}
							],
	fontType:			[
	           			 {
	           				 label:"",
	           				 value:''
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.roboto"),
	           				 value:'roboto'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.arial"),
	           				 value:'arial'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.curierNew"),
	           				 value:'curier-new'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.tahoma"),
	           				 value:'tahoma'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.timesNewRoman"),
	           				 value:'times-new-roman'
	           			 },
	           			 {
	           				 label:sbiModule_translate.load("sbi.cockpit.style.font.verdana"),
	           				 value:'verdana'
	           			 }
	           			 ],
	aggregationFunctions:[
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.none"),
                        	   value:"NONE"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.sum"),
                        	   value:"SUM"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.avg"),
                        	   value:"AVG"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.max"),
                        	   value:"MAX"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.min"),
                        	   value:"MIN"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.count"),
                        	   value:"COUNT"
                           },
                           {
                        	   label:sbiModule_translate.load("sbi.qbe.selectgridpanel.aggfunc.name.countdistinct"),
                        	   value:"COUNT_DISTINCT"
                           },
                   ],
    textAlign:	[
					{
						label:"",
						value:''
					 },
					{
						label:sbiModule_translate.load("sbi.cockpit.style.textAlign.left"),
						value:'left'
					},
					{
						label:sbiModule_translate.load("sbi.cockpit.style.textAlign.right"),
						value:'right'
					},
					{
						label:sbiModule_translate.load("sbi.cockpit.style.textAlign.center"),
						value:'center'
					}
				],
    textVerticalAlign:	[
		{
			label:"",
			value:''
		 },
		{
			label:sbiModule_translate.load("sbi.cockpit.style.textVerticalAlign.top"),
			value:'top'
		},
		{
			label:sbiModule_translate.load("sbi.cockpit.style.textVerticalAlign.middle"),
			value:'middle'
		},
		{
			label:sbiModule_translate.load("sbi.cockpit.style.textVerticalAlign.bottom"),
			value:'bottom'
		}
	]
	}
});