/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.analiticalmodel.document.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;




/**
 * SbiObjState generated by hbm2java
 */
public class SbiObjState  extends SbiHibernateModel {

    // Fields    

     private SbiObjStateId id;
     private Date endDt;
     private String note;


    // Constructors

    /**
     * default constructor.
     */
    public SbiObjState() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiObjState(SbiObjStateId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiObjStateId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiObjStateId id) {
        this.id = id;
    }

    /**
     * Gets the end dt.
     * 
     * @return the end dt
     */
    public Date getEndDt() {
        return this.endDt;
    }
    
    /**
     * Sets the end dt.
     * 
     * @param endDt the new end dt
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * Gets the note.
     * 
     * @return the note
     */
    public String getNote() {
        return this.note;
    }
    
    /**
     * Sets the note.
     * 
     * @param note the new note
     */
    public void setNote(String note) {
        this.note = note;
    }



}