--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD RESOURCE_CODE VARCHAR2(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
CREATE UNIQUE INDEX UNIQUE_RES_CODE ON SBI_RESOURCES(RESOURCE_CODE);
ALTER TABLE SBI_RESOURCES MODIFY RESOURCE_CODE VARCHAR2(45) NOT NULL;

--Giulio 31/05/2010
CREATE SEQUENCE SBI_KPI_MODEL_ATTR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER
/

--Giulio 5/07/2010

create trigger TRG_SBI_KPI_MODEL_ATTR
  BEFORE INSERT
  on SBI_KPI_MODEL_ATTR
  REFERENCING OLD AS old NEW AS new
  for each row
  declare nuovo_id number;
begin
IF :new.KPI_MODEL_ATTR_ID IS NULL THEN
     select SBI_KPI_MODEL_ATTR_SEQ.nextval into nuovo_id from dual;
     :new.KPI_MODEL_ATTR_ID:=nuovo_id;
END IF;
end;
/
