--- START ---
-- 2020-09-11 Adding Portuguese language
update SBI_CONFIG set VALUE_CHECK = CONCAT(VALUE_CHECK, ',[pt,BR]') WHERE LABEL = 'SPAGOBI.LANGUAGE_SUPPORTED.LANGUAGES' and VALUE_CHECK not like '%[pt,BR]%';
commit;
--28/12/2020 Alberto Nale
ALTER TABLE SBI_DOSSIER_ACTIVITY ADD DOC bytea NULL;
ALTER TABLE SBI_DOSSIER_ACTIVITY ADD CONFIG varchar(4000) NULL;