-- 22/12/2020 Marco Balestri
-- CATALOG FUNCTION TABLES UPDATE

-- START

-- CLEAN old tables
DELETE FROM SBI_CATALOG_FUNCTION;
DELETE FROM SBI_FUNCTION_INPUT_VARIABLE;

-- DROP old tables
DROP TABLE SBI_FUNCTION_OUTPUT;
DROP TABLE SBI_FUNCTION_INPUT_DATASET;
DROP TABLE SBI_FUNCTION_INPUT_FILE;

-- ------------------------- TABLE sbi_catalog_function -------------------------
ALTER TABLE SBI_CATALOG_FUNCTION ADD (BENCHMARKS varchar2(4000), FAMILY varchar2(30), ONLINE_SCRIPT varchar2(4000), OFFLINE_SCRIPT_TRAIN varchar2(4000), OFFLINE_SCRIPT_USE varchar2(4000));
ALTER TABLE SBI_CATALOG_FUNCTION DROP (SCRIPT, URL, REMOTE);

-- ----------------------- TABLE sbi_function_input_column -----------------------
CREATE TABLE SBI_FUNCTION_INPUT_COLUMN AS SELECT * FROM SBI_FUNCTION_INPUT_VARIABLE WHERE 1=0;
  
ALTER TABLE SBI_FUNCTION_INPUT_COLUMN RENAME COLUMN VAR_NAME TO COL_NAME;
ALTER TABLE SBI_FUNCTION_INPUT_COLUMN RENAME COLUMN VAR_VALUE TO COL_TYPE;
ALTER TABLE SBI_FUNCTION_INPUT_COLUMN MODIFY  COL_NAME varchar2(100);
ALTER TABLE SBI_FUNCTION_INPUT_COLUMN MODIFY COL_TYPE varchar2(100);

-- ---------------------- TABLE sbi_function_input_variable ---------------------
ALTER TABLE SBI_FUNCTION_INPUT_VARIABLE ADD VAR_TYPE varchar2(100);

-- ---------------------- TABLE sbi_function_output_column -----------------------
CREATE TABLE SBI_FUNCTION_OUTPUT_COLUMN AS SELECT * FROM SBI_FUNCTION_INPUT_COLUMN WHERE 1=0;

ALTER TABLE SBI_FUNCTION_OUTPUT_COLUMN ADD COL_FIELD_TYPE varchar2(100);

-- --------------------------- TABLE sbi_obj_function ---------------------------
CREATE TABLE SBI_OBJ_FUNCTION AS SELECT * FROM SBI_OBJ_DATA_SET WHERE 1=0;

ALTER TABLE SBI_OBJ_FUNCTION DROP COLUMN IS_DETAIL;
ALTER TABLE SBI_OBJ_FUNCTION RENAME COLUMN BIOBJ_DS_ID TO BIOBJ_FUNCTION_ID;
ALTER TABLE SBI_OBJ_FUNCTION RENAME COLUMN DS_ID TO FUNCTION_ID;
ALTER TABLE SBI_OBJ_FUNCTION MODIFY BIOBJ_FUNCTION_ID integer;
ALTER TABLE SBI_OBJ_FUNCTION MODIFY FUNCTION_ID integer;

ALTER TABLE SBI_OBJ_FUNCTION ADD FOREIGN KEY (BIOBJ_ID) REFERENCES SBI_OBJECTS(BIOBJ_ID);
ALTER TABLE SBI_OBJ_FUNCTION ADD FOREIGN KEY (FUNCTION_ID) REFERENCES SBI_CATALOG_FUNCTION(FUNCTION_ID);

-- END