INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('groovy','Groovy','SCRIPT_TYPE','Script Type','Script Type')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('rhino-nonjdk','Javascript','SCRIPT_TYPE','Script Type','Script Type')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('ejs','Embedded Javascript','SCRIPT_TYPE','Script Type','Script Type')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('File','SbiFileDataSet','DATA_SET_TYPE','Data Set Type','SbiFileDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('Query','SbiQueryDataSet','DATA_SET_TYPE','Data Set Type','SbiQueryDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('Java Class','SbiJClassDataSet','DATA_SET_TYPE','Data Set Type','SbiJClassDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('Web Service','SbiWSDataSet','DATA_SET_TYPE','Data Set Type','SbiWSDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('Script','SbiScriptDataSet','DATA_SET_TYPE','Data Set Type','SbiScriptDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('Qbe','SbiQbeDataSet','DATA_SET_TYPE','Data Set Type','SbiQbeDataSet')
/
INSERT into SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) values ('WORKSHEET','sbidomains.nm.worksheet','BIOBJ_TYPE','BI Object types','sbidomains.ds.worksheet')
/
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('DEVELOPMENT', 'sbidomains.permissiononfolder.nm.dev','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.dev')
/
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('TEST', 'sbidomains.permissiononfolder.nm.test','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.test')
/
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('EXECUTION', 'sbidomains.permissiononfolder.nm.execute','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.execute')
/
INSERT INTO SBI_DOMAINS (VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS) VALUES ('CREATION', 'sbidomains.permissiononfolder.nm.create','PERMISSION_ON_FOLDER','Permission on folder','sbidomains.permissiononfolder.ds.create')
/
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'DEVELOPMENT' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'DEVELOPMENT' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'DEV' AND DOMAIN_CD = 'STATE')
/
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'TEST' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'TEST' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'TEST' AND DOMAIN_CD = 'STATE')
/
UPDATE SBI_FUNC_ROLE SET STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'EXECUTION' AND DOMAIN_CD = 'PERMISSION_ON_FOLDER'), STATE_CD = 'EXECUTION' WHERE STATE_ID = (SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'REL' AND DOMAIN_CD = 'STATE')
/
INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('DomainManagement', 'DomainManagement')
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='DomainManagement'))
/
INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('ConfigManagement', 'ConfigManagement')
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='ConfigManagement'))
/
INSERT INTO SBI_USER_FUNC (NAME, DESCRIPTION) VALUES ('UserSaveDocumentFunctionality', 'UserSaveDocumentFunctionality')
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'ADMIN'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'))
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'USER'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'))
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'DEV_ROLE'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'))
/
INSERT INTO SBI_ROLE_TYPE_USER_FUNC values((SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ROLE_TYPE' AND VALUE_CD = 'TEST_ROLE'), (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME='UserSaveDocumentFunctionality'))
/
INSERT INTO SBI_ENGINES (NAME, ENCRYPT, LABEL,MAIN_URL, DRIVER_NM, ENGINE_TYPE,BIOBJ_TYPE,USE_DATASOURCE,USE_DATASET) VALUES 
 ('Worksheet Engine', 0, 'WorksheetEngine','/SpagoBIQbeEngine/servlet/AdapterHTTP','it.eng.spagobi.engines.drivers.worksheet.WorksheetDriver',(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'ENGINE_TYPE' AND VALUE_CD = 'EXT'),(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'BIOBJ_TYPE' AND VALUE_CD = 'WORKSHEET'),1,0)
 /

CREATE TABLE SBI_DATA_SET_HISTORY (
	DS_H_ID 	   INTEGER NOT NULL,
	DS_ID 		   INTEGER NOT NULL,
	ACTIVE		   SMALLINT NOT NULL,
	VERSION_NUM	   INTEGER NOT NULL,
	OBJECT_TYPE    VARCHAR2(50),
	DS_METADATA    VARCHAR2(2000),
	PARAMS         VARCHAR2(1000),
	CATEGORY_ID    INTEGER,
    FILE_NAME	   VARCHAR2(300),
    QUERY   	   CLOB,
    DATA_SOURCE_ID INTEGER,
    ADRESS   	   VARCHAR2(250),
    OPERATION      VARCHAR2(50),
    JCLASS_NAME    VARCHAR2(100),
    LANGUAGE_SCRIPT VARCHAR2(50),
	SCRIPT   	   CLOB,
	JSON_QUERY     CLOB,
	DATAMARTS	   VARCHAR2(400),
    TRANSFORMER_ID INTEGER,
    PIVOT_COLUMN   VARCHAR2(50),
	PIVOT_ROW      VARCHAR2(50),
	PIVOT_VALUE    VARCHAR2(50),
	NUM_ROWS	   SMALLINT,	
	USER_IN              VARCHAR2(100) NOT NULL,
	TIME_IN              TIMESTAMP NOT NULL,
	META_VERSION         VARCHAR2(100),
	SBI_VERSION_IN       VARCHAR2(10),
    PRIMARY KEY (DS_H_ID)
)
/

ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_T  FOREIGN KEY  ( TRANSFORMER_ID ) REFERENCES SBI_DOMAINS ( VALUE_ID ) ON DELETE CASCADE
/
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_CAT  FOREIGN KEY  (CATEGORY_ID) REFERENCES SBI_DOMAINS (VALUE_ID) ON DELETE CASCADE 
/
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_DS  FOREIGN KEY  ( DATA_SOURCE_ID ) REFERENCES SBI_DATA_SOURCE ( DS_ID ) ON DELETE CASCADE
/
ALTER TABLE SBI_DATA_SET_HISTORY ADD CONSTRAINT FK_SBI_DATA_SET_DS2  FOREIGN KEY  (DS_ID) REFERENCES SBI_DATA_SET (DS_ID) ON DELETE CASCADE
/

INSERT INTO SBI_DATA_SET_HISTORY
(DS_H_ID, DS_ID,ACTIVE,VERSION_NUM,FILE_NAME,QUERY,JCLASS_NAME,SCRIPT,PARAMS,DS_METADATA
	,DATA_SOURCE_ID,OBJECT_TYPE,OPERATION,TRANSFORMER_ID,PIVOT_COLUMN,PIVOT_ROW
	,PIVOT_VALUE,NUM_ROWS,LANGUAGE_SCRIPT,USER_IN, TIME_IN)
SELECT DS_ID, DS_ID,1 ACTIVE,1 VERSION_NUM,FILE_NAME,QUERY,JCLASS_NAME,SCRIPT,PARAMS,DS_METADATA,DATA_SOURCE_ID
,OBJECT_TYPE,OPERATION,TRANSFORMER_ID,PIVOT_COLUMN,PIVOT_ROW,PIVOT_VALUE,NUM_ROWS,LANGUAGE_SCRIPT
,'biadmin' USER_IN, CURRENT_TIMESTAMP TIME_IN
FROM SBI_DATA_SET
/

commit
/

--Drop all SBI_DATA_SET foreign keys
ALTER TABLE SBI_DATA_SET DROP CONSTRAINT ( SELECT c.constraint_name
  FROM user_constraints c, user_cons_columns cc
 WHERE     c.constraint_name = cc.constraint_name
       AND c.table_name = 'SBI_DATA_SET'
       AND c.constraint_type = 'R'
       AND cc.column_name = 'TRANSFORMER_ID' )
/

ALTER TABLE SBI_DATA_SET DROP COLUMN EXECUTOR_CLASS
/
ALTER TABLE SBI_DATA_SET DROP COLUMN FILE_NAME
/
ALTER TABLE SBI_DATA_SET DROP COLUMN QUERY
/
ALTER TABLE SBI_DATA_SET DROP COLUMN JCLASS_NAME
/
ALTER TABLE SBI_DATA_SET DROP COLUMN SCRIPT
/
ALTER TABLE SBI_DATA_SET DROP COLUMN PARAMS
/
ALTER TABLE SBI_DATA_SET DROP COLUMN DS_METADATA
/
ALTER TABLE SBI_DATA_SET DROP COLUMN DATA_SOURCE_ID
/
ALTER TABLE SBI_DATA_SET DROP COLUMN OBJECT_TYPE
/
ALTER TABLE SBI_DATA_SET DROP COLUMN OPERATION
/
ALTER TABLE SBI_DATA_SET DROP COLUMN TRANSFORMER_ID
/
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_COLUMN
/
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_ROW
/
ALTER TABLE SBI_DATA_SET DROP COLUMN PIVOT_VALUE
/
ALTER TABLE SBI_DATA_SET DROP COLUMN NUM_ROWS
/
ALTER TABLE SBI_DATA_SET DROP COLUMN LANGUAGE_SCRIPT
/
ALTER TABLE SBI_DATA_SET DROP COLUMN ADRESS
/

--UPDATE TECHNOLOGY FIELDS START---
ALTER TABLE SBI_DATA_SET ADD USER_IN VARCHAR2(100) DEFAULT 'biadmin'  NOT NULL;
ALTER TABLE SBI_DATA_SET ADD USER_UP VARCHAR2(100); 
ALTER TABLE SBI_DATA_SET ADD USER_DE VARCHAR2(100);
ALTER TABLE SBI_DATA_SET ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DATA_SET ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DATA_SET ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DATA_SET ADD SBI_VERSION_IN VARCHAR2(10); 
ALTER TABLE SBI_DATA_SET ADD SBI_VERSION_UP VARCHAR2(10); 
ALTER TABLE SBI_DATA_SET ADD SBI_VERSION_DE VARCHAR2(10); 
ALTER TABLE SBI_DATA_SET ADD META_VERSION VARCHAR2(100);
ALTER TABLE SBI_DATA_SET ADD ORGANIZATION VARCHAR2(20);

ALTER TABLE SBI_FUNCTIONS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_FUNCTIONS ADD USER_UP VARCHAR(100);
ALTER TABLE SBI_FUNCTIONS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_FUNCTIONS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_FUNCTIONS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_FUNCTIONS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_FUNCTIONS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_FUNCTIONS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_FUNCTIONS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_STATE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_STATE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_STATE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_STATE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_STATE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_STATE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_STATE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_PAR ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_PAR ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_PAR ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_PAR ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_PAR ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PAR ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PAR ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJECTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_VIEWPOINTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_VIEWPOINTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_VIEWPOINTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_VIEWPOINTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DATA_SOURCE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DATA_SOURCE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DATA_SOURCE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DATA_SOURCE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECT_TEMPLATES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_TEMPLATES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECT_NOTES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECT_NOTES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECT_NOTES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECT_NOTES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SUBOBJECTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SUBOBJECTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SUBOBJECTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SUBOBJECTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SNAPSHOTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SNAPSHOTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SNAPSHOTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SNAPSHOTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_FUNC_ROLE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_FUNC_ROLE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_FUNC_ROLE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_FUNC_ROLE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE_DET ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_PARUSE_DET ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE_DET ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE_DET ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE_DET ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_DET ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_DET ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE_CK ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_PARUSE_CK ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE_CK ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE_CK ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE_CK ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE_CK ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE_CK ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARUSE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_PARUSE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARUSE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARUSE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARUSE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARUSE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_SUBREPORTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_SUBREPORTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_SUBREPORTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SUBREPORTS ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_SUBREPORTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_SUBREPORTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_SUBREPORTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJECTS_RATING ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJECTS_RATING ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJECTS_RATING ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJECTS_RATING ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_PARAMETERS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_PARAMETERS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_PARAMETERS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARAMETERS ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_PARAMETERS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_PARAMETERS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_PARAMETERS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_PARUSE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD TIME_DE  TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_PARUSE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_PARUSE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_PARUSE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_FUNC ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_FUNC ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_FUNC ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_FUNC ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_CHECKS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_CHECKS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_CHECKS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_CHECKS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_CHECKS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_CHECKS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_CHECKS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_LOV ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_LOV ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_LOV ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_LOV ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_LOV ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_LOV ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_LOV ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_BINARY_CONTENTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_BINARY_CONTENTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_BINARY_CONTENTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOMAINS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DOMAINS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOMAINS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOMAINS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOMAINS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOMAINS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOMAINS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EXT_ROLES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_EXT_ROLES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_EXT_ROLES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EXT_ROLES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EXT_ROLES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EXT_ROLES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EXT_ROLES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER_FUNC ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_USER_FUNC ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER_FUNC ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER_FUNC ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER_FUNC ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER_FUNC ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER_FUNC ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ENGINES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ENGINES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ENGINES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ENGINES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ENGINES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ENGINES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ENGINES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EVENTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_EVENTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_EVENTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EVENTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EVENTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EVENTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EVENTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EVENTS_LOG ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EVENTS_LOG ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EVENTS_LOG ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EVENTS_LOG ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_REMEMBER_ME ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_REMEMBER_ME ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_REMEMBER_ME ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_REMEMBER_ME ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM_EVENT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM_EVENT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM_EVENT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM_EVENT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ALARM ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ALARM_CONTACT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ALARM_CONTACT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ALARM_CONTACT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ALARM_CONTACT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_ROLE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_ROLE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_ROLE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_ROLE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_ROLE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_ROLE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_ROLE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_REL ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_REL ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_REL ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_REL ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_REL ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_REL ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_REL ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_PERIODICITY ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_PERIODICITY ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_PERIODICITY ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INST_PERIOD ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INST_PERIOD ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INST_PERIOD ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_INSTANCE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_INSTANCE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_INSTANCE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_INSTANCE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_ERROR ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_ERROR ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_ERROR ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_ERROR ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_ERROR ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_ERROR ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_ERROR ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_DOCUMENTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_DOCUMENTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_DOCUMENTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_VALUE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_VALUE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_VALUE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_VALUE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_VALUE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_VALUE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_VALUE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MEASURE_UNIT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MEASURE_UNIT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MEASURE_UNIT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MEASURE_UNIT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL_KPI ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GOAL_KPI ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL_KPI ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL_KPI ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL_KPI ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL_KPI ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL_KPI ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL_HIERARCHY ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL_HIERARCHY ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL_HIERARCHY ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GOAL ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GOAL ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GOAL ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GOAL ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GOAL ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GOAL ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_RESOURCES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_RESOURCES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_RESOURCES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_RESOURCES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_RESOURCES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_RESOURCES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_RESOURCES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_RESOURCES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL_INST ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL_INST ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL_INST ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_KPI_MODEL ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_KPI_MODEL ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_KPI_MODEL ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_KPI_MODEL ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_KPI_MODEL ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_KPI_MODEL ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ORG_UNIT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_GRANT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_HIERARCHIES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ORG_UNIT_NODES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ORG_UNIT_NODES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ORG_UNIT_NODES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_THRESHOLD ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_THRESHOLD ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_THRESHOLD ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_THRESHOLD_VALUE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_THRESHOLD_VALUE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_THRESHOLD_VALUE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_FEATURES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_FEATURES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_FEATURES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_FEATURES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_MAP_FEATURES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAP_FEATURES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_GEO_MAPS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_GEO_MAPS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_GEO_MAPS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_MAPS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_GEO_MAPS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_GEO_MAPS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_GEO_MAPS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_AUDIT ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_AUDIT ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_AUDIT ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_AUDIT ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_AUDIT ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_AUDIT ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_AUDIT ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_ATTRIBUTE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_ATTRIBUTE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_ATTRIBUTE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_ATTRIBUTE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_EXT_USER_ROLES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_EXT_USER_ROLES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_EXT_USER_ROLES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_USER ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_USER_ATTRIBUTES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_USER_ATTRIBUTES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_USER_ATTRIBUTES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST_USER ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_USER ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_USER ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_USER ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST_OBJECTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST_OBJECTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DIST_LIST ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DIST_LIST ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DIST_LIST ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DIST_LIST ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DIST_LIST ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DIST_LIST ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_METACONTENTS ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_METACONTENTS ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METACONTENTS ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_OBJ_METADATA ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_OBJ_METADATA ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_OBJ_METADATA ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_OBJ_METADATA ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_UDP_VALUE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_UDP_VALUE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_UDP_VALUE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_UDP_VALUE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_UDP_VALUE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_UDP_VALUE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_UDP_VALUE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_UDP ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_UDP ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_UDP ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_UDP ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_UDP ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_UDP ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_UDP ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MENU_ROLE ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_MENU_ROLE ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_MENU_ROLE ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MENU_ROLE ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MENU_ROLE ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MENU_ROLE ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MENU_ROLE ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_MENU ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_MENU ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_MENU ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MENU ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_MENU ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_MENU ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_MENU ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_PRES ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_PRES ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_PRES ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_PRES ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_TEMP ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_TEMP ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_TEMP ADD ORGANIZATION VARCHAR(20) ;

ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD USER_IN VARCHAR(100) DEFAULT 'biadmin' NOT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD USER_UP VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD USER_DE VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD TIME_IN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD TIME_UP TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD TIME_DE TIMESTAMP DEFAULT NULL;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD SBI_VERSION_IN VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD SBI_VERSION_UP VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD SBI_VERSION_DE VARCHAR(10) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD META_VERSION VARCHAR(100) ;
ALTER TABLE SBI_DOSSIER_BIN_TEMP ADD ORGANIZATION VARCHAR(20) ;
--UPDATE TECHNOLOGY FIELDS END---
DROP TABLE SBI_CONFIG;
CREATE TABLE SBI_CONFIG (
	ID 				INTEGER NOT NULL,
	LABEL			VARCHAR2(100) NOT NULL,
	NAME			VARCHAR2(100) NULL,
	DESCRIPTION 	VARCHAR2(500) NULL,
	IS_ACTIVE 		SMALLINT DEFAULT 1,
	VALUE_CHECK 	VARCHAR2(1000) NULL,
	VALUE_TYPE_ID 	INTEGER NULL,  
	USER_IN              VARCHAR2(100) NOT NULL,
    USER_UP              VARCHAR2(100),
    USER_DE              VARCHAR2(100),
    TIME_IN              TIMESTAMP NOT NULL,
    TIME_UP              TIMESTAMP DEFAULT NULL,    
    TIME_DE              TIMESTAMP DEFAULT NULL,
    SBI_VERSION_IN       VARCHAR2(10),
    SBI_VERSION_UP       VARCHAR2(10),
    SBI_VERSION_DE       VARCHAR2(10),
    META_VERSION         VARCHAR2(100),
    ORGANIZATION         VARCHAR2(20),
    CATEGORY             VARCHAR2(50),
 PRIMARY KEY (ID)
 )
/
--UPDATE HIBERNATE SEQUENCES START--
CREATE TABLE hibernate_sequences (
  SEQUENCE_NAME VARCHAR2(200) NOT NULL,
  NEXT_VAL INTEGER NOT NULL,
  PRIMARY KEY (SEQUENCE_NAME)
);

--DROP TRIGGER 
DROP TRIGGER TRG_SBI_CHECKS
/
DROP TRIGGER TRG_SBI_DOMAINS
/
DROP TRIGGER TRG_SBI_ENGINES
/
DROP TRIGGER TRG_SBI_EXT_ROLES
/
DROP TRIGGER TRG_SBI_FUNCTIONS
/
DROP TRIGGER TRG_SBI_LOV
/
DROP TRIGGER TRG_SBI_MENU
/
DROP TRIGGER TRG_SBI_OBJECTS
/
DROP TRIGGER TRG_SBI_PARAMETERS
/
DROP TRIGGER TRG_SBI_PARUSE
/
DROP TRIGGER TRG_SBI_OBJ_PAR
/
DROP TRIGGER TRG_SBI_EVENTS_LOG
/
DROP TRIGGER TRG_SBI_AUDIT
/
DROP TRIGGER TRG_SBI_ACTIVITY_MONITORING
/
DROP TRIGGER TRG_SBI_DIST_LIST_OBJECTS
/
DROP TRIGGER TRG_SBI_DIST_LIST_USER
/
DROP TRIGGER TRG_SBI_DIST_LIST
/
DROP TRIGGER TRG_SBI_DATA_SET
/
DROP TRIGGER TRG_SBI_REMEMBER_ME
/
DROP TRIGGER TRG_SBI_DOSSIER_BIN_TEMP
/
DROP TRIGGER TRG_SBI_DOSSIER_TEMP
/
DROP TRIGGER TRG_SBI_DOSSIER_PRES
/
DROP TRIGGER TRG_SBI_USER_FUNC
/
DROP TRIGGER TRG_SBI_SNAPSHOTS
/
DROP TRIGGER TRG_SBI_SUBOBJECTS
/
DROP TRIGGER TRG_SBI_OBJECT_NOTES
/
DROP TRIGGER TRG_SBI_OBJECT_TEMPLATES
/
DROP TRIGGER TRG_SBI_BINARY_CONTENTS
/
DROP TRIGGER TRG_SBI_DATA_SOURCE
/
DROP TRIGGER TRG_SBI_GEO_FEATURES
/
DROP TRIGGER TRG_SBI_GEO_MAPS
/
DROP TRIGGER TRG_SBI_KPI_INSTANCE_HISTORY
/
DROP TRIGGER TRG_SBI_KPI_INSTANCE
/
DROP TRIGGER TRG_SBI_KPI_MODEL_INST
/
DROP TRIGGER TRG_SBI_KPI_MODEL
/
DROP TRIGGER TRG_SBI_KPI_VALUE
/
DROP TRIGGER TRG_SBI_KPI
/
DROP TRIGGER TRG_SBI_KPI_INST_PERIOD
/
DROP TRIGGER TRG_SBI_KPI_MODEL_RESOURCES
/
DROP TRIGGER TRG_SBI_KPI_DOCUMENTS
/
DROP TRIGGER TRG_RESOURCES
/
DROP TRIGGER TRG_SBI_THRESHOLD
/
DROP TRIGGER TRG_SBI_THRESHOLD_VAULE
/
DROP TRIGGER TRG_SBI_KPI_PERIODICITY
/
DROP TRIGGER TRG_SBI_MEASURE_UNIT
/
DROP TRIGGER TRG_SBI_OBJ_METADATA
/
DROP TRIGGER TRG_SBI_OBJ_METACONTENTS
/
DROP TRIGGER TRG_SBI_CONFIG
/
DROP TRIGGER TRG_SBI_UDP
/
DROP TRIGGER TRG_SBI_UDP_VALUE
/
DROP TRIGGER TRG_SBI_GOAL
/
DROP TRIGGER TRG_SBI_GOAL_HIERARCHY
/
DROP TRIGGER TRG_SBI_GOAL_KPI
/ 

DROP SEQUENCE SBI_CHECKS_SEQ ;
DROP SEQUENCE SBI_DOMAINS_SEQ ;
DROP SEQUENCE SBI_ENGINES_SEQ ;
DROP SEQUENCE SBI_EXT_ROLES_SEQ ;
DROP SEQUENCE SBI_FUNCTIONS_SEQ ;
DROP SEQUENCE SBI_LOV_SEQ ;
DROP SEQUENCE SBI_OBJECTS_SEQ ;
DROP SEQUENCE SBI_PARAMETERS_SEQ ;
DROP SEQUENCE SBI_PARUSE_SEQ ;
DROP SEQUENCE SBI_OBJ_PAR_SEQ ;
DROP SEQUENCE SBI_EVENTS_LOG_SEQ ;
DROP SEQUENCE SBI_AUDIT_SEQ ;
DROP SEQUENCE SBI_ACTIVITY_SEQ ;
DROP SEQUENCE SBI_USER_FUNC_SEQ ;
DROP SEQUENCE SBI_REMEMBER_ME_SEQ ;
DROP SEQUENCE SBI_MENU_SEQ ;
DROP SEQUENCE SBI_BINARY_CONTENTS_SEQ ;
DROP SEQUENCE SBI_DATA_SET_SEQ ;
DROP SEQUENCE SBI_DATA_SOURCE_SEQ ;
DROP SEQUENCE SBI_DIST_LIST_SEQ ;
DROP SEQUENCE SBI_DIST_LIST_USER_SEQ ;
DROP SEQUENCE SBI_DIST_LIST_OBJECTS_SEQ ;
DROP SEQUENCE SBI_DOSSIER_BIN_TEMP_SEQ ;
DROP SEQUENCE SBI_DOSSIER_TEMP_SEQ ;
DROP SEQUENCE SBI_DOSSIER_PRES_SEQ ;
DROP SEQUENCE SBI_GEO_FEATURES_SEQ ;
DROP SEQUENCE SBI_GEO_MAPS_SEQ ;
DROP SEQUENCE SBI_OBJECT_NOTES_SEQ ;
DROP SEQUENCE SBI_OBJECT_TEMPLATES_SEQ ;
DROP SEQUENCE SBI_SNAPSHOTS_SEQ ;
DROP SEQUENCE SBI_SUBOBJECTS_SEQ ;
DROP SEQUENCE SBI_VIEWPOINTS_SEQ ;
DROP SEQUENCE SBI_KPI_INSTANCE_HISTORY_SEQ ;
DROP SEQUENCE SBI_KPI_INSTANCE_SEQ ;
DROP SEQUENCE SBI_KPI_MODEL_INST_SEQ ;
DROP SEQUENCE SBI_KPI_MODEL_SEQ ;
DROP SEQUENCE SBI_KPI_VALUE_SEQ ;
DROP SEQUENCE SBI_KPI_SEQ ;
DROP SEQUENCE SBI_KPI_INST_PERIOD_SEQ ;
DROP SEQUENCE SBI_KPI_MODEL_RESOURCES_SEQ ;
DROP SEQUENCE SBI_KPI_DOCUMENTS_SEQ ;
DROP SEQUENCE RESOURCES_SEQ ;
DROP SEQUENCE SBI_THRESHOLD_SEQ ;
DROP SEQUENCE SBI_THRESHOLD_VAULE_SEQ ;
DROP SEQUENCE SBI_KPI_PERIODICITY_SEQ ;
DROP SEQUENCE SBI_MEASURE_UNIT_SEQ ;
DROP SEQUENCE SBI_OBJ_METADATA_SEQ ;
DROP SEQUENCE SBI_OBJ_METACONTENTS_SEQ ;
DROP SEQUENCE SBI_CONFIG_SEQ ;
DROP SEQUENCE SBI_UDP_SEQ ;
DROP SEQUENCE SBI_UDP_VALUE_SEQ ;
DROP SEQUENCE SBI_KPI_ERROR_SEQ ;
DROP SEQUENCE SBI_GOAL_SEQ ;
DROP SEQUENCE SBI_GOAL_HIERARCHY_SEQ ;
DROP SEQUENCE SBI_GOAL_KPI_SEQ ;

INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(BIOBJ_ID)+1 FROM SBI_OBJECTS),1),'SBI_OBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(OBJ_NOTE_ID)+1 FROM SBI_OBJECT_NOTES),1) ,'SBI_OBJECT_NOTES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(OBJ_PAR_ID)+1 FROM SBI_OBJ_PAR),1) ,'SBI_OBJ_PAR');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(OBJ_TEMP_ID)+1 FROM SBI_OBJECT_TEMPLATES),1) ,'SBI_OBJECT_TEMPLATES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(SNAP_ID)+1 FROM SBI_SNAPSHOTS),1) ,'SBI_SNAPSHOTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(SUBOBJ_ID)+1 FROM SBI_SUBOBJECTS),1) ,'SBI_SUBOBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(VP_ID)+1 FROM SBI_VIEWPOINTS),1) ,'SBI_VIEWPOINTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(FUNCT_ID)+1 FROM SBI_FUNCTIONS),1) ,'SBI_FUNCTIONS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(PAR_ID)+1 FROM SBI_PARAMETERS),1) ,'SBI_PARAMETERS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(USE_ID)+1 FROM SBI_PARUSE),1) ,'SBI_PARUSE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(CHECK_ID)+1 FROM SBI_CHECKS),1) ,'SBI_CHECKS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(LOV_ID)+1 FROM SBI_LOV),1) ,'SBI_LOV');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_CONFIG),1) ,'SBI_CONFIG');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(BIN_ID)+1 FROM SBI_BINARY_CONTENTS),1) ,'SBI_BINARY_CONTENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(VALUE_ID)+1 FROM SBI_DOMAINS),1) ,'SBI_DOMAINS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(EXT_ROLE_ID)+1 FROM SBI_EXT_ROLES),1) ,'SBI_EXT_ROLES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(USER_FUNCT_ID)+1 FROM SBI_USER_FUNC),1) ,'SBI_USER_FUNC');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ENGINE_ID)+1 FROM SBI_ENGINES),1) ,'SBI_ENGINES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(BIN_ID)+1 FROM SBI_DOSSIER_BIN_TEMP),1) ,'SBI_DOSSIER_BIN_TEMP');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(PART_ID)+1 FROM SBI_DOSSIER_TEMP),1) ,'SBI_DOSSIER_TEMP');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(PRESENTATION_ID)+1 FROM SBI_DOSSIER_PRES),1) ,'SBI_DOSSIER_PRES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_EVENTS),1) ,'SBI_EVENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_EVENTS_LOG),1) ,'SBI_EVENTS_LOG');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_REMEMBER_ME),1) ,'SBI_REMEMBER_ME');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ALARM_ID)+1 FROM SBI_ALARM),1) ,'SBI_ALARM');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ALARM_CONTACT_ID)+1 FROM SBI_ALARM_CONTACT),1) ,'SBI_ALARM_CONTACT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ALARM_EVENT_ID)+1 FROM SBI_ALARM_EVENT),1) ,'SBI_ALARM_EVENT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_ID)+1 FROM SBI_KPI),1) ,'SBI_KPI');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_DOC)+1 FROM SBI_KPI_DOCUMENTS),1),'SBI_KPI_DOCUMENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_ERROR_ID)+1 FROM SBI_KPI_ERROR),1) ,'SBI_KPI_ERROR');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_INSTANCE)+1 FROM SBI_KPI_INSTANCE),1) ,'SBI_KPI_INSTANCE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_INSTANCE_HISTORY)+1 FROM SBI_KPI_INSTANCE_HISTORY) ,1),'SBI_KPI_INSTANCE_HISTORY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_INST_PERIOD_ID)+1 FROM SBI_KPI_INST_PERIOD),1) ,'SBI_KPI_INST_PERIOD');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_PERIODICITY)+1 FROM SBI_KPI_PERIODICITY),1) ,'SBI_KPI_PERIODICITY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_ROLE)+1 FROM SBI_KPI_ROLE) ,1),'SBI_KPI_ROLE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_KPI_INSTANCE_VALUE)+1 FROM SBI_KPI_VALUE),1) ,'SBI_KPI_VALUE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_MEASURE_UNIT)+1 FROM SBI_MEASURE_UNIT),1) ,'SBI_MEASURE_UNIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(GOAL_ID)+1 FROM SBI_GOAL),1) ,'SBI_GOAL');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(GOAL_HIERARCHY_ID)+1 FROM SBI_GOAL_HIERARCHY),1) ,'SBI_GOAL_HIERARCHY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(GOAL_KPI_ID)+1 FROM SBI_GOAL_KPI),1) ,'SBI_GOAL_KPI');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_MODEL_ID)+1 FROM SBI_KPI_MODEL) ,1),'SBI_KPI_MODEL');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_MODEL_INST)+1 FROM SBI_KPI_MODEL_INST),1) ,'SBI_KPI_MODEL_INST');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(KPI_MODEL_RESOURCES_ID)+1 FROM SBI_KPI_MODEL_RESOURCES),1) ,'SBI_KPI_MODEL_RESOURCES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(RESOURCE_ID)+1 FROM SBI_RESOURCES),1) ,'SBI_RESOURCES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT),1) ,'SBI_ORG_UNIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT_GRANT),1) ,'SBI_ORG_UNIT_GRANT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_ORG_UNIT_HIERARCHIES),1) ,'SBI_ORG_UNIT_HIERARCHIES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(NODE_ID)+1 FROM SBI_ORG_UNIT_NODES),1) ,'SBI_ORG_UNIT_NODES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(THRESHOLD_ID)+1 FROM SBI_THRESHOLD),1) ,'SBI_THRESHOLD');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID_THRESHOLD_VALUE)+1 FROM SBI_THRESHOLD_VALUE),1) ,'SBI_THRESHOLD_VALUE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(FEATURE_ID)+1 FROM SBI_GEO_FEATURES),1) ,'SBI_GEO_FEATURES');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(MAP_ID)+1 FROM SBI_GEO_MAPS),1) ,'SBI_GEO_MAPS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_AUDIT),1) ,'SBI_AUDIT');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ATTRIBUTE_ID)+1 FROM SBI_ATTRIBUTE),1) ,'SBI_ATTRIBUTE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(ID)+1 FROM SBI_USER) ,1),'SBI_USER');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(DS_ID)+1 FROM SBI_DATA_SET),1) ,'SBI_DATA_SET');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(DS_H_ID)+1 FROM SBI_DATA_SET_HISTORY),1) ,'SBI_DATA_SET_HISTORY');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(DS_ID)+1 FROM SBI_DATA_SOURCE),1) ,'SBI_DATA_SOURCE');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(DL_ID)+1 FROM SBI_DIST_LIST),1) ,'SBI_DIST_LIST');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(REL_ID)+1 FROM SBI_DIST_LIST_OBJECTS),1) ,'SBI_DIST_LIST_OBJECTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(DLU_ID)+1 FROM SBI_DIST_LIST_USER) ,1),'SBI_DIST_LIST_USER');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(OBJ_METACONTENT_ID)+1 FROM SBI_OBJ_METACONTENTS),1) ,'SBI_OBJ_METACONTENTS');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(OBJ_META_ID)+1 FROM SBI_OBJ_METADATA),1) ,'SBI_OBJ_METADATA');
INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(MENU_ID)+1 FROM SBI_MENU) ,1),'SBI_MENU');
--UPDATE HIBERNATE SEQUENCES END--
INSERT INTO  SBI_EXPORTERS (ENGINE_ID,DOMAIN_ID,DEFAULT_VALUE)values((SELECT ENGINE_ID FROM SBI_ENGINES WHERE LABEL='WorksheetEngine'),(SELECT VALUE_ID FROM SBI_DOMAINS WHERE DOMAIN_CD = 'EXPORT_TYPE' AND VALUE_CD = 'XLS'), 0);
ALTER TABLE SBI_ALARM_EVENT DROP CONSTRAINT SBI_ALARM_EVENT_1;
ALTER TABLE SBI_ALARM_EVENT ADD CONSTRAINT SBI_ALARM_EVENT_IBFK_1 FOREIGN KEY (ALARM_ID) REFERENCES SBI_ALARM (ALARM_ID);
--If this is not the correct name of your foreign key delete manually the foreign key related to the table SBI_OBJECTS
ALTER TABLE SBI_KPI_DOCUMENTS DROP CONSTRAINT SBI_KPI_DOCUMENTS_1;
ALTER TABLE SBI_KPI_DOCUMENTS  ADD CONSTRAINT FK_SBI_KPI_DOCUMENTS_1 FOREIGN KEY ( BIOBJ_ID ) REFERENCES  SBI_OBJECTS  ( BIOBJ_ID );