/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.kpi.goal.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 6-dic-2010 11.29.21 by Hibernate Tools 3.2.4.GA

/**
 * SbiGoalKpi generated by hbm2java
 */
public class SbiGoalKpi extends SbiHibernateModel {

	private int goalKpiId;
	private SbiGoalHierarchy sbiGoalHierarchy;
	private int kpiInstanceId;
	private double weight1;
	private double weight2;
	private double threshold1;
	private double threshold2;
	private int threshold1sign;
	private int threshold2sign;

	public SbiGoalKpi() {
	}

	public SbiGoalKpi(int goalKpiId, SbiGoalHierarchy sbiGoalHierarchy,
			int kpiInstanceId, double weight1, double weight2,
			double threshold1, double threshold2, int threshold1sign,
			int threshold2sign) {
		this.goalKpiId = goalKpiId;
		this.sbiGoalHierarchy = sbiGoalHierarchy;
		this.kpiInstanceId = kpiInstanceId;
		this.weight1 = weight1;
		this.weight2 = weight2;
		this.threshold1 = threshold1;
		this.threshold2 = threshold2;
		this.threshold1sign = threshold1sign;
		this.threshold2sign = threshold2sign;
	}

	public int getGoalKpiId() {
		return this.goalKpiId;
	}

	public void setGoalKpiId(int goalKpiId) {
		this.goalKpiId = goalKpiId;
	}

	public SbiGoalHierarchy getSbiGoalHierarchy() {
		return this.sbiGoalHierarchy;
	}

	public void setSbiGoalHierarchy(SbiGoalHierarchy sbiGoalHierarchy) {
		this.sbiGoalHierarchy = sbiGoalHierarchy;
	}

	public int getKpiInstanceId() {
		return this.kpiInstanceId;
	}

	public void setKpiInstanceId(int kpiInstanceId) {
		this.kpiInstanceId = kpiInstanceId;
	}

	public double getWeight1() {
		return this.weight1;
	}

	public void setWeight1(double weight1) {
		this.weight1 = weight1;
	}

	public double getWeight2() {
		return this.weight2;
	}

	public void setWeight2(double weight2) {
		this.weight2 = weight2;
	}

	public double getThreshold1() {
		return this.threshold1;
	}

	public void setThreshold1(double threshold1) {
		this.threshold1 = threshold1;
	}

	public double getThreshold2() {
		return this.threshold2;
	}

	public void setThreshold2(double threshold2) {
		this.threshold2 = threshold2;
	}

	public int getThreshold1sign() {
		return this.threshold1sign;
	}

	public void setThreshold1sign(int threshold1sign) {
		this.threshold1sign = threshold1sign;
	}

	public int getThreshold2sign() {
		return this.threshold2sign;
	}

	public void setThreshold2sign(int threshold2sign) {
		this.threshold2sign = threshold2sign;
	}

}
