-- for BLOB column is not possible to change the type, in order change the type is renamed the column, 
-- create new column with correct name, copy the value from olt to new column and remove the old column
ALTER TABLE SBI_META_MODELS_VERSIONS  RENAME COLUMN CONTENT TO CONTENT_BCK;	
ALTER TABLE SBI_META_MODELS_VERSIONS ADD CONTENT BLOB NULL;
UPDATE SBI_META_MODELS_VERSIONS SET CONTENT = CONTENT_BCK;
ALTER TABLE SBI_META_MODELS_VERSIONS DROP COLUMN CONTENT_BCK;

ALTER TABLE SBI_META_MODELS_VERSIONS ADD FILE_MODEL BLOB NULL;

ALTER TABLE SBI_OBJ_METACONTENTS ADD ADDITIONAL_INFO VARCHAR2(255) DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION  ADD OWNER VARCHAR(50) NOT NULL;
ALTER TABLE SBI_CATALOG_FUNCTION  ADD KEYWORDS VARCHAR(255) DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION ADD LABEL VARCHAR(50) NOT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION ADD CONSTRAINT UNIQUE_LABEL_ORG UNIQUE (LABEL,ORGANIZATION);

ALTER TABLE SBI_CATALOG_FUNCTION ADD TYPE VARCHAR(50) DEFAULT NULL;

ALTER TABLE SBI_DATA_SET DROP COLUMN IS_PUBLIC;

CREATE TABLE SBI_WHATIF_WORKFLOW(
	ID INTEGER,
    MODEL_ID INTEGER,
    USER_ID INTEGER,
    SEQUENCE INTEGER,
    STATE VARCHAR2(20),
    NOTES VARCHAR2(100),
    INFO VARCHAR2(100),
    USER_IN              VARCHAR2(100) NOT NULL,
    USER_UP VARCHAR2(100),
    USER_DE VARCHAR2(100),
    TIME_IN              TIMESTAMP NOT NULL,
    TIME_UP              TIMESTAMP DEFAULT NULL,    
    TIME_DE              TIMESTAMP DEFAULT NULL,
    SBI_VERSION_IN VARCHAR2(10),
    SBI_VERSION_UP VARCHAR2(10),
    SBI_VERSION_DE VARCHAR2(10),
    ORGANIZATION VARCHAR2(20),
    PRIMARY KEY (ID)
);

ALTER TABLE SBI_WHATIF_WORKFLOW 				ADD CONSTRAINT FK_SBI_MODEL_WORKFLOW			FOREIGN KEY (MODEL_ID) 			REFERENCES SBI_ARTIFACTS(ID)					ON DELETE CASCADE;
ALTER TABLE SBI_WHATIF_WORKFLOW 				ADD CONSTRAINT FK_SBI_USER_WORKFLOW			FOREIGN KEY (USER_ID) 				REFERENCES SBI_USER(ID) ON DELETE CASCADE;
