-- for BLOB column is not possible to change the type, in order change the type is renamed the column, 
-- create new column with correct name, copy the value from olt to new column and remove the old column
ALTER TABLE SBI_META_MODELS_VERSIONS  RENAME COLUMN CONTENT TO CONTENT_BCK;	
ALTER TABLE SBI_META_MODELS_VERSIONS ADD CONTENT BLOB NULL;
UPDATE SBI_META_MODELS_VERSIONS SET CONTENT = CONTENT_BCK;
ALTER TABLE SBI_META_MODELS_VERSIONS DROP COLUMN CONTENT_BCK;

ALTER TABLE SBI_META_MODELS_VERSIONS ADD FILE_MODEL BLOB NULL;

ALTER TABLE SBI_OBJ_METACONTENTS ADD ADDITIONAL_INFO VARCHAR2(255) DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION  ADD OWNER VARCHAR(50) NOT NULL;
ALTER TABLE SBI_CATALOG_FUNCTION  ADD KEYWORDS VARCHAR(255) DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION ADD LABEL VARCHAR(50) NOT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION ADD CONSTRAINT UNIQUE_LABEL_ORG UNIQUE (LABEL,ORGANIZATION);

ALTER TABLE SBI_CATALOG_FUNCTION ADD TYPE VARCHAR(50) DEFAULT NULL;

ALTER TABLE SBI_DATA_SET DROP COLUMN IS_PUBLIC;