package it.eng.spagobi.metadata.metadata;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SbiMetaTable generated by hbm2java
 */
public class SbiMetaTable extends SbiHibernateModel {

	private Integer tableId;
	@JsonIgnore
	private SbiMetaSource sbiMetaSource;
	private String name;
	private boolean deleted;
	@JsonIgnore
	private Set sbiMetaTableColumns = new HashSet(0);
	@JsonIgnore
	private Set sbiMetaJobTables = new HashSet(0);
	@JsonIgnore
	private Set sbiMetaTableBcs = new HashSet(0);

	public SbiMetaTable() {
	}

	public SbiMetaTable(SbiMetaSource sbiMetaSource, String name, boolean deleted) {
		this.sbiMetaSource = sbiMetaSource;
		this.name = name;
		this.deleted = deleted;
	}

	public SbiMetaTable(SbiMetaSource sbiMetaSource, String name, boolean deleted, Set sbiMetaTableColumns, Set sbiMetaObjTables, Set sbiMetaDsTables,
			Set sbiMetaJobTables, Set sbiMetaTableBcs) {
		this.sbiMetaSource = sbiMetaSource;
		this.name = name;
		this.deleted = deleted;
		this.sbiMetaTableColumns = sbiMetaTableColumns;
		this.sbiMetaJobTables = sbiMetaJobTables;
		this.sbiMetaTableBcs = sbiMetaTableBcs;
	}

	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	public SbiMetaSource getSbiMetaSource() {
		return this.sbiMetaSource;
	}

	public void setSbiMetaSource(SbiMetaSource sbiMetaSource) {
		this.sbiMetaSource = sbiMetaSource;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Set getSbiMetaTableColumns() {
		return this.sbiMetaTableColumns;
	}

	public void setSbiMetaTableColumns(Set sbiMetaTableColumns) {
		this.sbiMetaTableColumns = sbiMetaTableColumns;
	}

	public Set getSbiMetaJobTables() {
		return this.sbiMetaJobTables;
	}

	public void setSbiMetaJobTables(Set sbiMetaJobTables) {
		this.sbiMetaJobTables = sbiMetaJobTables;
	}

	public Set getSbiMetaTableBcs() {
		return this.sbiMetaTableBcs;
	}

	public void setSbiMetaTableBcs(Set sbiMetaTableBcs) {
		this.sbiMetaTableBcs = sbiMetaTableBcs;
	}

}
