package it.eng.spagobi.metadata.metadata;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.tools.catalogue.metadata.SbiMetaModel;

import java.util.Date;
import java.util.Set;

/**
 * SbiMetaBc generated by hbm2java
 */
public class SbiMetaBc extends SbiHibernateModel {

	private Integer bcId;
	private SbiMetaModel sbiMetaModel;
	private int tableId;
	private String name;
	private boolean deleted;
	private String userIn;
	private String userUp;
	private String userDe;
	private Date timeIn;
	private Date timeUp;
	private Date timeDe;
	private String sbiVersionIn;
	private String sbiVersionUp;
	private String sbiVersionDe;
	private String metaVersion;
	private String organization;

	// private Set sbiMetaDsBcs = new HashSet(0);
	// private Set sbiMetaTableBcs = new HashSet(0);
	// private Set sbiMetaBcAttributes = new HashSet(0);

	public SbiMetaBc() {
	}

	public SbiMetaBc(SbiMetaModel sbiMetaModel, int tableId, String name, boolean deleted, String userIn, Date timeIn) {
		this.sbiMetaModel = sbiMetaModel;
		this.tableId = tableId;
		this.name = name;
		this.deleted = deleted;
		this.userIn = userIn;
		this.timeIn = timeIn;
	}

	public SbiMetaBc(SbiMetaModel sbiMetaModel, int tableId, String name, boolean deleted, String userIn, String userUp, String userDe, Date timeIn,
			Date timeUp, Date timeDe, String sbiVersionIn, String sbiVersionUp, String sbiVersionDe, String metaVersion, String organization, Set sbiMetaDsBcs,
			Set sbiMetaTableBcs, Set sbiMetaBcAttributes) {
		this.sbiMetaModel = sbiMetaModel;
		this.tableId = tableId;
		this.name = name;
		this.deleted = deleted;
		this.userIn = userIn;
		this.userUp = userUp;
		this.userDe = userDe;
		this.timeIn = timeIn;
		this.timeUp = timeUp;
		this.timeDe = timeDe;
		this.sbiVersionIn = sbiVersionIn;
		this.sbiVersionUp = sbiVersionUp;
		this.sbiVersionDe = sbiVersionDe;
		this.metaVersion = metaVersion;
		this.organization = organization;
		// this.sbiMetaDsBcs = sbiMetaDsBcs;
		// this.sbiMetaTableBcs = sbiMetaTableBcs;
		// this.sbiMetaBcAttributes = sbiMetaBcAttributes;
	}

	public Integer getBcId() {
		return this.bcId;
	}

	public void setBcId(Integer bcId) {
		this.bcId = bcId;
	}

	public SbiMetaModel getSbiMetaModel() {
		return this.sbiMetaModel;
	}

	public void setSbiMetaModel(SbiMetaModel sbiMetaModel) {
		this.sbiMetaModel = sbiMetaModel;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getUserIn() {
		return this.userIn;
	}

	public void setUserIn(String userIn) {
		this.userIn = userIn;
	}

	public String getUserUp() {
		return this.userUp;
	}

	public void setUserUp(String userUp) {
		this.userUp = userUp;
	}

	public String getUserDe() {
		return this.userDe;
	}

	public void setUserDe(String userDe) {
		this.userDe = userDe;
	}

	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	public Date getTimeUp() {
		return this.timeUp;
	}

	public void setTimeUp(Date timeUp) {
		this.timeUp = timeUp;
	}

	public Date getTimeDe() {
		return this.timeDe;
	}

	public void setTimeDe(Date timeDe) {
		this.timeDe = timeDe;
	}

	public String getSbiVersionIn() {
		return this.sbiVersionIn;
	}

	public void setSbiVersionIn(String sbiVersionIn) {
		this.sbiVersionIn = sbiVersionIn;
	}

	public String getSbiVersionUp() {
		return this.sbiVersionUp;
	}

	public void setSbiVersionUp(String sbiVersionUp) {
		this.sbiVersionUp = sbiVersionUp;
	}

	public String getSbiVersionDe() {
		return this.sbiVersionDe;
	}

	public void setSbiVersionDe(String sbiVersionDe) {
		this.sbiVersionDe = sbiVersionDe;
	}

	public String getMetaVersion() {
		return this.metaVersion;
	}

	public void setMetaVersion(String metaVersion) {
		this.metaVersion = metaVersion;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	// public Set getSbiMetaDsBcs() {
	// return this.sbiMetaDsBcs;
	// }
	//
	// public void setSbiMetaDsBcs(Set sbiMetaDsBcs) {
	// this.sbiMetaDsBcs = sbiMetaDsBcs;
	// }
	//
	// public Set getSbiMetaTableBcs() {
	// return this.sbiMetaTableBcs;
	// }
	//
	// public void setSbiMetaTableBcs(Set sbiMetaTableBcs) {
	// this.sbiMetaTableBcs = sbiMetaTableBcs;
	// }
	//
	// public Set getSbiMetaBcAttributes() {
	// return this.sbiMetaBcAttributes;
	// }
	//
	// public void setSbiMetaBcAttributes(Set sbiMetaBcAttributes) {
	// this.sbiMetaBcAttributes = sbiMetaBcAttributes;
	// }

}
