package it.eng.spagobi.metadata.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

/**
 * SbiMetaDsTableId generated by hbm2java
 */
public class SbiMetaDsTableId extends SbiHibernateModel {

	private int dsId;
	private int tableId;

	public SbiMetaDsTableId() {
	}

	public SbiMetaDsTableId(int dsId, int tableId) {
		this.dsId = dsId;
		this.tableId = tableId;
	}

	public int getDsId() {
		return this.dsId;
	}

	public void setDsId(int dsId) {
		this.dsId = dsId;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiMetaDsTableId))
			return false;
		SbiMetaDsTableId castOther = (SbiMetaDsTableId) other;

		return (this.getDsId() == castOther.getDsId()) && (this.getTableId() == castOther.getTableId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDsId();
		result = 37 * result + this.getTableId();
		return result;
	}

}
