package it.eng.spagobi.metadata.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

/**
 * SbiMetaTableBcId generated by hbm2java
 */
public class SbiMetaTableBcId extends SbiHibernateModel {

	private int tableId;
	private int bcId;

	public SbiMetaTableBcId() {
	}

	public SbiMetaTableBcId(int tableId, int bcId) {
		this.tableId = tableId;
		this.bcId = bcId;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public int getBcId() {
		return this.bcId;
	}

	public void setBcId(int bcId) {
		this.bcId = bcId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiMetaTableBcId))
			return false;
		SbiMetaTableBcId castOther = (SbiMetaTableBcId) other;

		return (this.getTableId() == castOther.getTableId()) && (this.getBcId() == castOther.getBcId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTableId();
		result = 37 * result + this.getBcId();
		return result;
	}

}
