package it.eng.spagobi.metadata.metadata;

// Generated 13-apr-2016 14.55.30 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbiMetaSource generated by hbm2java
 */
public class SbiMetaSource extends SbiHibernateModel {

	private Integer sourceId;
	private String name;
	private String type;
	private String url;
	private String location;
	private String sourceSchema;
	private String sourceCatalogue;
	private String userIn;
	private String userUp;
	private String userDe;
	private Date timeIn;
	private Date timeUp;
	private Date timeDe;
	private String sbiVersionIn;
	private String sbiVersionUp;
	private String sbiVersionDe;
	private String metaVersion;
	private String organization;
	private Set sbiMetaJobSources = new HashSet(0);
	private Set sbiMetaTables = new HashSet(0);

	public SbiMetaSource() {
	}

	public SbiMetaSource(String name, String type, String userIn, Date timeIn) {
		this.name = name;
		this.type = type;
		this.userIn = userIn;
		this.timeIn = timeIn;
	}

	public SbiMetaSource(String name, String type, String url, String location, String sourceSchema, String sourceCatalogue, String userIn, String userUp,
			String userDe, Date timeIn, Date timeUp, Date timeDe, String sbiVersionIn, String sbiVersionUp, String sbiVersionDe, String metaVersion,
			String organization, Set sbiMetaJobSources, Set sbiMetaTables) {
		this.name = name;
		this.type = type;
		this.url = url;
		this.location = location;
		this.sourceSchema = sourceSchema;
		this.sourceCatalogue = sourceCatalogue;
		this.userIn = userIn;
		this.userUp = userUp;
		this.userDe = userDe;
		this.timeIn = timeIn;
		this.timeUp = timeUp;
		this.timeDe = timeDe;
		this.sbiVersionIn = sbiVersionIn;
		this.sbiVersionUp = sbiVersionUp;
		this.sbiVersionDe = sbiVersionDe;
		this.metaVersion = metaVersion;
		this.organization = organization;
		this.sbiMetaJobSources = sbiMetaJobSources;
		this.sbiMetaTables = sbiMetaTables;
	}

	public Integer getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSourceSchema() {
		return this.sourceSchema;
	}

	public void setSourceSchema(String sourceSchema) {
		this.sourceSchema = sourceSchema;
	}

	public String getSourceCatalogue() {
		return this.sourceCatalogue;
	}

	public void setSourceCatalogue(String sourceCatalogue) {
		this.sourceCatalogue = sourceCatalogue;
	}

	public String getUserIn() {
		return this.userIn;
	}

	public void setUserIn(String userIn) {
		this.userIn = userIn;
	}

	public String getUserUp() {
		return this.userUp;
	}

	public void setUserUp(String userUp) {
		this.userUp = userUp;
	}

	public String getUserDe() {
		return this.userDe;
	}

	public void setUserDe(String userDe) {
		this.userDe = userDe;
	}

	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	public Date getTimeUp() {
		return this.timeUp;
	}

	public void setTimeUp(Date timeUp) {
		this.timeUp = timeUp;
	}

	public Date getTimeDe() {
		return this.timeDe;
	}

	public void setTimeDe(Date timeDe) {
		this.timeDe = timeDe;
	}

	public String getSbiVersionIn() {
		return this.sbiVersionIn;
	}

	public void setSbiVersionIn(String sbiVersionIn) {
		this.sbiVersionIn = sbiVersionIn;
	}

	public String getSbiVersionUp() {
		return this.sbiVersionUp;
	}

	public void setSbiVersionUp(String sbiVersionUp) {
		this.sbiVersionUp = sbiVersionUp;
	}

	public String getSbiVersionDe() {
		return this.sbiVersionDe;
	}

	public void setSbiVersionDe(String sbiVersionDe) {
		this.sbiVersionDe = sbiVersionDe;
	}

	public String getMetaVersion() {
		return this.metaVersion;
	}

	public void setMetaVersion(String metaVersion) {
		this.metaVersion = metaVersion;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public Set getSbiMetaJobSources() {
		return this.sbiMetaJobSources;
	}

	public void setSbiMetaJobSources(Set sbiMetaJobSources) {
		this.sbiMetaJobSources = sbiMetaJobSources;
	}

	public Set getSbiMetaTables() {
		return this.sbiMetaTables;
	}

	public void setSbiMetaTables(Set sbiMetaTables) {
		this.sbiMetaTables = sbiMetaTables;
	}

}
