package it.eng.spagobi.metadata.metadata;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;

/**
 * SbiMetaDsTable generated by hbm2java
 */
public class SbiMetaDsTable extends SbiHibernateModel {

	private SbiMetaDsTableId id;
	private SbiMetaTable sbiMetaTable;

	public SbiMetaDsTable() {
	}

	public SbiMetaDsTable(SbiMetaDsTableId id, SbiMetaTable sbiMetaTable) {
		this.id = id;
		this.sbiMetaTable = sbiMetaTable;
	}

	public SbiMetaDsTable(SbiMetaDsTableId id, SbiMetaTable sbiMetaTable, String userIn, String userUp, String userDe, Date timeIn, Date timeUp, Date timeDe,
			String sbiVersionIn, String sbiVersionUp, String sbiVersionDe, String metaVersion) {
		this.id = id;
		this.sbiMetaTable = sbiMetaTable;
	}

	public SbiMetaDsTableId getId() {
		return this.id;
	}

	public void setId(SbiMetaDsTableId id) {
		this.id = id;
	}

	public SbiMetaTable getSbiMetaTable() {
		return this.sbiMetaTable;
	}

	public void setSbiMetaTable(SbiMetaTable sbiMetaTable) {
		this.sbiMetaTable = sbiMetaTable;
	}

}
