package it.eng.spagobi.metadata.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 3-mag-2016 9.36.43 by Hibernate Tools 3.4.0.CR1

/**
 * SbiMetaDsTableId generated by hbm2java
 */
public class SbiMetaDsTableId extends SbiHibernateModel {

	private int dsId;
	private int versionNum;
	private String organization;
	private int tableId;

	public SbiMetaDsTableId() {
	}

	public SbiMetaDsTableId(int dsId, int versionNum, String organization, int tableId) {
		this.dsId = dsId;
		this.versionNum = versionNum;
		this.organization = organization;
		this.tableId = tableId;
	}

	public int getDsId() {
		return this.dsId;
	}

	public void setDsId(int dsId) {
		this.dsId = dsId;
	}

	public int getVersionNum() {
		return this.versionNum;
	}

	public void setVersionNum(int versionNum) {
		this.versionNum = versionNum;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiMetaDsTableId))
			return false;
		SbiMetaDsTableId castOther = (SbiMetaDsTableId) other;

		return (this.getDsId() == castOther.getDsId())
				&& (this.getVersionNum() == castOther.getVersionNum())
				&& ((this.getOrganization() == castOther.getOrganization()) || (this.getOrganization() != null && castOther.getOrganization() != null && this
						.getOrganization().equals(castOther.getOrganization()))) && (this.getTableId() == castOther.getTableId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDsId();
		result = 37 * result + this.getVersionNum();
		result = 37 * result + (getOrganization() == null ? 0 : this.getOrganization().hashCode());
		result = 37 * result + this.getTableId();
		return result;
	}

}
