ALTER TABLE SBI_DATA_SOURCE ADD  ATTR_SCHEMA VARCHAR2(45) Default NULL;
ALTER TABLE SBI_DATA_SOURCE ADD MULTI_SCHEMA Number(38,0) Default 0;
ALTER TABLE SBI_EXT_ROLES ADD BUILD_QBE_QUERY Number(38,0) Default 1;
ALTER TABLE SBI_KPI_VALUE ADD XML_DATA CLOB;