CREATE TABLE SBI_HOMEPAGE (
	ID INT NOT NULL,
	TYPE VARCHAR(20) NOT NULL,
	DOCUMENT_ID INT DEFAULT NULL,
	IMAGE_URL VARCHAR(4000) DEFAULT NULL,
	STATIC_PAGE VARCHAR(255) DEFAULT NULL,
	HTML TEXT,
	CSS TEXT,
	MENU_PLACEHOLDERS TEXT,
	IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
	USER_IN VARCHAR(100) NOT NULL,
	USER_UP VARCHAR(100) DEFAULT NULL,
	USER_DE VARCHAR(100) DEFAULT NULL,
	TIME_IN TIMESTAMP NOT NULL,
	TIME_UP TIMESTAMP NULL DEFAULT NULL,
	TIME_DE TIMESTAMP NULL DEFAULT NULL,
	SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
	SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
	META_VERSION VARCHAR(100) DEFAULT NULL,
	ORGANIZATION VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_SBI_HOMEPAGE_1 FOREIGN KEY (DOCUMENT_ID) REFERENCES SBI_OBJECTS (BIOBJ_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) WITHOUT OIDS;

CREATE TABLE SBI_HOMEPAGE_ROLE (
	HOMEPAGE_ID INT NOT NULL,
	EXT_ROLE_ID INT NOT NULL,
	PRIMARY KEY (HOMEPAGE_ID,EXT_ROLE_ID),
	CONSTRAINT FK_SBI_HOMEPAGE_ROLE_1 FOREIGN KEY (HOMEPAGE_ID) REFERENCES SBI_HOMEPAGE (ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_SBI_HOMEPAGE_ROLE_2 FOREIGN KEY (EXT_ROLE_ID) REFERENCES SBI_EXT_ROLES (EXT_ROLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
) WITHOUT OIDS;

INSERT INTO hibernate_sequences(next_val, sequence_name)
VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM SBI_HOMEPAGE), 'SBI_HOMEPAGE');

COMMIT;
