/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiAttribute generated by hbm2java
 */
public class SbiAttribute extends SbiHibernateModel {

	private int attributeId;
	private String attributeName;
	private String description;
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiAttribute() {
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description, Set<SbiUserAttributes> sbiUserAttributeses) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

}
