/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.profiling.bean;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

/**
 * SbiUserAttributes generated by hbm2java
 */
public class SbiUserAttributes extends SbiHibernateModel {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((attributeValue == null) ? 0 : attributeValue.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SbiUserAttributes other = (SbiUserAttributes) obj;
		if (attributeValue == null) {
			if (other.attributeValue != null)
				return false;
		} else if (!attributeValue.equals(other.attributeValue))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	private SbiUserAttributesId id;
	private SbiUser sbiUser;
	private SbiAttribute sbiAttribute;
	private String attributeValue;

	public SbiUserAttributes() {
	}

	public SbiUserAttributes(SbiUserAttributesId id, SbiUser sbiUser,
			SbiAttribute sbiAttribute) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiAttribute = sbiAttribute;
	}

	public SbiUserAttributes(SbiUserAttributesId id, SbiUser sbiUser,
			SbiAttribute sbiAttribute, String attributeValue) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiAttribute = sbiAttribute;
		this.attributeValue = attributeValue;
	}

	public SbiUserAttributesId getId() {
		return this.id;
	}

	public void setId(SbiUserAttributesId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

	public SbiAttribute getSbiAttribute() {
		return this.sbiAttribute;
	}

	public void setSbiAttribute(SbiAttribute sbiAttribute) {
		this.sbiAttribute = sbiAttribute;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
