/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import it.eng.spagobi.commons.metadata.SbiExtRoles;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbiUser generated by hbm2java
 */
public class SbiUser extends SbiHibernateModel{

	private int id;
	private String userId;
	private String password;
	private String fullName;
	private Date dtPwdBegin;
	private Date dtPwdEnd;
	private Boolean flgPwdBlocked;
	private Date dtLastAccess;
	private Boolean isSuperadmin;
	
	private Set<SbiExtRoles> sbiExtUserRoleses = new HashSet<SbiExtRoles>(
			0);
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiUser() {
	}

	public SbiUser(int id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public SbiUser(int id, String userId, String password, String fullName,
			Date dtPwdBegin, Date dtPwdEnd, Boolean flgPwdBlocked,
			Date dtLastAccess,
			Set<SbiExtRoles> sbiExtUserRoleses,
			Set<SbiUserAttributes> sbiUserAttributeses, Boolean isSuperadmin) {
		this.id = id;
		this.userId = userId;
		this.password = password;
		this.fullName = fullName;
		this.dtPwdBegin = dtPwdBegin;
		this.dtPwdEnd = dtPwdEnd;
		this.flgPwdBlocked = flgPwdBlocked;
		this.dtLastAccess = dtLastAccess;
		this.sbiExtUserRoleses = sbiExtUserRoleses;
		this.sbiUserAttributeses = sbiUserAttributeses;
		this.isSuperadmin = isSuperadmin;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDtPwdBegin() {
		return this.dtPwdBegin;
	}

	public void setDtPwdBegin(Date dtPwdBegin) {
		this.dtPwdBegin = dtPwdBegin;
	}

	public Date getDtPwdEnd() {
		return this.dtPwdEnd;
	}

	public void setDtPwdEnd(Date dtPwdEnd) {
		this.dtPwdEnd = dtPwdEnd;
	}

	public Boolean getFlgPwdBlocked() {
		return this.flgPwdBlocked;
	}

	public void setFlgPwdBlocked(Boolean flgPwdBlocked) {
		this.flgPwdBlocked = flgPwdBlocked;
	}

	public Date getDtLastAccess() {
		return this.dtLastAccess;
	}

	public void setDtLastAccess(Date dtLastAccess) {
		this.dtLastAccess = dtLastAccess;
	}
	
	public Set<SbiExtRoles> getSbiExtUserRoleses() {
		return this.sbiExtUserRoleses;
	}

	public void setSbiExtUserRoleses(Set<SbiExtRoles> sbiExtUserRoleses) {
		this.sbiExtUserRoleses = sbiExtUserRoleses;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public Boolean getIsSuperadmin() {
		return this.isSuperadmin;
	}

	public void setIsSuperadmin(Boolean isSuperadmin) {
		this.isSuperadmin = isSuperadmin;
	}
}
