DELETE FROM SBI_CONFIG WHERE LABEL = 'internal.security.encript.password';

-- 2023-04-04 KNOWAGE_TM-568
CREATE TABLE SBI_VIEW_HIERARCHY (
    ID             CHAR(36)     NOT NULL,
    NAME           VARCHAR(200) NOT NULL,
    DESCR          TEXT             NULL,
    PROGR          INT          NOT NULL,

    PARENT_ID      CHAR(36) NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

CREATE TABLE SBI_VIEW (
    ID             CHAR(36)     NOT NULL,
    LABEL          VARCHAR(200) NOT NULL,
    NAME           VARCHAR(200) NOT NULL,
    DESCR          TEXT             NULL,
    DRIVERS        TEXT         NOT NULL,
    SETTINGS       TEXT         NOT NULL,

    BIOBJ_ID          INTEGER      NULL,
    VIEW_HIERARCHY_ID CHAR(36) NOT NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

CREATE TABLE SBI_VIEW_FOR_DOC (
    ID CHAR(36) NOT NULL,

    BIOBJ_ID          INTEGER  NOT NULL,
    VIEW_HIERARCHY_ID CHAR(36) NOT NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

ALTER TABLE SBI_VIEW_HIERARCHY ADD CONSTRAINT FK_SBI_VIEW_HIERARCHY_1 FOREIGN KEY (ORGANIZATION, PARENT_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE SBI_VIEW ADD CONSTRAINT FK_SBI_VIEW_1 FOREIGN KEY (ORGANIZATION, VIEW_HIERARCHY_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE SBI_VIEW ADD CONSTRAINT FK_SBI_VIEW_2 FOREIGN KEY (BIOBJ_ID)                        REFERENCES SBI_OBJECTS        (BIOBJ_ID)         ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE SBI_VIEW_FOR_DOC ADD CONSTRAINT FK_SBI_VIEW_FOR_DOC_1 FOREIGN KEY (ORGANIZATION, VIEW_HIERARCHY_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE SBI_VIEW_FOR_DOC ADD CONSTRAINT FK_SBI_VIEW_FOR_DOC_2 FOREIGN KEY (BIOBJ_ID)                        REFERENCES SBI_OBJECTS        (BIOBJ_ID)         ON DELETE RESTRICT ON UPDATE CASCADE;

-- 2023-05-29 KNOWAGE-7932
DELETE FROM SBI_EXPORTERS ;
DELETE FROM SBI_DOMAINS WHERE DOMAIN_CD = "EXPORT_TYPE" ;
DROP TABLE SBI_EXPORTERS ;

-- 2023-07-21: Dashboard themes
CREATE TABLE SBI_DASHBOARD_THEME (
	ID              CHAR(36)     NOT NULL,
	THEME_NAME      VARCHAR(255) NOT NULL,
	CONFIG          TEXT             NULL,
	USER_IN         VARCHAR(100) NOT NULL,
	USER_UP         VARCHAR(100),
	USER_DE         VARCHAR(100),
	TIME_IN         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
	TIME_UP         TIMESTAMP        NULL DEFAULT NULL,
	TIME_DE         TIMESTAMP        NULL DEFAULT NULL,
	SBI_VERSION_IN  VARCHAR(10),
	SBI_VERSION_UP  VARCHAR(10),
	SBI_VERSION_DE  VARCHAR(10),
	META_VERSION    VARCHAR(100),
	ORGANIZATION    VARCHAR(20),
	PRIMARY KEY (ID, ORGANIZATION)
);

-- 2023-09-18 : Add execution role to dossier run
ALTER TABLE SBI_PROGRESS_THREAD ADD EXECUTION_ROLE VARCHAR(100) NULL;
