/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.analiticalmodel.functionalitytree.metadata;

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Set;




/**
 * SbiFunctions generated by hbm2java
 */
public class SbiFunctions  extends SbiHibernateModel {

    // Fields    

     private Integer functId;
     private SbiDomains functType;
     private SbiFunctions parentFunct;
     private String functTypeCd;
     private String code;
     private String name;
     private String descr;
     private String path;
     private Set sbiObjFuncs;
     private Set sbiFuncRoles;
     private Integer prog;


    // Constructors

    /**
     * default constructor.
     */
    public SbiFunctions() {
    	this.functId = -1;
    }
    
    /**
     * constructor with id.
     * 
     * @param functId the funct id
     */
    public SbiFunctions(Integer functId) {
        this.functId = functId;
    }
   
    
    

    // Property accessors

    /**
     * Gets the funct id.
     * 
     * @return the funct id
     */
    public Integer getFunctId() {
        return this.functId;
    }
    
    /**
     * Sets the funct id.
     * 
     * @param functId the new funct id
     */
    public void setFunctId(Integer functId) {
        this.functId = functId;
    }


    /**
     * Gets the funct type cd.
     * 
     * @return the funct type cd
     */
    public String getFunctTypeCd() {
        return this.functTypeCd;
    }
    
    /**
     * Sets the funct type cd.
     * 
     * @param functTypeCd the new funct type cd
     */
    public void setFunctTypeCd(String functTypeCd) {
        this.functTypeCd = functTypeCd;
    }

    /**
     * Gets the code.
     * 
     * @return the code
     */
    public String getCode() {
        return this.code;
    }
    
    /**
     * Sets the code.
     * 
     * @param code the new code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }
    
    /**
     * Sets the name.
     * 
     * @param name the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the descr.
     * 
     * @return the descr
     */
    public String getDescr() {
        return this.descr;
    }
    
    /**
     * Sets the descr.
     * 
     * @param descr the new descr
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * Gets the path.
     * 
     * @return the path
     */
    public String getPath() {
        return this.path;
    }
    
    /**
     * Sets the path.
     * 
     * @param path the new path
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Gets the sbi obj funcs.
     * 
     * @return the sbi obj funcs
     */
    public Set getSbiObjFuncs() {
        return this.sbiObjFuncs;
    }
    
    /**
     * Sets the sbi obj funcs.
     * 
     * @param sbiObjFuncs the new sbi obj funcs
     */
    public void setSbiObjFuncs(Set sbiObjFuncs) {
        this.sbiObjFuncs = sbiObjFuncs;
    }

    /**
     * Gets the sbi func roles.
     * 
     * @return the sbi func roles
     */
    public Set getSbiFuncRoles() {
        return this.sbiFuncRoles;
    }
    
    /**
     * Sets the sbi func roles.
     * 
     * @param sbiFuncRoles the new sbi func roles
     */
    public void setSbiFuncRoles(Set sbiFuncRoles) {
        this.sbiFuncRoles = sbiFuncRoles;
    }



	/**
	 * Gets the funct type.
	 * 
	 * @return the funct type
	 */
	public SbiDomains getFunctType() {
		return functType;
	}
	
	/**
	 * Sets the funct type.
	 * 
	 * @param functType the new funct type
	 */
	public void setFunctType(SbiDomains functType) {
		this.functType = functType;
	}
	
	/**
	 * Gets the parent funct.
	 * 
	 * @return the parent funct
	 */
	public SbiFunctions getParentFunct() {
		return parentFunct;
	}
	
	/**
	 * Sets the parent funct.
	 * 
	 * @param parentFunct the new parent funct
	 */
	public void setParentFunct(SbiFunctions parentFunct) {
		this.parentFunct = parentFunct;
	}

	/**
	 * Gets the prog.
	 * 
	 * @return the prog
	 */
	public Integer getProg() {
		return prog;
	}

	/**
	 * Sets the prog.
	 * 
	 * @param prog the new prog
	 */
	public void setProg(Integer prog) {
		this.prog = prog;
	}
}