/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.tools.distributionlist.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3



/**
 * SbiDistributionListUser generated by hbm2java
 */

public class SbiDistributionListUser  extends SbiHibernateModel {


    // Fields    

     private Integer dluId;
     private SbiDistributionList sbiDistributionList;
     private String userId;
     private String EMail;


     /**
      * Instantiates a new sbi distribution list user.
      */
     public SbiDistributionListUser() {
     }

     
     /**
      * full constructor.
      * 
      * @param dluId the dlu id
      * @param sbiDistributionList the sbi distribution list
      * @param userId the user id
      * @param EMail the e mail
      */
     public SbiDistributionListUser(Integer dluId, SbiDistributionList sbiDistributionList, String userId, String EMail) {
         this.dluId = dluId;
         this.sbiDistributionList = sbiDistributionList;
         this.userId = userId;
         this.EMail = EMail;
     }
     

    
     // Property accessors

     /**
      * Gets the dlu id.
      * 
      * @return the dlu id
      */
     public Integer getDluId() {
         return this.dluId;
     }
     
     /**
      * Sets the dlu id.
      * 
      * @param dluId the new dlu id
      */
     public void setDluId(Integer dluId) {
         this.dluId = dluId;
     }

     /**
      * Gets the sbi distribution list.
      * 
      * @return the sbi distribution list
      */
     public SbiDistributionList getSbiDistributionList() {
         return this.sbiDistributionList;
     }
     
     /**
      * Sets the sbi distribution list.
      * 
      * @param sbiDistributionList the new sbi distribution list
      */
     public void setSbiDistributionList(SbiDistributionList sbiDistributionList) {
         this.sbiDistributionList = sbiDistributionList;
     }

     /**
      * Gets the user id.
      * 
      * @return the user id
      */
     public String getUserId() {
         return this.userId;
     }
     
     /**
      * Sets the user id.
      * 
      * @param userId the new user id
      */
     public void setUserId(String userId) {
         this.userId = userId;
     }

     /**
      * Gets the e mail.
      * 
      * @return the e mail
      */
     public String getEMail() {
         return this.EMail;
     }
     
     /**
      * Sets the e mail.
      * 
      * @param EMail the new e mail
      */
     public void setEMail(String EMail) {
         this.EMail = EMail;
     }
    
}
