ALTER TABLE SBI_OBJECTS ADD CONSTRAINT FK_SBI_OBJECTS_5 FOREIGN KEY (ENGINE_ID) REFERENCES SBI_ENGINES (ENGINE_ID) ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE SBI_META_MODELS_VERSIONS ALTER COLUMN CONTENT TYPE BYTEA;
ALTER TABLE SBI_META_MODELS_VERSIONS ALTER COLUMN CONTENT DROP NOT NULL;
ALTER TABLE SBI_META_MODELS_VERSIONS ADD COLUMN FILE_MODEL BYTEA NULL;

ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN ADDITIONAL_INFO VARCHAR(255) NULL;

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN OWNER 	VARCHAR(50) NOT NULL,
ADD COLUMN KEYWORDS VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN LABEL VARCHAR(50) NOT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION
ADD CONSTRAINT UNIQUE_LABEL_ORG UNIQUE (LABEL,ORGANIZATION);

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN TYPE VARCHAR(50) NULL DEFAULT NULL;



ALTER TABLE SBI_DATA_SET DROP COLUMN IS_PUBLIC;