ALTER TABLE SBI_META_MODELS_VERSIONS ALTER COLUMN CONTENT CONTENT MEDIUMBLOB NULL;
ALTER TABLE SBI_META_MODELS_VERSIONS ADD COLUMN FILE_MODEL MEDIUMBLOB NULL AFTER NAME;

ALTER TABLE SBI_OBJ_METACONTENTS ADD COLUMN ADDITIONAL_INFO VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN OWNER 	VARCHAR(50) NOT NULL AFTER ORGANIZATION,
ADD COLUMN KEYWORDS VARCHAR(255) NULL DEFAULT NULL AFTER OWNER;

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN LABEL VARCHAR(50) NOT NULL AFTER KEYWORDS;

ALTER TABLE SBI_CATALOG_FUNCTION
ADD CONSTRAINT UNIQUE_LABEL_ORG UNIQUE (LABEL,ORGANIZATION);

ALTER TABLE SBI_CATALOG_FUNCTION 
ADD COLUMN TYPE VARCHAR(50) NULL DEFAULT NULL AFTER LABEL;   



ALTER TABLE SBI_DATA_SET DROP COLUMN IS_PUBLIC;