ALTER TABLE SBI_KPI_KPI CHANGE COLUMN DEFINITION DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_RULE CHANGE COLUMN DEFINITION DEFINITION VARCHAR(4000) NOT NULL;
ALTER TABLE SBI_KPI_VALUE CHANGE COLUMN LOGICAL_KEY LOGICAL_KEY VARCHAR(4000) NOT NULL;