DROP TABLE `TWITTER_SENTIMENT`;

DROP TABLE `TWITTER_SEARCH_SCHEDULER`;

DROP TABLE `TWITTER_MONITOR_SCHEDULER`;

DROP TABLE `TWITTER_LINK_TO_MONITOR_CATEGORY`;

DROP TABLE `TWITTER_LINKS_TO_MONITOR`;

DROP TABLE `TWITTER_ACCOUNTS_TO_MONITOR`;

DROP TABLE `TWITTER_DATA`;

DROP TABLE `TWITTER_USERS`;

DROP TABLE `TWITTER_SEARCH`;