/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.commons.metadata;

// Generated 2-dic-2013 14.44.44 by Hibernate Tools 3.4.0.CR1

/**
 * SbiAuthorizationsRolesId generated by hbm2java
 */
public class SbiAuthorizationsRolesId implements java.io.Serializable {

	private int authorizationId;
	private int roleId;

	public SbiAuthorizationsRolesId() {
	}

	public SbiAuthorizationsRolesId(int authorizationId, int roleId) {
		this.authorizationId = authorizationId;
		this.roleId = roleId;
	}

	public int getAuthorizationId() {
		return this.authorizationId;
	}

	public void setAuthorizationId(int authorizationId) {
		this.authorizationId = authorizationId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiAuthorizationsRolesId))
			return false;
		SbiAuthorizationsRolesId castOther = (SbiAuthorizationsRolesId) other;

		return (this.getAuthorizationId() == castOther.getAuthorizationId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAuthorizationId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
