/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.commons.metadata;

// Generated 20-nov-2013 15.29.05 by Hibernate Tools 3.4.0.CR1

/**
 * SbiOrganizationDatasourceId generated by hbm2java
 */
public class SbiOrganizationDatasourceId implements java.io.Serializable {

	private int datasourceId;
	private int organizationId;

	public SbiOrganizationDatasourceId() {
	}

	public SbiOrganizationDatasourceId(int datasourceId, int organizationId) {
		this.datasourceId = datasourceId;
		this.organizationId = organizationId;
	}

	public int getDatasourceId() {
		return this.datasourceId;
	}

	public void setDatasourceId(int datasourceId) {
		this.datasourceId = datasourceId;
	}

	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiOrganizationDatasourceId))
			return false;
		SbiOrganizationDatasourceId castOther = (SbiOrganizationDatasourceId) other;

		return (this.getDatasourceId() == castOther.getDatasourceId())
				&& (this.getOrganizationId() == castOther.getOrganizationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDatasourceId();
		result = 37 * result + this.getOrganizationId();
		return result;
	}

}
