package it.eng.spagobi.commons.metadata;

// Generated 20-nov-2013 15.29.05 by Hibernate Tools 3.4.0.CR1

/**
 * SbiProductTypeEngineId generated by hbm2java
 */
public class SbiProductTypeEngineId implements java.io.Serializable {

	private int engineId;
	private int productTypeId;

	public SbiProductTypeEngineId() {
	}

	public SbiProductTypeEngineId(int engineId, int productTypeId) {
		this.engineId = engineId;
		this.productTypeId = productTypeId;
	}

	public int getEngineId() {
		return this.engineId;
	}

	public void setEngineId(int engineId) {
		this.engineId = engineId;
	}

	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiProductTypeEngineId))
			return false;
		SbiProductTypeEngineId castOther = (SbiProductTypeEngineId) other;

		return (this.getEngineId() == castOther.getEngineId()) && (this.getProductTypeId() == castOther.getProductTypeId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEngineId();
		result = 37 * result + this.getProductTypeId();
		return result;
	}

}
