DELETE FROM SBI_CONFIG WHERE LABEL = 'internal.security.encript.password';

-- 2023-04-04 KNOWAGE_TM-568
CREATE TABLE SBI_VIEW_HIERARCHY (
	ID             CHAR(36)     NOT NULL,
	NAME           VARCHAR(200) NOT NULL,
	DESCR          TEXT             NULL,
	PROGR          INT          NOT NULL,

	PARENT_ID      CHAR(36) NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

ALTER TABLE SBI_VIEW_HIERARCHY ADD CONSTRAINT FK_SBI_VIEW_HIERARCHY_1 FOREIGN KEY (ORGANIZATION, PARENT_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE SBI_VIEW (
	ID             CHAR(36)     NOT NULL,
	LABEL          VARCHAR(200) NOT NULL,
	NAME           VARCHAR(200) NOT NULL,
	DESCR          TEXT             NULL,
    DRIVERS        TEXT         NOT NULL,
    SETTINGS       TEXT         NOT NULL,

    BIOBJ_ID          INTEGER      NULL,
	VIEW_HIERARCHY_ID CHAR(36) NOT NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

ALTER TABLE SBI_VIEW ADD CONSTRAINT FK_SBI_VIEW_1 FOREIGN KEY (ORGANIZATION, VIEW_HIERARCHY_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE SBI_VIEW ADD CONSTRAINT FK_SBI_VIEW_2 FOREIGN KEY (BIOBJ_ID)                        REFERENCES SBI_OBJECTS        (BIOBJ_ID)         ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE SBI_VIEW_FOR_DOC (
	ID CHAR(36) NOT NULL,

    BIOBJ_ID          INTEGER  NOT NULL,
	VIEW_HIERARCHY_ID CHAR(36) NOT NULL,

    USER_IN        VARCHAR(100) NOT NULL,
    USER_UP        VARCHAR(100),
    USER_DE        VARCHAR(100),
    TIME_IN        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP        TIMESTAMP        NULL DEFAULT NULL,
    TIME_DE        TIMESTAMP        NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION   VARCHAR(100),
    ORGANIZATION   VARCHAR(20),
    PRIMARY KEY (ORGANIZATION, ID)
);

ALTER TABLE SBI_VIEW_FOR_DOC ADD CONSTRAINT FK_SBI_VIEW_FOR_DOC_1 FOREIGN KEY (ORGANIZATION, VIEW_HIERARCHY_ID) REFERENCES SBI_VIEW_HIERARCHY (ORGANIZATION, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE SBI_VIEW_FOR_DOC ADD CONSTRAINT FK_SBI_VIEW_FOR_DOC_2 FOREIGN KEY (BIOBJ_ID)                        REFERENCES SBI_OBJECTS        (BIOBJ_ID)         ON DELETE RESTRICT ON UPDATE CASCADE;

-- 2023-05-29 KNOWAGE-7932
DROP PROCEDURE IF EXISTS MIGRATE_EXPORTERS_TO_SBI_CONFIG ;

DELIMITER //

CREATE OR REPLACE PROCEDURE MIGRATE_EXPORTERS_TO_SBI_CONFIG()
BEGIN
	DECLARE DONE          INT DEFAULT FALSE;
	DECLARE CURR_VALUE_CD VARCHAR(100) ;
	DECLARE CURR_LABEL    VARCHAR( 40) ;
	
	DECLARE VALUE_FOR_KNOWAGEBIRTREPORTENG VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGECHARTENGINE   VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGECOCKPITENGINE VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGEJASPERREPORTE VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGEKPIENGINE     VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGENETWORKENGINE VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGEOLAPENGINE    VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGEQBEENGINE     VARCHAR(1000) DEFAULT "";
	DECLARE VALUE_FOR_KNOWAGEWHATIFENGINE  VARCHAR(1000) DEFAULT "";

	DECLARE CUR CURSOR FOR SELECT sd.VALUE_CD, se2.LABEL FROM sbi_exporters se INNER JOIN sbi_domains sd ON se.DOMAIN_ID = sd.VALUE_ID INNER JOIN sbi_engines se2 ON se.ENGINE_ID = se2.ENGINE_ID ORDER BY se2.name, sd.VALUE_CD, se.DEFAULT_VALUE DESC ;

	DECLARE
		CONTINUE HANDLER FOR NOT FOUND
	SET
		DONE = TRUE;

	OPEN CUR ;

	EXPORTERS_LOOP: LOOP

		FETCH CUR INTO CURR_VALUE_CD, CURR_LABEL ;
	
		IF DONE THEN LEAVE EXPORTERS_LOOP;
		END IF;
	
		IF CURR_LABEL = "knowagebirtreporteng" THEN SELECT CONCAT(VALUE_FOR_KNOWAGEBIRTREPORTENG, ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEBIRTREPORTENG ; END IF ;
		IF CURR_LABEL = "knowagechartengine"   THEN SELECT CONCAT(VALUE_FOR_KNOWAGECHARTENGINE  , ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGECHARTENGINE   ; END IF ;
		IF CURR_LABEL = "knowagecockpitengine" THEN SELECT CONCAT(VALUE_FOR_KNOWAGECOCKPITENGINE, ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGECOCKPITENGINE ; END IF ;
		IF CURR_LABEL = "knowagejasperreporte" THEN SELECT CONCAT(VALUE_FOR_KNOWAGEJASPERREPORTE, ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEJASPERREPORTE ; END IF ;
		IF CURR_LABEL = "knowagekpiengine"     THEN SELECT CONCAT(VALUE_FOR_KNOWAGEKPIENGINE    , ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEKPIENGINE     ; END IF ;
		IF CURR_LABEL = "knowagenetworkengine" THEN SELECT CONCAT(VALUE_FOR_KNOWAGENETWORKENGINE, ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGENETWORKENGINE ; END IF ;
		IF CURR_LABEL = "knowageolapengine"    THEN SELECT CONCAT(VALUE_FOR_KNOWAGEOLAPENGINE   , ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEOLAPENGINE    ; END IF ;
		IF CURR_LABEL = "knowageqbeengine"     THEN SELECT CONCAT(VALUE_FOR_KNOWAGEQBEENGINE    , ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEQBEENGINE     ; END IF ;
		IF CURR_LABEL = "knowagewhatifengine"  THEN SELECT CONCAT(VALUE_FOR_KNOWAGEWHATIFENGINE , ",", CURR_VALUE_CD) INTO VALUE_FOR_KNOWAGEWHATIFENGINE  ; END IF ;
		
	END LOOP EXPORTERS_LOOP ;

	CLOSE CUR ;

	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEBIRTREPORTENG, "^,", "") WHERE LABEL = "document.exporter.knowagebirtreporteng" ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGECOCKPITENGINE, "^,", "") WHERE LABEL = "document.exporter.knowagecockpitengine" ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEJASPERREPORTE, "^,", "") WHERE LABEL = "document.exporter.knowagejasperreporte" ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEKPIENGINE,     "^,", "") WHERE LABEL = "document.exporter.knowagekpiengine"     ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEOLAPENGINE,    "^,", "") WHERE LABEL = "document.exporter.knowageolapengine"    ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEQBEENGINE,     "^,", "") WHERE LABEL = "document.exporter.knowageqbeengine"     ;
	UPDATE SBI_CONFIG SET VALUE_CHECK = REGEXP_REPLACE(VALUE_FOR_KNOWAGEWHATIFENGINE,  "^,", "") WHERE LABEL = "document.exporter.knowagewhatifengine"  ;

END //

DELIMITER ;

CALL MIGRATE_EXPORTERS_TO_SBI_CONFIG() ;

DROP PROCEDURE IF EXISTS MIGRATE_EXPORTERS_TO_SBI_CONFIG ;

DELETE FROM SBI_EXPORTERS ;

DELETE FROM SBI_DOMAINS WHERE DOMAIN_CD = "EXPORT_TYPE" ;
