ALTER TABLE SBI_KPI_KPI ALTER COLUMN DEFINITION VARCHAR(4000);
ALTER TABLE SBI_KPI_RULE ALTER COLUMN DEFINITION VARCHAR(4000);
ALTER TABLE SBI_KPI_VALUE ALTER COLUMN LOGICAL_KEY VARCHAR(4000);

ALTER TABLE SBI_META_MODELS         ADD CONSTRAINT FK_META_MODELS_DS_ID          FOREIGN KEY (DATA_SOURCE_ID) REFERENCES SBI_DATA_SOURCE (DS_ID) ;
