/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.tools.datasource.metadata;


// Generated 31-mag-2007 14.53.27 by Hibernate Tools 3.2.0.beta8

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiGeoMaps generated by hbm2java
 */
public class SbiDataSource extends SbiHibernateModel {

	private int dsId;	
	
	private SbiDomains dialect;
	
	private String dialectDescr;

	private String descr;
	
	private String label;

	private String jndi;
	
	private String url_connection;
	
	private String user;
	
	private String pwd;
	
	private String driver;
	
    private Set sbiObjectses;
    
    private Set sbiEngineses;
    
    private String schemaAttribute=null;
    
    private Boolean multiSchema=null;

    private Boolean readOnly=null;

    private Boolean writeDefault=null;

    private Set sbiOrganizationDatasources = new HashSet(0);

	// Constructors



	/**
	 * default constructor.
	 */
	public SbiDataSource() {
	}

	public String getSchemaAttribute() {
		return schemaAttribute;
	}

	public void setSchemaAttribute(String schemaAttribute) {
		this.schemaAttribute = schemaAttribute;
	}

	public Boolean getMultiSchema() {
		return multiSchema;
	}

	public void setMultiSchema(Boolean multiSchema) {
		this.multiSchema = multiSchema;
	}

	/**
	 * minimal constructor.
	 * 
	 * @param dsId Identifier of data source
	 */
	public SbiDataSource(int dsId) {
		this.dsId = dsId;
	}

	/**
	 * full constructor.
	 * 
	 * @param dsId Identifier of data source
	 * @param descr description of data source
	 * @param label label of data source
	 * @param jndi jndi value
	 * @param url_connection url connection value
	 * @param user user of data source
	 * @param pwd password of data source
	 * @param driver driver of data source
	 * @param dialect the dialect
	 * @param sbiObjectses the sbi objectses
	 * @param sbiEngineses the sbi engineses
	 * @param sbiOrganizationDatasources the association with tenant
	 */
	public SbiDataSource(int dsId, String descr, SbiDomains dialect, String label, String jndi, String url_connection, String user, 
			String pwd, String driver,  Set sbiObjectses, Set sbiEngineses, Boolean multiSchema, String schemaAttribute,
			Boolean readOnly, Boolean writeDefault, Set sbiOrganizationDatasources
			) {
		this.dsId = dsId;		
		this.dialect = dialect;
		this.descr = descr;
		this.label = label;
		this.jndi = jndi;
		this.url_connection = url_connection;
		this.user = user;
		this.pwd = pwd;
		this.driver = driver;
		this.sbiObjectses = sbiObjectses;
	    this.sbiEngineses = sbiEngineses;
	    this.schemaAttribute = schemaAttribute;
	    this.multiSchema = multiSchema;
	    this.readOnly = readOnly;
	    this.writeDefault = writeDefault;
	    this.sbiOrganizationDatasources = sbiOrganizationDatasources;
	}

	/**
	 * Gets the ds id.
	 * 
	 * @return the ds id
	 */
	public int getDsId() {
		return dsId;
	}

	/**
	 * Sets the ds id.
	 * 
	 * @param dsId the new ds id
	 */
	public void setDsId(int dsId) {
		this.dsId = dsId;
	}
	
	/**
	 * Gets the dialect.
	 * 
	 * @return the dialect
	 */
	public SbiDomains getDialect() {
        return this.dialect;
    }
    
    /**
     * Sets the dialect.
     * 
     * @param dialect the new dialect
     */
    public void setDialect(SbiDomains dialect) {
        this.dialect = dialect;
    }
    
	/**
	 * Gets the dialect descr.
	 * 
	 * @return the dialect descr
	 */
	public String getDialectDescr() {
        return this.dialectDescr;
    }
    
    /**
     * Sets the dialect descr.
     * 
     * @param dialectDescr the new dialect descr
     */
    public void setDialectDescr(String dialectDescr) {
        this.dialectDescr = dialectDescr;
    }

	/**
	 * Gets the descr.
	 * 
	 * @return the descr
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * Sets the descr.
	 * 
	 * @param descr the new descr
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * Gets the label.
	 * 
	 * @return the label
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the label.
	 * 
	 * @param label the new label
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * Gets the jndi.
	 * 
	 * @return the jndi
	 */
	public String getJndi() {
		return jndi;
	}

	/**
	 * Sets the jndi.
	 * 
	 * @param jndi the new jndi
	 */
	public void setJndi(String jndi) {
		this.jndi = jndi;
	}

	/**
	 * Gets the url_connection.
	 * 
	 * @return the url_connection
	 */
	public String getUrl_connection() {
		return url_connection;
	}

	/**
	 * Sets the url_connection.
	 * 
	 * @param url_connection the new url_connection
	 */
	public void setUrl_connection(String url_connection) {
		this.url_connection = url_connection;
	}

	/**
	 * Gets the user.
	 * 
	 * @return the user
	 */
	public String getUser() {
		return user;
	}

	/**
	 * Sets the user.
	 * 
	 * @param user the new user
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * Gets the pwd.
	 * 
	 * @return the pwd
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * Sets the pwd.
	 * 
	 * @param pwd the new pwd
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * Gets the driver.
	 * 
	 * @return the driver
	 */
	public String getDriver() {
		return driver;
	}

	/**
	 * Sets the driver.
	 * 
	 * @param driver the new driver
	 */
	public void setDriver(String driver) {
		this.driver = driver;
	}
	
	/**
	 * Gets the sbi objectses.
	 * 
	 * @return the sbi objectses
	 */
	public Set getSbiObjectses() {
        return this.sbiObjectses;
    }
    
    /**
     * Sets the sbi objectses.
     * 
     * @param sbiObjectses the new sbi objectses
     */
    public void setSbiObjectses(Set sbiObjectses) {
        this.sbiObjectses = sbiObjectses;
    }

    /**
     * Gets the sbi engineses.
     * 
     * @return the sbi engineses
     */
    public Set getSbiEngineses() {
        return this.sbiEngineses;
    }
    
    /**
     * Sets the sbi engineses.
     * 
     * @param sbiEngineses the new sbi engineses
     */
    public void setSbiEngineses(Set sbiEngineses) {
        this.sbiEngineses = sbiEngineses;
    }

	public Boolean getReadOnly() {
		return readOnly;
	}

	public void setReadOnly(Boolean readOnly) {
		this.readOnly = readOnly;
	}

	public Boolean getWriteDefault() {
		return writeDefault;
	}

	public void setWriteDefault(Boolean writeDefault) {
		this.writeDefault = writeDefault;
	}

	public Set getSbiOrganizationDatasources() {
		return this.sbiOrganizationDatasources;
	}

	public void setSbiOrganizationDatasources(Set sbiOrganizationDatasources) {
		this.sbiOrganizationDatasources = sbiOrganizationDatasources;
	}
    
}
