/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.tools.distributionlist.metadata;
// Generated 19-feb-2008 18.15.47 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiDistributionList generated by hbm2java
 */

public class SbiDistributionList  extends SbiHibernateModel {


    // Fields    

     private Integer dlId;
     private String name;
     private String descr;
     private Set sbiDistributionListUsers = new HashSet(0);
     private Set sbiDistributionListsObjectses = new HashSet(0);


    // Constructors

    /**
     * default constructor.
     */
    public SbiDistributionList() {
    }

	/**
	 * minimal constructor.
	 * 
	 * @param dlId the dl id
	 * @param name the name
	 */
    public SbiDistributionList(Integer dlId, String name) {
        this.dlId = dlId;
        this.name = name;
    }
    
    /**
     * full constructor.
     * 
     * @param dlId the dl id
     * @param name the name
     * @param descr the descr
     * @param sbiDistributionListUsers the sbi distribution list users
     * @param sbiDistributionListsObjectses the sbi distribution lists objectses
     */
    public SbiDistributionList(Integer dlId, String name, String descr, Set sbiDistributionListUsers, Set sbiDistributionListsObjectses) {
        this.dlId = dlId;
        this.name = name;
        this.descr = descr;
        this.sbiDistributionListUsers = sbiDistributionListUsers;
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
    

   
    // Property accessors

    /**
     * Gets the dl id.
     * 
     * @return the dl id
     */
    public Integer getDlId() {
        return this.dlId;
    }
    
    /**
     * Sets the dl id.
     * 
     * @param dlId the new dl id
     */
    public void setDlId(Integer dlId) {
        this.dlId = dlId;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }
    
    /**
     * Sets the name.
     * 
     * @param name the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the descr.
     * 
     * @return the descr
     */
    public String getDescr() {
        return this.descr;
    }
    
    /**
     * Sets the descr.
     * 
     * @param descr the new descr
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * Gets the sbi distribution list users.
     * 
     * @return the sbi distribution list users
     */
    public Set getSbiDistributionListUsers() {
        return this.sbiDistributionListUsers;
    }
    
    /**
     * Sets the sbi distribution list users.
     * 
     * @param sbiDistributionListUsers the new sbi distribution list users
     */
    public void setSbiDistributionListUsers(Set sbiDistributionListUsers) {
        this.sbiDistributionListUsers = sbiDistributionListUsers;
    }

    /**
     * Gets the sbi distribution lists objectses.
     * 
     * @return the sbi distribution lists objectses
     */
    public Set getSbiDistributionListsObjectses() {
        return this.sbiDistributionListsObjectses;
    }
    
    /**
     * Sets the sbi distribution lists objectses.
     * 
     * @param sbiDistributionListsObjectses the new sbi distribution lists objectses
     */
    public void setSbiDistributionListsObjectses(Set sbiDistributionListsObjectses) {
        this.sbiDistributionListsObjectses = sbiDistributionListsObjectses;
    }
   




}
