/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;


// Generated 17-set-2010 11.25.47 by Hibernate Tools 3.2.4.GA

/**
 * SbiKpiRel generated by hbm2java
 */
public class SbiKpiRel extends SbiHibernateModel {

	private Integer kpiRelId;
	private SbiKpi sbiKpiByKpiChildId;
	private SbiKpi sbiKpiByKpiFatherId;
	private String parameter;

	public SbiKpiRel() {
	}

	public SbiKpiRel(SbiKpi sbiKpiByKpiChildId, SbiKpi sbiKpiByKpiFatherId) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
	}

	public SbiKpiRel(SbiKpi sbiKpiByKpiChildId, SbiKpi sbiKpiByKpiFatherId,
			String parameter) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
		this.parameter = parameter;
	}

	public Integer getKpiRelId() {
		return this.kpiRelId;
	}

	public void setKpiRelId(Integer kpiRelId) {
		this.kpiRelId = kpiRelId;
	}

	public SbiKpi getSbiKpiByKpiChildId() {
		return this.sbiKpiByKpiChildId;
	}

	public void setSbiKpiByKpiChildId(SbiKpi sbiKpiByKpiChildId) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
	}

	public SbiKpi getSbiKpiByKpiFatherId() {
		return this.sbiKpiByKpiFatherId;
	}

	public void setSbiKpiByKpiFatherId(SbiKpi sbiKpiByKpiFatherId) {
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
	}

	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

}
