/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.35 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.threshold.metadata.SbiThreshold;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * SbiKpiInstance generated by hbm2java
 */

public class SbiKpiInstance  extends SbiHibernateModel{


    // Fields    

     private Integer idKpiInstance;
     private SbiKpi sbiKpi;
     private SbiDomains chartType;
     private SbiThreshold sbiThreshold;
     private SbiMeasureUnit sbiMeasureUnit;
     private Double weight;
     private Double target;
     private Set sbiKpiModelInsts = new HashSet(0);
     private Set sbiKpiInstanceHistories = new HashSet(0);
     private Set sbiKpiValues = new HashSet(0);
     private Set sbiAlarms = new HashSet(0);
     private Date beginDt;
     private Set sbiKpiInstPeriods = new HashSet(0);


    // Constructors

    public Date getBeginDt() {
		return beginDt;
	}

	public void setBeginDt(Date beginDt) {
		this.beginDt = beginDt;
	}

	/** default constructor */
    public SbiKpiInstance() {
    }

	/** minimal constructor */
    public SbiKpiInstance(Integer idKpiInstance, SbiKpi sbiKpi, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit) {
        this.idKpiInstance = idKpiInstance;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
    }
    
    /** full constructor */
    public SbiKpiInstance(Integer idKpiInstance, SbiKpi sbiKpi,  SbiDomains sbiDomains, SbiThreshold sbiThreshold, SbiMeasureUnit sbiMeasureUnit, double weight, Set sbiKpiModelInsts, Set sbiKpiInstanceHistories, Set sbiKpiValues, Set sbiAlarms, Set sbiKpiInstPeriods) {
        this.idKpiInstance = idKpiInstance;
        this.sbiKpi = sbiKpi;
        this.sbiThreshold = sbiThreshold;
        this.sbiMeasureUnit = sbiMeasureUnit;
        this.weight = weight;
        this.chartType = sbiDomains;
        this.sbiKpiModelInsts = sbiKpiModelInsts;
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
        this.sbiKpiValues = sbiKpiValues;
        this.sbiAlarms = sbiAlarms;
        this.sbiKpiInstPeriods = sbiKpiInstPeriods;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstance() {
        return this.idKpiInstance;
    }
    
    public void setIdKpiInstance(Integer idKpiInstance) {
        this.idKpiInstance = idKpiInstance;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiMeasureUnit getSbiMeasureUnit() {
        return this.sbiMeasureUnit;
    }
    
    public void setSbiMeasureUnit(SbiMeasureUnit sbiMeasureUnit) {
        this.sbiMeasureUnit = sbiMeasureUnit;
    }

    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Set getSbiKpiModelInsts() {
        return this.sbiKpiModelInsts;
    }
    
    public void setSbiKpiModelInsts(Set sbiKpiModelInsts) {
        this.sbiKpiModelInsts = sbiKpiModelInsts;
    }

    public Set getSbiKpiInstanceHistories() {
        return this.sbiKpiInstanceHistories;
    }
    
    public void setSbiKpiInstanceHistories(Set sbiKpiInstanceHistories) {
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }

    public Set getSbiKpiValues() {
        return this.sbiKpiValues;
    }
    
    public void setSbiKpiValues(Set sbiKpiValues) {
        this.sbiKpiValues = sbiKpiValues;
    }

    public Set getSbiAlarms() {
        return this.sbiAlarms;
    }
    
    public void setSbiAlarms(Set sbiAlarms) {
        this.sbiAlarms = sbiAlarms;
    }
   
    public SbiDomains getChartType() {
        return this.chartType;
    }
    
    public void setChartType(SbiDomains sbiDomains) {
        this.chartType = sbiDomains;
    }

	public Double getTarget() {
		return target;
	}

	public void setTarget(Double target) {
		this.target = target;
	}
	
	public Set getSbiKpiInstPeriods() {
        return this.sbiKpiInstPeriods;
    }
    
    public void setSbiKpiInstPeriods(Set sbiKpiInstPeriods) {
        this.sbiKpiInstPeriods = sbiKpiInstPeriods;
    }
   
}
