/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package it.eng.spagobi.engines.config.metadata;


import it.eng.spagobi.commons.metadata.SbiDomains;
// Generated 4-giu-2009 12.50.24 by Hibernate Tools 3.1.0 beta3



/**
 * SbiExporters generated by hbm2java
 */

public class SbiExporters  implements java.io.Serializable {


    // Fields    

     private SbiExportersId id;
     private SbiEngines sbiEngines;
     private SbiDomains sbiDomains;
     private boolean defaultValue;


    // Constructors

    /** default constructor */
    public SbiExporters() {
    }

	/** minimal constructor */
    public SbiExporters(SbiExportersId id, SbiEngines sbiEngines, SbiDomains sbiDomains) {
        this.id = id;
        this.sbiEngines = sbiEngines;
        this.sbiDomains = sbiDomains;
    }
    
    /** full constructor */
    public SbiExporters(SbiExportersId id, SbiEngines sbiEngines, SbiDomains sbiDomains, boolean defaultValue) {
        this.id = id;
        this.sbiEngines = sbiEngines;
        this.sbiDomains = sbiDomains;
        this.defaultValue = defaultValue;
    }
    

   
    // Property accessors

    public SbiExportersId getId() {
        return this.id;
    }
    
    public void setId(SbiExportersId id) {
        this.id = id;
    }

    public SbiEngines getSbiEngines() {
        return this.sbiEngines;
    }
    
    public void setSbiEngines(SbiEngines sbiEngines) {
        this.sbiEngines = sbiEngines;
    }

    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    public boolean isDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(boolean defaultValue) {
        this.defaultValue = defaultValue;
    }
   








}
