/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.tools.distributionlist.metadata;

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiDistributionListsObjects generated by hbm2java
 */

public class SbiDistributionListsObjects  extends SbiHibernateModel {


    // Fields    

     private Integer relId;
     private SbiObjects sbiObjects;
     private SbiDistributionList sbiDistributionList;
     private String xml;


    // Constructors

    /**
     * default constructor.
     */
    public SbiDistributionListsObjects() {
    }

    
    /**
     * full constructor.
     * 
     * @param relId the rel id
     * @param sbiObjects the sbi objects
     * @param sbiDistributionList the sbi distribution list
     * @param xml the xml
     */
    public SbiDistributionListsObjects(Integer relId, SbiObjects sbiObjects, SbiDistributionList sbiDistributionList, String xml) {
        this.relId = relId;
        this.sbiObjects = sbiObjects;
        this.sbiDistributionList = sbiDistributionList;
        this.xml = xml;
    }
    

   
    // Property accessors

    /**
     * Gets the rel id.
     * 
     * @return the rel id
     */
    public Integer getRelId() {
        return this.relId;
    }
    
    /**
     * Sets the rel id.
     * 
     * @param relId the new rel id
     */
    public void setRelId(Integer relId) {
        this.relId = relId;
    }

    /**
     * Gets the sbi objects.
     * 
     * @return the sbi objects
     */
    public SbiObjects getSbiObjects() {
        return this.sbiObjects;
    }
    
    /**
     * Sets the sbi objects.
     * 
     * @param sbiObjects the new sbi objects
     */
    public void setSbiObjects(SbiObjects sbiObjects) {
        this.sbiObjects = sbiObjects;
    }

    /**
     * Gets the sbi distribution list.
     * 
     * @return the sbi distribution list
     */
    public SbiDistributionList getSbiDistributionList() {
        return this.sbiDistributionList;
    }
    
    /**
     * Sets the sbi distribution list.
     * 
     * @param sbiDistributionList the new sbi distribution list
     */
    public void setSbiDistributionList(SbiDistributionList sbiDistributionList) {
        this.sbiDistributionList = sbiDistributionList;
    }

    /**
     * Gets the xml.
     * 
     * @return the xml
     */
    public String getXml() {
        return this.xml;
    }
    
    /**
     * Sets the xml.
     * 
     * @param xml the new xml
     */
    public void setXml(String xml) {
        this.xml = xml;
    }
   








}
