ALTER TABLE SBI_CROSS_NAVIGATION ADD DESCRIPTION VARCHAR2(200);
ALTER TABLE SBI_CROSS_NAVIGATION ADD BREADCRUMB VARCHAR2(200);

CREATE TABLE SBI_METAMODEL_VIEWPOINTS (
VP_ID INTEGER NOT NULL,
METAMODEL_ID INTEGER NOT NULL,
VP_NAME VARCHAR(40) NOT NULL,
VP_OWNER VARCHAR(40) DEFAULT NULL,
VP_DESC VARCHAR(160) DEFAULT NULL,
VP_SCOPE VARCHAR(20) NOT NULL,
VP_VALUE_PARAMS CLOB,
VP_CREATION_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
USER_IN VARCHAR(100) NOT NULL,
USER_UP VARCHAR(100) DEFAULT NULL,
USER_DE VARCHAR(100) DEFAULT NULL,
TIME_IN TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
TIME_UP TIMESTAMP  DEFAULT NULL,
TIME_DE TIMESTAMP  DEFAULT NULL,
SBI_VERSION_IN VARCHAR(10) DEFAULT NULL,
SBI_VERSION_UP VARCHAR(10) DEFAULT NULL,
SBI_VERSION_DE VARCHAR(10) DEFAULT NULL,
META_VERSION VARCHAR(100) DEFAULT NULL,
ORGANIZATION VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (VP_ID)
) ;

ALTER TABLE SBI_METAMODEL_VIEWPOINTS ADD CONSTRAINT FK_SBI_METAMODEL_VIEWPOINTS_1 FOREIGN KEY (METAMODEL_ID) REFERENCES SBI_META_MODELS (ID);
CREATE TABLE SBI_TAG (
	TAG_ID               INTEGER NOT NULL,
	NAME                 VARCHAR(30) NOT NULL,
	USER_IN              VARCHAR(100) NOT NULL,
	USER_UP              VARCHAR(100),
	USER_DE              VARCHAR(100),
	TIME_IN              TIMESTAMP NOT NULL,
	TIME_UP              TIMESTAMP  DEFAULT NULL,
	TIME_DE              TIMESTAMP  DEFAULT NULL,
	SBI_VERSION_IN       VARCHAR(10),
	SBI_VERSION_UP       VARCHAR(10),
	SBI_VERSION_DE       VARCHAR(10),
	META_VERSION         VARCHAR(100),
	ORGANIZATION         VARCHAR(20),
	PRIMARY KEY (TAG_ID),
	CONSTRAINT XAK1SBI_TAG UNIQUE (NAME, ORGANIZATION)
);


CREATE TABLE SBI_DATA_SET_TAG (
	DS_ID                INTEGER NOT NULL,
	VERSION_NUM	     	 INTEGER NOT NULL,
	ORGANIZATION         VARCHAR(20),
	TAG_ID               INTEGER NOT NULL,
	PRIMARY KEY (DS_ID, VERSION_NUM, ORGANIZATION, TAG_ID),
	FOREIGN KEY (TAG_ID) REFERENCES SBI_TAG (TAG_ID) ,
	FOREIGN KEY (DS_ID, VERSION_NUM, ORGANIZATION) REFERENCES SBI_DATA_SET (DS_ID, VERSION_NUM, ORGANIZATION)
	
);
