ALTER TABLE SBI_KPI_KPI ALTER DEFINITION TYPE VARCHAR(4000);
ALTER TABLE SBI_KPI_VALUE ALTER LOGICAL_KEY TYPE VARCHAR(4000);

ALTER TABLE SBI_META_MODEL add  Foreign Key (DATA_SOURCE_ID) references SBI_DATA_SOURCE (DS_ID);