/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.tools.massiveExport.metadata;


/**s
 * SbiProgressThread generated by hbm2java
 */
public class SbiProgressThread implements java.io.Serializable {

	private int progressThreadId;
	private String userId;
	private Integer partial;
	private Integer total;
	private String functionCd;
	private String status;
	private String randomKey;
	private String type;

	public SbiProgressThread() {
	}

	public SbiProgressThread(int progressThreadId, String userId) {
		this.progressThreadId = progressThreadId;
		this.userId = userId;
	}

	public SbiProgressThread(int progressThreadId, String userId,
			Integer partial, Integer total, String functionCd, String status, String randomKey, String type) {
		this.progressThreadId = progressThreadId;
		this.userId = userId;
		this.partial = partial;
		this.total = total;
		this.functionCd = functionCd;
		this.status = status;
		this.randomKey = randomKey;
		this.type = type;
	}

	public int getProgressThreadId() {
		return this.progressThreadId;
	}

	public void setProgressThreadId(int progressThreadId) {
		this.progressThreadId = progressThreadId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getPartial() {
		return this.partial;
	}

	public void setPartial(Integer partial) {
		this.partial = partial;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public String getFunctionCd() {
		return this.functionCd;
	}

	public void setFunctionCd(String functionCd) {
		this.functionCd = functionCd;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRandomKey() {
		return randomKey;
	}

	public void setRandomKey(String randomKey) {
		this.randomKey = randomKey;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
