/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.kpi.ou.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.model.metadata.SbiKpiModelInst;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3



/**
 * SbiOrgUnitGrantNodes generated by hbm2java
 */

public class SbiOrgUnitGrantNodes  extends SbiHibernateModel {


    // Fields    

     private SbiOrgUnitGrantNodesId id;
     private SbiOrgUnitNodes sbiOrgUnitNodes;
     private SbiKpiModelInst sbiKpiModelInst;
     private SbiOrgUnitGrant sbiOrgUnitGrant;


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrantNodes() {
    }

    
    /** full constructor */
    public SbiOrgUnitGrantNodes(SbiOrgUnitGrantNodesId id, SbiOrgUnitNodes sbiOrgUnitNodes, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.id = id;
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
    

   
    // Property accessors

    public SbiOrgUnitGrantNodesId getId() {
        return this.id;
    }
    
    public void setId(SbiOrgUnitGrantNodesId id) {
        this.id = id;
    }

    public SbiOrgUnitNodes getSbiOrgUnitNodes() {
        return this.sbiOrgUnitNodes;
    }
    
    public void setSbiOrgUnitNodes(SbiOrgUnitNodes sbiOrgUnitNodes) {
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
    }

    public SbiKpiModelInst getSbiKpiModelInst() {
        return this.sbiKpiModelInst;
    }
    
    public void setSbiKpiModelInst(SbiKpiModelInst sbiKpiModelInst) {
        this.sbiKpiModelInst = sbiKpiModelInst;
    }

    public SbiOrgUnitGrant getSbiOrgUnitGrant() {
        return this.sbiOrgUnitGrant;
    }
    
    public void setSbiOrgUnitGrant(SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
   








}
