/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */
package it.eng.spagobi.kpi.ou.metadata;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.kpi.model.metadata.SbiKpiModelInst;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * SbiOrgUnitGrant generated by hbm2java
 */

public class SbiOrgUnitGrant  extends SbiHibernateModel {


    // Fields    

     private Integer id;
     private SbiKpiModelInst sbiKpiModelInst;
     private SbiOrgUnitHierarchies sbiOrgUnitHierarchies;
     private Date startDate;
     private Date endDate;
     private String label;
     private String name;
     private String description;
     private Boolean isAvailable;


	private Set sbiOrgUnitGrantNodeses = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrant() {
    }

	/** minimal constructor */
    public SbiOrgUnitGrant(Integer id, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
        this.id = id;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
    }
    
    /** full constructor */
    public SbiOrgUnitGrant(Integer id, Boolean isAvailable, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitHierarchies sbiOrgUnitHierarchies, Date startDate, Date endDate, String label, String name, String description, Set sbiOrgUnitGrantNodeses) {
        this.id = id;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
        this.startDate = startDate;
        this.endDate = endDate;
        this.label = label;
        this.name = name;
        this.description = description;
        this.isAvailable = isAvailable;
        this.sbiOrgUnitGrantNodeses = sbiOrgUnitGrantNodeses;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public SbiKpiModelInst getSbiKpiModelInst() {
        return this.sbiKpiModelInst;
    }
    
    public void setSbiKpiModelInst(SbiKpiModelInst sbiKpiModelInst) {
        this.sbiKpiModelInst = sbiKpiModelInst;
    }

    public SbiOrgUnitHierarchies getSbiOrgUnitHierarchies() {
        return this.sbiOrgUnitHierarchies;
    }
    
    public void setSbiOrgUnitHierarchies(SbiOrgUnitHierarchies sbiOrgUnitHierarchies) {
        this.sbiOrgUnitHierarchies = sbiOrgUnitHierarchies;
    }

    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSbiOrgUnitGrantNodeses() {
        return this.sbiOrgUnitGrantNodeses;
    }
    
    public void setSbiOrgUnitGrantNodeses(Set sbiOrgUnitGrantNodeses) {
        this.sbiOrgUnitGrantNodeses = sbiOrgUnitGrantNodeses;
    }
    public Boolean getIsAvailable() {
		return isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}








}
