export interface iQBE {
    actions: { name: string, description: string }[],
    canLoadData: boolean,
    catTypeId: any,
    catTypeVn: any,
    dateIn: string | Date,
    description: string | null,
    dsTypeCd: string,
    dsVersions: any[],
    endDate: string | Date | null,
    id: number,
    isIterable: boolean,
    isPersisted: boolean,
    isPersistedHDFS: boolean,
    isRealtime: boolean,
    isScheduled: boolean,
    label: string,
    meta: { dataset: { pname: string, pvalue: string }[], columns: { column: string, pname: string, pvalue: string }[] },
    name: string,
    owner: string,
    pars: any[],
    persistTableName: string,
    pivotColName: string | null,
    pivotColValue: string | null,
    pivotIsNumRows: boolean,
    pivotRowName: string | null,
    qbeDataSource: string,
    qbeDataSourceId: number,
    qbeDatamarts: string,
    qbeJSONQuery: any,
    schedulingCronLine: any,
    scopeCd: string,
    scopeId: number,
    startDate: string | Date | null,
    tags: any[],
    trasfTypeCd: any,
    usedByNDocs: number,
    userIn: string,
    versNum: number
}