package it.eng.spagobi.metadata.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 12-apr-2016 10.43.25 by Hibernate Tools 3.4.0.CR1

/**
 * SbiMetaJobSourceId generated by hbm2java
 */
public class SbiMetaJobSourceId extends SbiHibernateModel {

	private int jobId;
	private int sourceId;

	public SbiMetaJobSourceId() {
	}

	public SbiMetaJobSourceId(int jobId, int sourceId) {
		this.jobId = jobId;
		this.sourceId = sourceId;
	}

	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	public int getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(int sourceId) {
		this.sourceId = sourceId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiMetaJobSourceId))
			return false;
		SbiMetaJobSourceId castOther = (SbiMetaJobSourceId) other;

		return (this.getJobId() == castOther.getJobId()) && (this.getSourceId() == castOther.getSourceId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJobId();
		result = 37 * result + this.getSourceId();
		return result;
	}

}
