package it.eng.spagobi.metadata.metadata;

import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated 13-apr-2016 14.55.30 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.services.validation.ExtendedAlphanumeric;

/**
 * SbiMetaSource generated by hbm2java
 */
public class SbiMetaSource extends SbiHibernateModel {

	private Integer sourceId;

	@NotEmpty
	@ExtendedAlphanumeric
	@Size(max = 100)
	private String name;

	@NotEmpty
	@ExtendedAlphanumeric
	@Size(max = 100)
	private String type;

	@ExtendedAlphanumeric
	@Size(max = 100)
	private String url;

	@ExtendedAlphanumeric
	@Size(max = 100)
	private String location;

	@ExtendedAlphanumeric
	@Size(max = 100)
	private String sourceSchema;

	@ExtendedAlphanumeric
	@Size(max = 100)
	private String sourceCatalogue;

	@ExtendedAlphanumeric
	@Size(max = 100)
	private String role;

	@JsonIgnore
	private Set sbiMetaJobSources = new HashSet(0);
	@JsonIgnore
	private Set sbiMetaTables = new HashSet(0);

	public SbiMetaSource() {
	}

	public SbiMetaSource(String name, String type) {
		this.name = name;
		this.type = type;
	}

	public SbiMetaSource(String name, String type, String url, String location, String sourceSchema, String sourceCatalogue, String role, Set sbiMetaJobSources,
			Set sbiMetaTables) {
		this.name = name;
		this.type = type;
		this.url = url;
		this.location = location;
		this.sourceSchema = sourceSchema;
		this.sourceCatalogue = sourceCatalogue;
		this.role = role;
		this.sbiMetaJobSources = sbiMetaJobSources;
		this.sbiMetaTables = sbiMetaTables;
	}

	public Integer getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSourceSchema() {
		return this.sourceSchema;
	}

	public void setSourceSchema(String sourceSchema) {
		this.sourceSchema = sourceSchema;
	}

	public String getSourceCatalogue() {
		return this.sourceCatalogue;
	}

	public void setSourceCatalogue(String sourceCatalogue) {
		this.sourceCatalogue = sourceCatalogue;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getSbiMetaJobSources() {
		return this.sbiMetaJobSources;
	}

	public void setSbiMetaJobSources(Set sbiMetaJobSources) {
		this.sbiMetaJobSources = sbiMetaJobSources;
	}

	public Set getSbiMetaTables() {
		return this.sbiMetaTables;
	}

	public void setSbiMetaTables(Set sbiMetaTables) {
		this.sbiMetaTables = sbiMetaTables;
	}

}
