package it.eng.spagobi.metadata.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

// Generated 13-apr-2016 14.55.30 by Hibernate Tools 3.4.0.CR1

/**
 * SbiMetaJobTableId generated by hbm2java
 */
public class SbiMetaJobTableId extends SbiHibernateModel {

	private int jobId;
	private int tableId;

	public SbiMetaJobTableId() {
	}

	public SbiMetaJobTableId(int jobId, int tableId) {
		this.jobId = jobId;
		this.tableId = tableId;
	}

	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiMetaJobTableId))
			return false;
		SbiMetaJobTableId castOther = (SbiMetaJobTableId) other;

		return (this.getJobId() == castOther.getJobId()) && (this.getTableId() == castOther.getTableId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJobId();
		result = 37 * result + this.getTableId();
		return result;
	}

}
