package it.eng.spagobi.metadata.metadata;

// Generated 13-apr-2016 14.55.30 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

/**
 * SbiMetaJobTable generated by hbm2java
 */
public class SbiMetaJobTable extends SbiHibernateModel {

	private SbiMetaJobTableId id;
	private SbiMetaTable sbiMetaTable;
	private SbiMetaJob sbiMetaJob;
	private String role;

	public SbiMetaJobTable() {
	}

	public SbiMetaJobTable(SbiMetaJobTableId id, SbiMetaTable sbiMetaTable, SbiMetaJob sbiMetaJob) {
		this.id = id;
		this.sbiMetaTable = sbiMetaTable;
		this.sbiMetaJob = sbiMetaJob;
	}

	public SbiMetaJobTable(SbiMetaJobTableId id, SbiMetaTable sbiMetaTable, SbiMetaJob sbiMetaJob, String role) {
		this.id = id;
		this.sbiMetaTable = sbiMetaTable;
		this.sbiMetaJob = sbiMetaJob;
		this.role = role;
	}

	public SbiMetaJobTableId getId() {
		return this.id;
	}

	public void setId(SbiMetaJobTableId id) {
		this.id = id;
	}

	public SbiMetaTable getSbiMetaTable() {
		return this.sbiMetaTable;
	}

	public void setSbiMetaTable(SbiMetaTable sbiMetaTable) {
		this.sbiMetaTable = sbiMetaTable;
	}

	public SbiMetaJob getSbiMetaJob() {
		return this.sbiMetaJob;
	}

	public void setSbiMetaJob(SbiMetaJob sbiMetaJob) {
		this.sbiMetaJob = sbiMetaJob;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
