/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package it.eng.spagobi.engines.whatif.parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 16 15:47:20 CEST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int RSQRPAREN = 11;
	public static final int MINUS = 4;
	public static final int DIVIDE = 6;
	public static final int UMINUS = 16;
	public static final int PERCENT = 9;
	public static final int NUMBER = 13;
	public static final int MEMBER = 15;
	public static final int SEMI = 2;
	public static final int EQUAL = 12;
	public static final int LSQRPAREN = 10;
	public static final int VARIABLE = 14;
	public static final int EOF = 0;
	public static final int PLUS = 3;
	public static final int error = 1;
	public static final int RPAREN = 8;
	public static final int TIMES = 5;
	public static final int LPAREN = 7;
}
