/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2016 Engineering Ingegneria Informatica S.p.A.
 * 
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package it.eng.spagobi.engines.whatif.parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 16 15:47:20 CEST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int RSQRPAREN = 11;
	public static final int MINUS = 4;
	public static final int DIVIDE = 6;
	public static final int UMINUS = 16;
	public static final int PERCENT = 9;
	public static final int NUMBER = 13;
	public static final int MEMBER = 15;
	public static final int SEMI = 2;
	public static final int EQUAL = 12;
	public static final int LSQRPAREN = 10;
	public static final int VARIABLE = 14;
	public static final int EOF = 0;
	public static final int PLUS = 3;
	public static final int error = 1;
	public static final int RPAREN = 8;
	public static final int TIMES = 5;
	public static final int LPAREN = 7;
}
