-- 2021/07/26
ALTER TABLE SBI_ALERT_ACTION DROP COLUMN TEMPLATE CASCADE;
ALTER TABLE SBI_ALERT_LISTENER DROP COLUMN TEMPLATE CASCADE;

-- 2022/02/08
CREATE TABLE SBI_ORGANIZATION_THEME (
	ID INTEGER NOT NULL,
    ORGANIZATION_ID INTEGER NOT NULL,
    THEME_NAME VARCHAR(255) NOT NULL,
    CONFIG VARCHAR(4000) NULL,
    ACTIVE SMALLINT DEFAULT '1',
    USER_IN VARCHAR(100) NOT NULL,
    USER_UP VARCHAR(100),
    USER_DE VARCHAR(100),
    TIME_IN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME_UP TIMESTAMP NULL DEFAULT NULL,
    TIME_DE TIMESTAMP NULL DEFAULT NULL,
    SBI_VERSION_IN VARCHAR(10),
    SBI_VERSION_UP VARCHAR(10),
    SBI_VERSION_DE VARCHAR(10),
    META_VERSION VARCHAR(100),
    ORGANIZATION VARCHAR(20),
	PRIMARY KEY (ID),
    UNIQUE U_SBI_ORGANIZATION_THEME (THEME_NAME, ORGANIZATION_ID),
    CONSTRAINT FK_ORGANIZATION_1 FOREIGN KEY (ORGANIZATION_ID) REFERENCES SBI_ORGANIZATIONS(ID)
);
INSERT INTO HIBERNATE_SEQUENCES (SEQUENCE_NAME, NEXT_VAL) VALUES('SBI_ORGANIZATION_THEME', 1);