ALTER TABLE SBI_CATALOG_FUNCTION ADD DESCRIPTION TEXT NOT NULL;

ALTER TABLE SBI_PARUSE ADD OPTIONS VARCHAR(4000) NULL DEFAULT NULL

ALTER TABLE  SBI_GEO_MAPS ADD HIERARCHY_NAME VARCHAR(100);
ALTER TABLE  SBI_GEO_MAPS ADD NUM_LEVEL INTEGER;
ALTER TABLE  SBI_GEO_MAPS ADD MEMBER_NAME VARCHAR(100);

ALTER TABLE  SBI_DATA_SET ADD IS_PERSISTED_HDFS BIT DEFAULT 0;