/* SpagoBI, the Open Source Business Intelligence suite

 * Copyright (C) 2012 Engineering Ingegneria Informatica S.p.A. - SpagoBI Competency Center
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0, without the "Incompatible With Secondary Licenses" notice. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package it.eng.spagobi.engines.config.metadata;


import it.eng.spagobi.commons.metadata.SbiDomains;
// Generated 4-giu-2009 12.50.24 by Hibernate Tools 3.1.0 beta3



/**
 * SbiExporters generated by hbm2java
 */

public class SbiExporters  implements java.io.Serializable {


    // Fields    

     private SbiExportersId id;
     private SbiEngines sbiEngines;
     private SbiDomains sbiDomains;
     private boolean defaultValue;


    // Constructors

    /** default constructor */
    public SbiExporters() {
    }

	/** minimal constructor */
    public SbiExporters(SbiExportersId id, SbiEngines sbiEngines, SbiDomains sbiDomains) {
        this.id = id;
        this.sbiEngines = sbiEngines;
        this.sbiDomains = sbiDomains;
    }
    
    /** full constructor */
    public SbiExporters(SbiExportersId id, SbiEngines sbiEngines, SbiDomains sbiDomains, boolean defaultValue) {
        this.id = id;
        this.sbiEngines = sbiEngines;
        this.sbiDomains = sbiDomains;
        this.defaultValue = defaultValue;
    }
    

   
    // Property accessors

    public SbiExportersId getId() {
        return this.id;
    }
    
    public void setId(SbiExportersId id) {
        this.id = id;
    }

    public SbiEngines getSbiEngines() {
        return this.sbiEngines;
    }
    
    public void setSbiEngines(SbiEngines sbiEngines) {
        this.sbiEngines = sbiEngines;
    }

    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    public boolean isDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(boolean defaultValue) {
        this.defaultValue = defaultValue;
    }
   








}
