--Chiara 27/05/2010
ALTER TABLE SBI_RESOURCES ADD COLUMN RESOURCE_CODE VARCHAR(45);
UPDATE SBI_RESOURCES SET RESOURCE_CODE = RESOURCE_NAME;
CREATE UNIQUE INDEX UNIQUE_RES_CODE ON SBI_RESOURCES(RESOURCE_CODE);
ALTER TABLE SBI_RESOURCES ALTER COLUMN RESOURCE_CODE SET NOT NULL;
--testato
--Giulio 31/05/2010
CREATE SEQUENCE SBI_KPI_MODEL_ATTR_SEQ INCREMENT 1 START  1 ;
--Giulio 05/07/2010
ALTER TABLE  SBI_KPI_MODEL_ATTR ALTER COLUMN KPI_MODEL_ATTR_ID SET DEFAULT nextval('SBI_KPI_MODEL_ATTR_SEQ')
