/*
 * Knowage, Open Source Business Intelligence suite
 * Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
 *
 * Knowage is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knowage is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.eng.spagobi.services.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 *
 */
@WebService(name = "SecurityServiceService", targetNamespace = "http://security.services.spagobi.eng.it/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SecurityServiceService {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "isAuthorized", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.IsAuthorized")
	@ResponseWrapper(localName = "isAuthorizedResponse", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.IsAuthorizedResponse")
	public boolean isAuthorized(@WebParam(name = "arg0", targetNamespace = "") String arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2, @WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns it.eng.spagobi.services.security.SpagoBIUserProfile
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserProfile", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.GetUserProfile")
	@ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.GetUserProfileResponse")
	public SpagoBIUserProfile getUserProfile(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkAuthorization", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.CheckAuthorization")
	@ResponseWrapper(localName = "checkAuthorizationResponse", targetNamespace = "http://security.services.spagobi.eng.it/", className = "it.eng.spagobi.services.security.CheckAuthorizationResponse")
	public boolean checkAuthorization(@WebParam(name = "arg0", targetNamespace = "") String arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
