name: "Jest test"
on:
  pull_request_target:
    types: [opened,synchronize]
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
        working-directory: ./knowage-vue
      - run: npm run test:ci
        working-directory: ./knowage-vue
