# Aggiungi questo a .github/workflows/publiccode-validation.yml
#
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'knowage-server-*'
  pull_request:
  pull_request_target:

jobs:
  publiccode_validation:
    runs-on: ubuntu-latest
    name: publiccode validation
    steps:
    - uses: actions/checkout@v3
    - uses: italia/publiccode-parser-action@v1
      with:
        publiccode: 'publiccode.yml'
