<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:spagobiaudit" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:spagobiaudit" xmlns:intf="urn:spagobiaudit" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="logRequest">

      <wsdl:part name="in0" type="soapenc:string"/>

      <wsdl:part name="in1" type="soapenc:string"/>

      <wsdl:part name="in2" type="soapenc:string"/>

      <wsdl:part name="in3" type="soapenc:string"/>

      <wsdl:part name="in4" type="soapenc:string"/>

      <wsdl:part name="in5" type="soapenc:string"/>

      <wsdl:part name="in6" type="soapenc:string"/>

      <wsdl:part name="in7" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="logResponse">

      <wsdl:part name="logReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="AuditService">

      <wsdl:operation name="log" parameterOrder="in0 in1 in2 in3 in4 in5 in6 in7">

         <wsdl:input message="impl:logRequest" name="logRequest"/>

         <wsdl:output message="impl:logResponse" name="logResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="AuditServiceSoapBinding" type="impl:AuditService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="log">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="logRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobiaudit" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="logResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobiaudit" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="AuditServiceService">

      <wsdl:port binding="impl:AuditServiceSoapBinding" name="AuditService">

         <wsdlsoap:address location="http://localhost:8080/SpagoBI/services/AuditService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
