<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:spagobievent" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:spagobievent" xmlns:intf="urn:spagobievent" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="fireEventRequest">

      <wsdl:part name="in0" type="soapenc:string"/>

      <wsdl:part name="in1" type="soapenc:string"/>

      <wsdl:part name="in2" type="soapenc:string"/>

      <wsdl:part name="in3" type="soapenc:string"/>

      <wsdl:part name="in4" type="soapenc:string"/>

      <wsdl:part name="in5" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:message name="fireEventResponse">

      <wsdl:part name="fireEventReturn" type="soapenc:string"/>

   </wsdl:message>

   <wsdl:portType name="EventService">

      <wsdl:operation name="fireEvent" parameterOrder="in0 in1 in2 in3 in4 in5">

         <wsdl:input message="impl:fireEventRequest" name="fireEventRequest"/>

         <wsdl:output message="impl:fireEventResponse" name="fireEventResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="EventServiceSoapBinding" type="impl:EventService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="fireEvent">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="fireEventRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobievent" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="fireEventResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobievent" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="EventServiceService">

      <wsdl:port binding="impl:EventServiceSoapBinding" name="EventService">

         <wsdlsoap:address location="http://localhost:8080/SpagoBI/services/EventService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
