<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:spagobisdktestconnection" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:spagobisdktestconnection" xmlns:intf="urn:spagobisdktestconnection" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="connectResponse">

      <wsdl:part name="connectReturn" type="xsd:boolean"/>

   </wsdl:message>

   <wsdl:message name="connectRequest">

   </wsdl:message>

   <wsdl:portType name="TestConnectionService">

      <wsdl:operation name="connect">

         <wsdl:input message="impl:connectRequest" name="connectRequest"/>

         <wsdl:output message="impl:connectResponse" name="connectResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TestConnectionServiceSoapBinding" type="impl:TestConnectionService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="connect">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="connectRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobisdktestconnection" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="connectResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:spagobisdktestconnection" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TestConnectionServiceService">

      <wsdl:port binding="impl:TestConnectionServiceSoapBinding" name="TestConnectionService">

         <wsdlsoap:address location="http://localhost:8080/SpagoBI/sdk/TestConnectionService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
