module.exports = function (grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    concat: {
      options: {
        banner: "/*! <%= pkg.name %> - v<%= pkg.version %> - " + '<%= grunt.template.today("yyyy-mm-dd") %> */',
        stripBanners: true,
        nonull: true,
      },
      basic_and_extras: {
        files: {
          "dist/knowagecockpit-lib-bundle.js": ["js/lib/angular/angular-gridster/angular-gridster.min.js", "js/lib/angular/angular-drag-and-drop-lists/angular-drag-and-drop-lists.js", "js/lib/angular/angular-json-tree/json-tree.js", "js/lib/openlayers/v6.15.1-dist/ol.js", "js/lib/mathjs/4.0.1/math.min.js"],
          "dist/knowagecockpit-modules-bundle.js": [
            "node_modules/ng-wysiwyg/dist/wysiwyg.min.js",
            "node_modules/jsonformatter/dist/json-formatter.min.js",
            "node_modules/codemirror/lib/codemirror.js",
            "node_modules/codemirror/addon/mode/simple.js",
            "node_modules/codemirror/mode/xml/xml.js",
            "node_modules/codemirror/mode/css/css.js",
            "node_modules/codemirror/mode/r/r.js",
            "node_modules/codemirror/mode/javascript/javascript.js",
            "node_modules/angular-ui-codemirror/src/ui-codemirror.js",
            "node_modules/ag-grid-community/dist/ag-grid-community.min.js",
            "node_modules/toastify-js/src/toastify.js",
            "node_modules/moment/min/moment-with-locales.min.js",
            "node_modules/luxon/build/global/luxon.min.js",
            "node_modules/canvg/dist/browser/canvg.min.js",
            "node_modules/html2canvas/dist/html2canvas.min.js",
            "node_modules/jspdf/dist/jspdf.umd.min.js",
            "node_modules/file-saver/dist/FileSaver.min.js",
          ],
          "dist/knowagecockpit-modules-styles-bundle.css": [
            "node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css",
            "js/lib/angular/angular-material_1.1.0/angular-material.min.css",
            "js/lib/angular/angular-tree/angular-ui-tree.min.css",
            "js/lib/angular/angular-gridster/angular-gridster.min.css",
            "node_modules/toastify-js/src/toastify.css",
            "js/lib/angular/color-picker/angularjs-color-picker.min.css",
            "js/lib/angular/color-picker/mdColorPickerPersonalStyle.css",
            "node_modules/angular-tree-control/css/tree-control.css",
            "node_modules/codemirror/lib/codemirror.css",
            "node_modules/codemirror/theme/eclipse.css",
            "node_modules/jsonformatter/dist/json-formatter.min.css",
            "js/lib/angular/angular-json-tree/json-tree.css",
            "js/lib/openlayers/v6.15.1-dist/ol.css",
          ],
          "dist/knowagecockpit-sources-bundle_<%= pkg.version %>.js": [
            "js/src/angular_1.4/tools/commons/angular-table/AngularTable.js",
            "js/src/angular_1.4/tools/commons/document-tree/DocumentTree.js",
            "js/src/angular_1.4/tools/commons/component-tree/componentTree.js",
            "js/src/angular_1.4/tools/commons/upload-file/FileUpload.js",
            "js/src/angular_1.4/tools/commons/angular-time-picker/angularTimePicker.js",
            "js/src/angular_1.4/tools/commons/angular-list-detail/angularListDetail.js",
            "js/src/angular_1.4/cockpit/directives/commons/calculated-field/calculatedFieldMode.js",
          ],
          "dist/knowagecockpit-sources-cockpit-bundle_<%= pkg.version %>.js": [
            "js/src/angular_1.4/cockpit/cockpit.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-sheet/cockpitSheet.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-grid/cockpitGrid.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-widget/cockpitWidget.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-toolbar/cockpitToolbar.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-style-configurator/cockpitStyleConfigurator.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-cross-configurator/cockpitCrossConfigurator.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-columns-configurator/cockpitColumnsConfigurator.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-column-variables/cockpitColumnVariables.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-selector-configurator/cockpitSelectorConfigurator.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-filters-configuration/cockpitFiltersConfiguration.js",
            "js/src/angular_1.4/cockpit/directives/cockpit-text-configuration/cockpitTextConfiguration.js",
            "js/src/angular_1.4/cockpit/services/*.js",
            "js/src/angular_1.4/tools/commons/services/knModule.js",
            "js/src/angular_1.4/tools/commons/services/knModule_fontIconsService.js",
            "js/src/angular_1.4/tools/commons/services/knModule_aggridLabels.js",
            "js/src/angular_1.4/tools/driversexecution/driversExecutionModule.js",
            "js/src/angular_1.4/tools/driversexecution/driversExecutionService.js",
            "js/src/angular_1.4/tools/driversexecution/driversDependencyService.js",
            "js/src/angular_1.4/tools/driversexecution/*.js",
            "js/src/angular_1.4/tools/documentexecution/documentParamenterElement/documentParamenterElementController.js",
            "js/src/angular_1.4/tools/businessmodelopening/*.js",
            "js/src/angular_1.4/tools/driversexecution/renderparameters/renderParameters.js",
            "js/src/angular_1.4/cockpit/factory/*.js",
          ],
          "dist/knowagecockpit-sources-widgets-bundle_<%= pkg.version %>.js": ["js/src/angular_1.4/cockpit/directives/cockpit-widget/widget/*Widget/*.js"],
          "dist/knowagecockpit-sources-chart-bundle_<%= pkg.version %>.js": [
            "js/src/angular_1.4/chart/designer/directives/custom_directives/customDirectives.js",
            "js/src/angular_1.4/chart/designer/directives/custom_directives/chart-tab/chart-tab.js",
            "js/src/angular_1.4/chart/designer/directives/custom_directives/configuration-tab/configuration-tab.js",
            "js/src/angular_1.4/chart/designer/directives/custom_directives/advanced-tab/advanced-tab.js",
            "js/src/angular_1.4/chart/designer/directives/custom_directives/structure-tab/chartstructure-tab.js",
            "js/src/angular_1.4/chart/commons/Settings.js",
            "js/src/angular_1.4/chart/designer/directives/common_directives/commonDirectives.js",
            "js/src/angular_1.4/chart/designer/directives/third_party/thirdPartyDirectives.js",
            "js/src/angular_1.4/chart/designer/directives/chartDirectives.js",
            "js/src/angular_1.4/chart/designer/services/chartDesignerServices.js",
            "js/src/angular_1.4/chart/designer/services/backward/chartBackwardCompatibilityModule.js",
            "js/src/angular_1.4/chart/designer/services/backward/chartBackwardCompatibilityModule.js",
            "js/src/angular_1.4/chart/designer/services/backward/chartBackwardCompatibility/chartBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/gaugeBackwardCompatibility/gaugeBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/sunburstBackwardCompatibility/sunburstBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/scatterBackwardCompatibility/scatterBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/parallelBackwardCompatibility/parallelBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/treemapBackwardCompatibility/treemapBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/heatmapBackwardCompatibility/heatmapBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/barBackwardCompatibility/barBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/lineBackwardCompatibility/lineBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/backward/radarBackwardCompatibility/radarBackwardCompatibility.js",
            "js/src/angular_1.4/chart/designer/services/channelMessaging.js",
            "js/src/angular_1.4/chart/designer/chartDesigner.js",
            "js/src/angular_1.4/chart/treemap/treemap.js",
            "js/src/angular_1.4/chart/heatmap/heatmap.js",
          ],
          "dist/knowagecockpit-sources-chartrender-bundle_<%= pkg.version %>.js": [
            "js/src/angular_1.4/chart/chartInitializer/chartInitializerModule.js",
            "js/src/angular_1.4/chart/designer/services/chartDesignerServices.js",
            "js/src/angular_1.4/chart/chartInitializer/services/*.js",
            "js/src/angular_1.4/chart/chartRenderer/chartRendererModule.js",
            "js/src/angular_1.4/chart/chartRenderer/directives/chartRenderer.js",
            "js/src/angular_1.4/chart/JsonChartTemplateService/JsonChartTemplateServiceModule.js",
            "js/src/angular_1.4/chart/JsonChartTemplateService/services/JsonChartTemplateService.js",
            "js/src/angular_1.4/chart/chartRenderer/services/chartConfMergeService.js",
            "js/src/angular_1.4/chart/chartRenderer/services/chartSonifyService.js",
            "js/lib/d3/d3.js",
            "js/lib/chartJs/Chart.js",
            "js/src/angular_1.4/chart/d3/*.js",
            "js/src/angular_1.4/chart/commons/Settings.js",
          ],
        },
      },
    },
    uglify: {
      options: {
        mangle: false,
      },
      target: {
        files: {
          "dist/knowagecockpit-lib-bundle.min.js": ["dist/knowagecockpit-lib-bundle.js"],
          "dist/knowagecockpit-modules-bundle.min.js": ["dist/knowagecockpit-modules-bundle.js"],
          "dist/knowagecockpit-sources-bundle_<%= pkg.version %>.min.js": ["dist/knowagecockpit-sources-bundle_<%= pkg.version %>.js"],
          "dist/knowagecockpit-sources-cockpit-bundle_<%= pkg.version %>.min.js": ["dist/knowagecockpit-sources-cockpit-bundle_<%= pkg.version %>.js"],
          "dist/knowagecockpit-sources-widgets-bundle_<%= pkg.version %>.min.js": ["dist/knowagecockpit-sources-widgets-bundle_<%= pkg.version %>.js"],
          "dist/knowagecockpit-sources-chart-bundle_<%= pkg.version %>.min.js": ["dist/knowagecockpit-sources-chart-bundle_<%= pkg.version %>.js"],
          "dist/knowagecockpit-sources-chartrender-bundle_<%= pkg.version %>.min.js": ["dist/knowagecockpit-sources-chartrender-bundle_<%= pkg.version %>.js"],
        },
      },
    },
    cssmin: {
      target: {
        files: {
          "dist/knowagecockpit-modules-styles-bundle.min.css": ["dist/knowagecockpit-modules-styles-bundle.css"],
        },
      },
    },
  });

  // Load the plugin that provides the "concat" task.
  grunt.loadNpmTasks("grunt-contrib-concat");
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.registerTask("knowagecockpit-concat", ["concat"]);
};
